import { BadRequestException, ConflictException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { AuthorizationService } from '../authorization/authorization.service.js';
import { auditData } from '../common/audit.js';
import { requestFingerprint } from '../common/mutation-protection.js';
import { isOperationIdempotencyCollision } from '../common/operation-idempotency.js';
import { PrismaService } from '../identity/prisma.service.js';

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const routes = { group: 'POST /api/app/schools/:schoolId/finance/receivable-groups', receivable: 'POST /api/app/schools/:schoolId/finance/receivables', groupLifecycle: 'POST /api/app/schools/:schoolId/finance/receivable-groups/:groupId/lifecycle', receivableLifecycle: 'POST /api/app/schools/:schoolId/finance/receivables/:receivableId/lifecycle' };
const validation = (field: string, message: string) => new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { [field]: message } });

@Injectable()
export class FinanceService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService) {}
  private school(schoolId: string) { if (!uuid.test(schoolId)) throw validation('schoolId', 'ID trường không hợp lệ.'); return schoolId; }
  private actor(identityId: string, schoolId: string) { return this.authorization.resolve(identityId, this.school(schoolId), 'app', 'FINANCE_MANAGE'); }
  private text(value: unknown, field: string, required = true, limit = 200) { const result = typeof value === 'string' ? value.trim() : ''; if ((required && !result) || result.length > limit) throw validation(field, required ? `Cần từ 1 đến ${limit} ký tự.` : `Không quá ${limit} ký tự.`); return result || null; }
  private identifier(value: unknown, field: string) { if (typeof value !== 'string' || !uuid.test(value)) throw validation(field, 'ID không hợp lệ.'); return value; }
  private price(value: unknown) { if (typeof value !== 'string' || !/^\d+$/.test(value) || BigInt(value) <= 0n || BigInt(value) > 9007199254740991n) throw validation('defaultUnitPrice', 'Đơn giá VND phải là số nguyên dương an toàn.'); return BigInt(value); }
  private groupDto(value: any) { const status = value.lifecycleTransitions?.[0]?.status ?? null; return { id: value.id, name: value.name, status, createdAt: value.createdAt.toISOString() }; }
  private receivableDto(value: any) { const status = value.lifecycleTransitions?.[0]?.status ?? null; const groupStatus = value.group?.lifecycleTransitions?.[0]?.status ?? 'ACTIVE'; return { id: value.id, groupId: value.groupId, code: value.code, displayName: value.displayName, unitLabel: value.unitLabel, defaultUnitPrice: value.defaultUnitPrice.toString(), status, available: status === 'ACTIVE' && groupStatus === 'ACTIVE', createdAt: value.createdAt.toISOString() }; }
  async read(identityId: string, schoolId: string) { schoolId = this.school(schoolId); await this.actor(identityId, schoolId); const [groups, receivables] = await Promise.all([this.prisma.receivableGroup.findMany({ where: { schoolId }, include: { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 } }, orderBy: { name: 'asc' } }), this.prisma.receivable.findMany({ where: { schoolId }, include: { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 }, group: { include: { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 } } } }, orderBy: { displayName: 'asc' } })]); return { groups: groups.map((item) => this.groupDto(item)), receivables: receivables.map((item) => this.receivableDto(item)) }; }
  async operation(identityId: string, schoolId: string, operationId: string) { schoolId = this.school(schoolId); const actor = await this.actor(identityId, schoolId); if (!uuid.test(operationId)) throw new NotFoundException({ code: 'OPERATION_NOT_FOUND', message: 'Không tìm thấy thao tác.' }); const operation = await this.prisma.operation.findFirst({ where: { id: operationId, schoolId, membershipId: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP' } }); if (!operation) throw new NotFoundException({ code: 'OPERATION_NOT_FOUND', message: 'Không tìm thấy thao tác.' }); return { id: operation.id, status: operation.status, outcome: operation.outcome }; }
  async createGroup(identityId: string, schoolId: string, key: string, operationId: string, body: any) { schoolId = this.school(schoolId); const actor = await this.actor(identityId, schoolId); const input = { name: this.text(body?.name, 'name')! }; return this.mutate(actor, identityId, schoolId, routes.group, key, operationId, input, async (tx, operation) => { try { const group = await tx.receivableGroup.create({ data: { schoolId, name: input.name } }); const transition = await tx.receivableGroupLifecycleTransition.create({ data: { schoolId, receivableGroupId: group.id, status: 'ACTIVE', actorIdentityId: identityId, membershipId: actor.membershipId, operationId: operation, sequence: 1 } }); const outcome = this.groupDto({ ...group, lifecycleTransitions: [transition] }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'RECEIVABLE_GROUP_CREATED', operation, null, outcome); return outcome; } catch (error) { if ((error as any)?.code === 'P2002') throw validation('name', 'Tên nhóm đã tồn tại trong trường.'); throw error; } }); }
  async createReceivable(identityId: string, schoolId: string, key: string, operationId: string, body: any) { schoolId = this.school(schoolId); const actor = await this.actor(identityId, schoolId); const input = { groupId: this.identifier(body?.groupId, 'groupId'), code: this.text(body?.code, 'code', false, 50), displayName: this.text(body?.displayName, 'displayName')!, unitLabel: this.text(body?.unitLabel, 'unitLabel', true, 50)!, defaultUnitPrice: this.price(body?.defaultUnitPrice) }; return this.mutate(actor, identityId, schoolId, routes.receivable, key, operationId, { ...input, defaultUnitPrice: input.defaultUnitPrice.toString() }, async (tx, operation) => { const group = await tx.receivableGroup.findFirst({ where: { id: input.groupId, schoolId }, include: { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 } } }); if (!group) throw new NotFoundException({ code: 'RECEIVABLE_GROUP_NOT_FOUND', message: 'Không tìm thấy nhóm khoản thu.' }); if (group.lifecycleTransitions[0]?.status !== 'ACTIVE') throw validation('groupId', 'Nhóm khoản thu đã ngừng áp dụng.'); try { const item = await tx.receivable.create({ data: { schoolId, ...input } }); const transition = await tx.receivableLifecycleTransition.create({ data: { schoolId, receivableId: item.id, status: 'ACTIVE', actorIdentityId: identityId, membershipId: actor.membershipId, operationId: operation, sequence: 1 } }); const outcome = this.receivableDto({ ...item, lifecycleTransitions: [transition], group }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'RECEIVABLE_CREATED', operation, null, outcome); return outcome; } catch (error) { if ((error as any)?.code === 'P2002') throw validation('code', 'Mã khoản thu đã tồn tại trong trường.'); throw error; } }); }
  async transitionGroup(identityId: string, schoolId: string, id: string, key: string, operationId: string, body: any) { return this.transition('group', identityId, this.school(schoolId), id, key, operationId, body); }
  async transitionReceivable(identityId: string, schoolId: string, id: string, key: string, operationId: string, body: any) { return this.transition('receivable', identityId, this.school(schoolId), id, key, operationId, body); }
  private async transition(kind: 'group' | 'receivable', identityId: string, schoolId: string, id: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); this.identifier(id, kind === 'group' ? 'groupId' : 'receivableId'); const status = body?.status; const reason = this.text(body?.reason, 'reason', true, 500)!; if (!['ACTIVE', 'INACTIVE'].includes(status)) throw validation('status', 'Trạng thái không hợp lệ.'); const route = kind === 'group' ? routes.groupLifecycle : routes.receivableLifecycle; return this.mutate(actor, identityId, schoolId, route, key, operationId, { id, status, reason }, async (tx, operation) => { const model = kind === 'group' ? tx.receivableGroup : tx.receivable; const transitionModel = kind === 'group' ? tx.receivableGroupLifecycleTransition : tx.receivableLifecycleTransition; const include = kind === 'group' ? { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 } } : { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 }, group: { include: { lifecycleTransitions: { orderBy: { sequence: 'desc' }, take: 1 } } } }; const item = await model.findFirst({ where: { id, schoolId }, include }); if (!item) throw new NotFoundException({ code: kind === 'group' ? 'RECEIVABLE_GROUP_NOT_FOUND' : 'RECEIVABLE_NOT_FOUND', message: 'Không tìm thấy catalog khoản thu.' }); const prior = item.lifecycleTransitions[0]; if (!prior || prior.status === status) throw validation('status', 'Bản ghi đã ở trạng thái này.'); if (kind === 'receivable' && status === 'ACTIVE' && item.group.lifecycleTransitions[0]?.status !== 'ACTIVE') throw validation('status', 'Không thể kích hoạt khoản thu khi nhóm đã ngừng áp dụng.'); const transition = await transitionModel.create({ data: { schoolId, [kind === 'group' ? 'receivableGroupId' : 'receivableId']: id, previousStatus: prior.status, status, reason, actorIdentityId: identityId, membershipId: actor.membershipId, operationId: operation, sequence: prior.sequence + 1 } }); const oldValue = kind === 'group' ? this.groupDto(item) : this.receivableDto(item); const outcome = kind === 'group' ? this.groupDto({ ...item, lifecycleTransitions: [transition] }) : this.receivableDto({ ...item, lifecycleTransitions: [transition] }); await this.audit(tx, schoolId, identityId, actor.membershipId, kind === 'group' ? 'RECEIVABLE_GROUP_LIFECYCLE_CHANGED' : 'RECEIVABLE_LIFECYCLE_CHANGED', operation, oldValue, outcome); return outcome; }); }
  private async audit(tx: any, schoolId: string, identityId: string, membershipId: string, action: string, operationId: string, oldValue: object | null, newValue: object) { await tx.auditRecord.create({ data: auditData(schoolId, { identityId, type: 'SCHOOL_MEMBERSHIP', reference: membershipId, membershipId }, action, { operationId, oldValue, newValue }) }); }
  private async mutate(actor: { membershipId: string }, identityId: string, schoolId: string, route: string, key: string, operationId: string, body: unknown, work: (tx: any, operation: string) => Promise<unknown>) { if (!uuid.test(key) || !uuid.test(operationId)) throw new UnauthorizedException({ code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Cần Idempotency-Key và X-Operation-Id UUID.' }); const fingerprint = requestFingerprint(body); const replay = async () => this.prisma.operation.findFirst({ where: { schoolId, actorReference: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP', route, idempotencyKey: key } }); const operationById = async () => this.prisma.operation.findFirst({ where: { id: operationId, schoolId, membershipId: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP' } }); const existing = await replay(); if (existing) { if (existing.fingerprint !== fingerprint) throw new ConflictException({ code: 'IDEMPOTENCY_CONFLICT', message: 'Idempotency-Key đã dùng cho yêu cầu khác.' }); await this.actor(identityId, schoolId); return { id: existing.id, status: existing.status, outcome: existing.outcome }; } const collision = await operationById(); if (collision) throw new ConflictException({ code: 'OPERATION_ID_CONFLICT', message: 'X-Operation-Id đã được dùng. Hãy đối soát Operation trước khi thử lại.', operationId }); try { return await this.prisma.$transaction(async (tx) => { await tx.$queryRaw`SELECT 1 FROM "School" WHERE "id" = ${schoolId}::uuid FOR UPDATE`; const membership = await tx.schoolMembership.findFirst({ where: { id: actor.membershipId, schoolId, userIdentityId: identityId, status: 'ACTIVE', school: { status: 'ACTIVE' }, boundStaffProfile: { employmentStatus: 'ACTIVE', primaryPosition: { status: 'ACTIVE', grants: { some: { capability: 'FINANCE_MANAGE' } } } } } }); if (!membership) throw new NotFoundException({ code: 'FINANCE_CONTEXT_DENIED', message: 'Không thể truy cập catalog khoản thu.' }); const operation = await tx.operation.create({ data: { id: operationId, schoolId, membershipId: actor.membershipId, actorIdentityId: identityId, actorType: 'SCHOOL_MEMBERSHIP', actorReference: actor.membershipId, route, idempotencyKey: key, fingerprint } }); const outcome = await work(tx, operation.id); const completed = await tx.operation.update({ where: { id: operation.id }, data: { status: 'COMPLETED', outcome: outcome as any } }); return { id: completed.id, status: completed.status, outcome: completed.outcome }; }); } catch (error) { if (isOperationIdempotencyCollision(error)) { const current = await replay(); if (current?.fingerprint === fingerprint) { await this.actor(identityId, schoolId); return { id: current.id, status: current.status, outcome: current.outcome }; } } if ((error as any)?.code === 'P2002') { const current = await operationById(); if (current) throw new ConflictException({ code: 'OPERATION_ID_CONFLICT', message: 'X-Operation-Id đã được dùng. Hãy đối soát Operation trước khi thử lại.', operationId }); } throw error; } }
}
