import { Body, Controller, Delete, Get, Headers, Param, Post, Put, Query, Req } from '@nestjs/common';
import { audienceConfig } from '../auth/auth.config.js';
import { AuthService } from '../auth/auth.service.js';
import { assertCookieMutation } from '../common/mutation-protection.js';
import { FinanceService } from './finance.service.js';

type RequestLike = { headers: Record<string, string | undefined> };
const cookie = (request: RequestLike, name: string) => request.headers.cookie?.split(';').map((item) => item.trim().split('=')).find(([key]) => key === name)?.[1];

@Controller('api/app/schools/:schoolId/finance')
export class FinanceController {
  constructor(private readonly auth: AuthService, private readonly finance: FinanceService) {}
  private identity(request: RequestLike) { return this.auth.session('app', cookie(request, audienceConfig('app').cookieName)).userIdentityId; }
  private mutation(request: RequestLike, key?: string) { const config = audienceConfig('app'); return assertCookieMutation(request, config.origin, config.csrfCookieName, key); }
  @Get('receivables') async read(@Req() request: RequestLike, @Param('schoolId') schoolId: string) { return { data: await this.finance.read(this.identity(request), schoolId) }; }
  @Get('operations/:operationId') async operation(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('operationId') operationId: string) { return { data: await this.finance.operation(this.identity(request), schoolId, operationId) }; }
  @Get('collection-runs') async runs(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('schoolYearId') schoolYearId?: string) { return { data: await this.finance.runs(this.identity(request), schoolId, schoolYearId) }; }
  @Get('collection-run-candidates') async candidates(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('schoolYearId') schoolYearId?: string) { return { data: await this.finance.candidates(this.identity(request), schoolId, schoolYearId) }; }
  @Get('collection-runs/:runId') async run(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string) { return { data: await this.finance.run(this.identity(request), schoolId, runId) }; }
  @Get('invoices/:invoiceId') async invoice(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string) { return { data: await this.finance.invoice(this.identity(request), schoolId, invoiceId) }; }
  @Get('bank-accounts') async bankAccounts(@Req() request: RequestLike, @Param('schoolId') schoolId: string) { return { data: await this.finance.bankAccounts(this.identity(request), schoolId) }; }
  @Get('promotion-policies') async promotionPolicies(@Req() request: RequestLike, @Param('schoolId') schoolId: string) { return { data: await this.finance.promotionPolicies(this.identity(request), schoolId) }; }
  @Get('promotion-students') async promotionStudents(@Req() request: RequestLike, @Param('schoolId') schoolId: string) { return { data: await this.finance.promotionStudents(this.identity(request), schoolId) }; }
  @Get('collection-runs/:runId/preview') async preview(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string) { this.mutation(request); return { data: await this.finance.preview(this.identity(request), schoolId, runId) }; }
  @Post('collection-runs') async openRun(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.openRun(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Put('collection-runs/:runId/selection') async selection(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.replaceSelection(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Put('collection-runs/:runId/coverage-selection') async coverageSelection(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.replaceCoverageSelection(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Put('collection-runs/:runId/template-lines') async template(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.saveTemplateLine(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Delete('collection-runs/:runId/template-lines/:lineId') async removeTemplate(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Param('lineId') lineId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.removeTemplateLine(this.identity(request), schoolId, runId, lineId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('collection-runs/:runId/ready') async ready(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.readyRun(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('collection-runs/:runId/generate') async generate(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.generateRun(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '') }; }
  @Post('collection-runs/:runId/generation/pause') async pauseGeneration(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.pauseGeneration(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '') }; }
  @Post('collection-runs/:runId/generation/resume') async resumeGeneration(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.resumeGeneration(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '') }; }
  @Post('collection-runs/:runId/generated-students') async addGeneratedStudent(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.addGeneratedStudent(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('collection-runs/:runId/close') async closeRun(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('runId') runId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.closeRun(this.identity(request), schoolId, runId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('invoices/:invoiceId/lines') async addInvoiceLine(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.addInvoiceLine(this.identity(request), schoolId, invoiceId, this.mutation(request, key), operationId ?? '', body) }; }
  @Put('invoices/:invoiceId/lines/:lineId') async editInvoiceLine(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Param('lineId') lineId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.editInvoiceLine(this.identity(request), schoolId, invoiceId, lineId, this.mutation(request, key), operationId ?? '', body) }; }
  @Delete('invoices/:invoiceId/lines/:lineId') async removeInvoiceLine(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Param('lineId') lineId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.removeInvoiceLine(this.identity(request), schoolId, invoiceId, lineId, this.mutation(request, key), operationId ?? '') }; }
  @Post('invoices/:invoiceId/issue') async issueInvoice(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.issueInvoice(this.identity(request), schoolId, invoiceId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('invoices/:invoiceId/receipt') async closeInvoice(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.closeInvoice(this.identity(request), schoolId, invoiceId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('invoices/:invoiceId/revisions') async prepareRevision(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.prepareRevision(this.identity(request), schoolId, invoiceId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('invoices/:invoiceId/issue-revision') async issueRevision(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('invoiceId') invoiceId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.issueRevision(this.identity(request), schoolId, invoiceId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('receivable-groups') async group(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.createGroup(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('receivables') async receivable(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.createReceivable(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('receivable-groups/:groupId/lifecycle') async groupLifecycle(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('groupId') groupId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.transitionGroup(this.identity(request), schoolId, groupId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('receivables/:receivableId/lifecycle') async receivableLifecycle(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('receivableId') receivableId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.transitionReceivable(this.identity(request), schoolId, receivableId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('promotion-policies') async createPromotionPolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.createPromotionPolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('promotion-policy-versions/:versionId/activate') async activatePromotionVersion(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('versionId') versionId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.activatePromotionVersion(this.identity(request), schoolId, versionId, this.mutation(request, key), operationId ?? '') }; }
  @Post('promotion-policy-versions/:versionId/retire') async retirePromotionVersion(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('versionId') versionId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.finance.retirePromotionVersion(this.identity(request), schoolId, versionId, this.mutation(request, key), operationId ?? '') }; }
  @Post('promotion-policy-versions/:versionId/assignments') async assignPromotionStudents(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('versionId') versionId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.assignPromotionStudents(this.identity(request), schoolId, versionId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('promotion-assignments/:assignmentId/end') async endPromotionAssignment(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('assignmentId') assignmentId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.finance.endPromotionAssignment(this.identity(request), schoolId, assignmentId, this.mutation(request, key), operationId ?? '', body) }; }
}
