import { FormEvent, useEffect, useRef, useState } from 'react';
import type { Session } from './auth-session';

type School = { id: string; name: string; slug: string; studentCodePrefix: string; status: 'ACTIVE' | 'SUSPENDED'; ownerEmail: string; ownerBound: boolean; updatedAt: string };
type PendingOperation = { id: string; key: string; route: string; body?: string; identityId: string; grantId: string };
const apiUrl = typeof __API_URL__ === 'undefined' ? '' : __API_URL__;
const csrfName = typeof __CSRF_COOKIE_NAME__ === 'undefined' ? 'ops_csrf' : __CSRF_COOKIE_NAME__;
const csrf = () => document.cookie.split('; ').find((entry) => entry.startsWith(`${csrfName}=`))?.slice(csrfName.length + 1);
const uuid = () => crypto.randomUUID();
const pendingKey = 'passionedu.ops.pending-operation';

export function OpsSchools({ session, clear }: { session: Session; clear: () => void }) {
  const [schools, setSchools] = useState<School[]>([]);
  const [error, setError] = useState('');
  const [dialog, setDialog] = useState<{ school?: School; action: 'provision' | 'lifecycle' }>();
  const [form, setForm] = useState({ name: '', slug: '', ownerEmail: '', studentCodePrefix: '' });
  const [pending, setPending] = useState(false);
  const [reconciling, setReconciling] = useState<PendingOperation>();
  const opener = useRef<HTMLButtonElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);
  const mounted = useRef(true);
  const clearSafe = () => { sessionStorage.removeItem(pendingKey); if (mounted.current) { setSchools([]); setDialog(undefined); setReconciling(undefined); clear(); } };
  const load = async () => { const response = await fetch(`${apiUrl}/api/ops/schools`, { credentials: 'include' }); if ([401, 403].includes(response.status)) return clearSafe(); if (!response.ok) throw new Error('Không thể tải danh sách trường.'); if (mounted.current) setSchools((await response.json() as { data: School[] }).data); };
  const closeDialog = () => { if (!pending && !reconciling) { setDialog(undefined); opener.current?.focus(); } };
  const reconcile = async (operation: PendingOperation) => { if (!mounted.current) return; setReconciling(operation); setPending(true); try { const response = await fetch(`${apiUrl}/api/ops/operations/${operation.id}`, { credentials: 'include' }); if ([401, 403].includes(response.status)) return clearSafe(); if (!response.ok) throw new Error('Không thể đối soát thao tác.'); const result = (await response.json() as { data: { status: string; outcome?: { message?: string } } }).data; if (result.status === 'COMPLETED') { sessionStorage.removeItem(pendingKey); setReconciling(undefined); await load(); if (mounted.current) { setDialog(undefined); opener.current?.focus(); } } else if (result.status === 'FAILED') { sessionStorage.removeItem(pendingKey); setReconciling(undefined); setError(result.outcome?.message ?? 'Thao tác không thành công.'); } else window.setTimeout(() => void reconcile(operation), 1000); } catch { if (mounted.current) window.setTimeout(() => void reconcile(operation), 1000); } finally { if (mounted.current) setPending(false); } };
  useEffect(() => { mounted.current = true; void load().catch((reason: Error) => mounted.current && setError(reason.message)); return () => { mounted.current = false; }; }, []);
  useEffect(() => { dialogRef.current?.querySelector<HTMLElement>('input, button')?.focus(); }, [dialog]);
  useEffect(() => { if (!dialog) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); closeDialog(); return; } if (event.key !== 'Tab') return; const focusable = [...(dialogRef.current?.querySelectorAll<HTMLElement>('input, button:not([disabled])') ?? [])]; const first = focusable[0]; const last = focusable.at(-1); if (!first || !last) return; if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } }; document.addEventListener('keydown', onKeyDown); return () => document.removeEventListener('keydown', onKeyDown); }, [dialog, pending, reconciling]);
  useEffect(() => { const raw = sessionStorage.getItem(pendingKey); if (!raw) return; try { const operation = JSON.parse(raw) as PendingOperation; if (operation.identityId === session.userIdentityId && operation.grantId === session.platformOperatorGrantId) void reconcile(operation); else sessionStorage.removeItem(pendingKey); } catch { sessionStorage.removeItem(pendingKey); } }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (reconciling || !dialog) return; setPending(true); setError(''); const target = dialog.school; const route = dialog.action === 'provision' ? '/api/ops/schools' : `/api/ops/schools/${target!.id}/${target!.status === 'ACTIVE' ? 'suspend' : 'reactivate'}`; const operation = { id: uuid(), key: uuid(), route, body: dialog.action === 'provision' ? JSON.stringify(form) : undefined, identityId: session.userIdentityId, grantId: session.platformOperatorGrantId }; try { const response = await fetch(`${apiUrl}${route}`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': decodeURIComponent(csrf() ?? ''), 'idempotency-key': operation.key, 'x-operation-id': operation.id }, body: operation.body }); if ([401, 403].includes(response.status)) return clearSafe(); if (!response.ok) throw new Error((await response.json() as { error?: { message?: string } }).error?.message ?? 'Thao tác không thành công.'); await load(); if (mounted.current) { setDialog(undefined); opener.current?.focus(); } } catch (reason) { if (reason instanceof TypeError) { sessionStorage.setItem(pendingKey, JSON.stringify(operation)); setError('Đang kiểm tra kết quả với hệ thống'); void reconcile(operation); } else setError(reason instanceof Error ? reason.message : 'Thao tác không thành công.'); } finally { if (mounted.current) setPending(false); } };
  return <main className="ops-shell"><header><div><p>VẬN HÀNH NỀN TẢNG</p><h1>Trường học</h1><p>Đăng nhập: {session.email}. Không truy cập dữ liệu nghiệp vụ của trường.</p></div><button disabled={Boolean(reconciling)} ref={opener} onClick={() => setDialog({ action: 'provision' })}>Khởi tạo trường</button><button onClick={clear}>Đăng xuất</button></header><p className="notice">Nhân sự vận hành chỉ xem danh tính, vòng đời và chủ sở hữu đầu tiên.</p>{error && <p role="alert">{error}</p>}<div className="table-wrap"><table><caption>Danh sách trường của nền tảng</caption><thead><tr><th>Trường</th><th>Mã trường</th><th>Tiền tố mã học sinh</th><th>Chủ sở hữu đầu tiên</th><th>Trạng thái</th><th>Cập nhật</th><th>Thao tác</th></tr></thead><tbody>{schools.map((school) => <tr key={school.id}><td>{school.name}</td><td>{school.slug}</td><td>{school.studentCodePrefix}</td><td>{school.ownerEmail} ({school.ownerBound ? 'Đã liên kết' : 'Đang chờ liên kết'})</td><td>{school.status === 'ACTIVE' ? 'Đang hoạt động' : 'Đã tạm ngừng'}</td><td>{new Date(school.updatedAt).toLocaleString('vi-VN')}</td><td><button disabled={Boolean(reconciling)} onClick={() => setDialog({ action: 'lifecycle', school })}>{school.status === 'ACTIVE' ? 'Tạm ngừng' : 'Kích hoạt lại'}</button></td></tr>)}</tbody></table></div>{dialog && <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="ops-dialog-title" className="dialog"><form onSubmit={submit}><h2 id="ops-dialog-title">{dialog.action === 'provision' ? 'Xác nhận khởi tạo trường' : `${dialog.school?.status === 'ACTIVE' ? 'Tạm ngừng' : 'Kích hoạt lại'} ${dialog.school?.name}`}</h2>{dialog.action === 'provision' && <><label>Tên trường<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Mã trường<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></label><label>Tiền tố mã học sinh<input required pattern="[A-Za-z][A-Za-z0-9]{0,19}" value={form.studentCodePrefix} onChange={(event) => setForm({ ...form, studentCodePrefix: event.target.value.toUpperCase() })} /></label><label>Email chủ sở hữu đầu tiên<input required type="email" value={form.ownerEmail} onChange={(event) => setForm({ ...form, ownerEmail: event.target.value })} /></label></>}<p>{dialog.action === 'lifecycle' ? 'Yêu cầu nghiệp vụ tiếp tục được chặn ngay sau khi trạng thái trường thay đổi.' : 'Chủ sở hữu sẽ liên kết tài khoản Google ở lần đăng nhập đầu tiên.'}</p><div className="dialog-actions"><button type="button" disabled={pending} onClick={closeDialog}>Hủy</button><button disabled={pending || Boolean(reconciling)}>Xác nhận</button></div></form></div>}</main>;
}
