import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { auditData } from '../common/audit.js';
import { requestFingerprint } from '../common/mutation-protection.js';
import { isOperationIdempotencyCollision } from '../common/operation-idempotency.js';
import { AuthorizationService } from '../authorization/authorization.service.js';
import { PrismaService } from '../identity/prisma.service.js';

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const lifecycles = new Set(['TRIAL', 'WAITING_FOR_CLASS', 'SCHEDULED_TO_START', 'ENROLLED', 'ON_LEAVE', 'WITHDRAWN', 'GRADUATED']);
const terminal = new Set(['ON_LEAVE', 'WITHDRAWN', 'GRADUATED']);
const route = { schoolYear: 'POST /api/app/schools/:schoolId/roster/school-years', class: 'POST /api/app/schools/:schoolId/roster/school-years/:schoolYearId/classes', rename: 'POST /api/app/schools/:schoolId/roster/classes/:classId/name', archive: 'POST /api/app/schools/:schoolId/roster/classes/:classId/archive', student: 'POST /api/app/schools/:schoolId/roster/students', lifecycle: 'POST /api/app/schools/:schoolId/roster/enrollments/:enrollmentId/lifecycle' };

@Injectable()
export class RosterService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService) {}
  private async actor(identityId: string, schoolId: string) { return this.authorization.resolve(identityId, schoolId, 'app', 'ROSTER_MANAGE'); }
  private name(value: unknown, field = 'name') { const name = typeof value === 'string' ? value.trim() : ''; if (!name || name.length > 100) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { [field]: 'Tên cần từ 1 đến 100 ký tự.' } }); return name; }
  private date(value: unknown, field: string) { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value) || new Date(`${value}T00:00:00.000Z`).toISOString().slice(0, 10) !== value) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { [field]: 'Ngày không hợp lệ.' } }); return value; }
  private dateValue(value: unknown, field: string) { return new Date(`${this.date(value, field)}T00:00:00.000Z`); }
  private businessToday() { const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); return `${parts.find((part) => part.type === 'year')!.value}-${parts.find((part) => part.type === 'month')!.value}-${parts.find((part) => part.type === 'day')!.value}`; }
  private schoolYearDto(value: any) { const today = this.businessToday(); return { id: value.id, name: value.name, startsOn: value.startsOn.toISOString().slice(0, 10), endsOn: value.endsOn.toISOString().slice(0, 10), isActive: value.startsOn.toISOString().slice(0, 10) <= today && today < value.endsOn.toISOString().slice(0, 10) }; }
  private classDto(value: any, activeStudentCount = 0) { return { id: value.id, schoolYearId: value.schoolYearId, name: value.name, status: value.status, activeStudentCount, createdAt: value.createdAt.toISOString(), updatedAt: value.updatedAt.toISOString() }; }
  private enrollmentDto(value: any) { return { id: value.id, schoolYearId: value.schoolYearId, classId: value.classId, lifecycle: value.lifecycle, effectiveFrom: value.effectiveFrom.toISOString().slice(0, 10), endedOn: value.endedOn?.toISOString().slice(0, 10) ?? null, schoolYear: { name: value.schoolYearName, startsOn: value.schoolYearStartsOn.toISOString().slice(0, 10), endsOn: value.schoolYearEndsOn.toISOString().slice(0, 10) }, classroom: { name: value.className }, lifecycleHistory: (value.lifecycleTransitions ?? []).map((item: any) => ({ id: item.id, previousLifecycle: item.previousLifecycle, lifecycle: item.lifecycle, effectiveFrom: item.effectiveFrom.toISOString().slice(0, 10), endedOn: item.endedOn?.toISOString().slice(0, 10) ?? null, changedAt: item.createdAt.toISOString() })) }; }
  private studentDto(value: any) { return { id: value.id, studentCode: value.studentCode, fullName: value.fullName, dateOfBirth: value.dateOfBirth.toISOString().slice(0, 10), enrollments: value.enrollments.map((item: any) => this.enrollmentDto(item)) }; }
  async schoolYears(identityId: string, schoolId: string) { await this.actor(identityId, schoolId); return (await this.prisma.schoolYear.findMany({ where: { schoolId }, orderBy: { startsOn: 'desc' } })).map((item) => this.schoolYearDto(item)); }
  async classes(identityId: string, schoolId: string, schoolYearId: string) { await this.actor(identityId, schoolId); await this.year(schoolId, schoolYearId); const classes = await this.prisma.class.findMany({ where: { schoolId, schoolYearId }, orderBy: { createdAt: 'asc' } }); const counts = await this.prisma.studentEnrollment.groupBy({ by: ['classId'], where: { schoolId, schoolYearId, lifecycle: 'ENROLLED', endedOn: null }, _count: { id: true } }); const countByClass = new Map(counts.map((item) => [item.classId, item._count.id])); return classes.map((item) => this.classDto(item, countByClass.get(item.id) ?? 0)); }
  async students(identityId: string, schoolId: string, schoolYearId: string, classId?: string) { await this.actor(identityId, schoolId); await this.year(schoolId, schoolYearId); if (classId && (!uuid.test(classId) || !await this.prisma.class.findFirst({ where: { id: classId, schoolId, schoolYearId } }))) throw new NotFoundException({ code: 'CLASS_NOT_FOUND', message: 'Không tìm thấy lớp.' }); const enrollments = await this.prisma.studentEnrollment.findMany({ where: { schoolId, schoolYearId, ...(classId ? { classId } : {}) }, include: { student: { include: { enrollments: { where: { schoolId }, orderBy: { createdAt: 'asc' }, include: { lifecycleTransitions: { orderBy: { createdAt: 'asc' } } } } } } } }); return enrollments.map((item) => this.studentDto(item.student)); }
  async student(identityId: string, schoolId: string, studentId: string) { await this.actor(identityId, schoolId); const student = await this.prisma.student.findFirst({ where: { id: studentId, schoolId }, include: { enrollments: { where: { schoolId }, orderBy: { createdAt: 'asc' }, include: { lifecycleTransitions: { orderBy: { createdAt: 'asc' } } } } } }); if (!student) throw new NotFoundException({ code: 'STUDENT_NOT_FOUND', message: 'Không tìm thấy học sinh.' }); return this.studentDto(student); }
  async createSchoolYear(identityId: string, schoolId: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); const name = this.name(body?.name); const startsOn = this.date(body?.startsOn, 'startsOn'); const endsOn = this.date(body?.endsOn, 'endsOn'); if (startsOn >= endsOn) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { endsOn: 'Ngày kết thúc phải sau ngày bắt đầu.' } }); return this.mutate(actor, identityId, schoolId, route.schoolYear, key, operationId, { name, startsOn, endsOn }, async (tx, operation) => { const year = await tx.schoolYear.create({ data: { schoolId, name, startsOn: new Date(`${startsOn}T00:00:00.000Z`), endsOn: new Date(`${endsOn}T00:00:00.000Z`) } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'SCHOOL_YEAR_CREATED', operation, { schoolYearId: year.id }); return this.schoolYearDto(year); }); }
  async createClass(identityId: string, schoolId: string, schoolYearId: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); const name = this.name(body?.name); return this.mutate(actor, identityId, schoolId, route.class, key, operationId, { schoolYearId, name }, async (tx, operation) => { await this.year(schoolId, schoolYearId, tx); const classroom = await tx.class.create({ data: { schoolId, schoolYearId, name } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'CLASS_CREATED', operation, { classId: classroom.id }); return this.classDto(classroom); }); }
  async renameClass(identityId: string, schoolId: string, classId: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); const name = this.name(body?.name); return this.mutate(actor, identityId, schoolId, route.rename, key, operationId, { classId, name }, async (tx, operation) => { const classroom = await this.lockClass(tx, schoolId, classId); if (classroom.status === 'ARCHIVED') throw new ConflictException({ code: 'CLASS_ARCHIVED', message: 'Lớp đã lưu trữ chỉ có thể xem.' }); const updated = await tx.class.update({ where: { id: classId }, data: { name } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'CLASS_RENAMED', operation, { classId }); return this.classDto(updated); }); }
  async archiveClass(identityId: string, schoolId: string, classId: string, key: string, operationId: string) { const actor = await this.actor(identityId, schoolId); return this.mutate(actor, identityId, schoolId, route.archive, key, operationId, { classId }, async (tx, operation) => { const classroom = await this.lockClass(tx, schoolId, classId); const activeStudentCount = await tx.studentEnrollment.count({ where: { schoolId, classId, lifecycle: 'ENROLLED', endedOn: null } }); if (classroom.status === 'ARCHIVED') return this.classDto(classroom, activeStudentCount); if (activeStudentCount) throw new ConflictException({ code: 'CLASS_HAS_ACTIVE_STUDENTS', message: 'Lớp còn học sinh đang nhập học.', activeStudentCount }); const updated = await tx.class.update({ where: { id: classId }, data: { status: 'ARCHIVED' } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'CLASS_ARCHIVED', operation, { classId }); return this.classDto(updated); }); }
  async createStudent(identityId: string, schoolId: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); const fullName = this.name(body?.fullName, 'fullName'); const dateOfBirth = this.dateValue(body?.dateOfBirth, 'dateOfBirth'); const schoolYearId = typeof body?.schoolYearId === 'string' ? body.schoolYearId : ''; const classId = typeof body?.classId === 'string' ? body.classId : ''; const lifecycle = typeof body?.lifecycle === 'string' ? body.lifecycle : ''; const effectiveFrom = this.dateValue(body?.effectiveFrom, 'effectiveFrom'); const endedOn = body?.endedOn == null || body.endedOn === '' ? null : this.dateValue(body.endedOn, 'endedOn'); this.lifecycleInterval(lifecycle, effectiveFrom, endedOn); return this.mutate(actor, identityId, schoolId, route.student, key, operationId, { fullName, dateOfBirth: body.dateOfBirth, schoolYearId, classId, lifecycle, effectiveFrom: body.effectiveFrom, endedOn: body.endedOn ?? null }, async (tx, operation) => { const year = await this.year(schoolId, schoolYearId, tx); this.activeYear(year); this.yearInterval(year, effectiveFrom, endedOn); const classroom = await this.lockClass(tx, schoolId, classId); if (classroom.schoolYearId !== schoolYearId) throw new NotFoundException({ code: 'CLASS_NOT_FOUND', message: 'Không tìm thấy lớp.' }); if (classroom.status === 'ARCHIVED') throw new ConflictException({ code: 'CLASS_ARCHIVED', message: 'Lớp đã lưu trữ chỉ có thể xem.' }); const school = await tx.school.update({ where: { id: schoolId }, data: { studentCodeSequence: { increment: 1 } }, select: { studentCodePrefix: true, studentCodeSequence: true } }); const student = await tx.student.create({ data: { schoolId, studentCode: `${school.studentCodePrefix}${school.studentCodeSequence}`, fullName, dateOfBirth } }); const enrollment = await tx.studentEnrollment.create({ data: { schoolId, studentId: student.id, schoolYearId, classId, lifecycle, effectiveFrom, endedOn, schoolYearName: year.name, schoolYearStartsOn: year.startsOn, schoolYearEndsOn: year.endsOn, className: classroom.name } }); await this.transition(tx, schoolId, enrollment, null, identityId, actor.membershipId, operation); await this.audit(tx, schoolId, identityId, actor.membershipId, 'STUDENT_ENROLLMENT_CREATED', operation, { studentId: student.id, enrollmentId: enrollment.id }); return this.studentDto({ ...student, enrollments: [{ ...enrollment, lifecycleTransitions: [] }] }); }); }
  async changeLifecycle(identityId: string, schoolId: string, enrollmentId: string, key: string, operationId: string, body: any) { const actor = await this.actor(identityId, schoolId); const lifecycle = typeof body?.lifecycle === 'string' ? body.lifecycle : ''; const endedOn = body?.endedOn == null || body.endedOn === '' ? null : this.dateValue(body.endedOn, 'endedOn'); return this.mutate(actor, identityId, schoolId, route.lifecycle, key, operationId, { enrollmentId, lifecycle, endedOn: body?.endedOn ?? null }, async (tx, operation) => { const enrollment = await tx.studentEnrollment.findFirst({ where: { id: enrollmentId, schoolId } }); if (!enrollment) throw new NotFoundException({ code: 'ENROLLMENT_NOT_FOUND', message: 'Không tìm thấy enrollment.' }); this.lifecycleInterval(lifecycle, enrollment.effectiveFrom, endedOn); this.yearInterval(enrollment, enrollment.effectiveFrom, endedOn); const classroom = await this.lockClass(tx, schoolId, enrollment.classId); if (classroom.status === 'ARCHIVED') throw new ConflictException({ code: 'CLASS_ARCHIVED', message: 'Lớp đã lưu trữ chỉ có thể xem.' }); const updated = await tx.studentEnrollment.update({ where: { id: enrollment.id }, data: { lifecycle, endedOn } }); await this.transition(tx, schoolId, updated, enrollment.lifecycle, identityId, actor.membershipId, operation); await this.audit(tx, schoolId, identityId, actor.membershipId, 'STUDENT_ENROLLMENT_LIFECYCLE_CHANGED', operation, { enrollmentId, previousLifecycle: enrollment.lifecycle, lifecycle, endedOn: body?.endedOn ?? null }); return this.enrollmentDto({ ...updated, lifecycleTransitions: [] }); }); }
  private lifecycleInterval(lifecycle: string, effectiveFrom: Date, endedOn: Date | null) { if (!lifecycles.has(lifecycle)) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { lifecycle: 'Trạng thái enrollment không hợp lệ.' } }); if (endedOn && effectiveFrom >= endedOn) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { endedOn: 'Ngày kết thúc phải sau ngày bắt đầu.' } }); if ((terminal.has(lifecycle) && !endedOn) || (!terminal.has(lifecycle) && endedOn)) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { endedOn: terminal.has(lifecycle) ? 'Trạng thái kết thúc cần ngày kết thúc.' : 'Trạng thái đang hiệu lực không có ngày kết thúc.' } }); }
  private yearInterval(year: any, effectiveFrom: Date, endedOn: Date | null) { if (effectiveFrom < year.startsOn || effectiveFrom >= year.endsOn || (endedOn && (endedOn < year.startsOn || endedOn >= year.endsOn))) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { effectiveFrom: 'Ngày enrollment phải nằm trong năm học.', ...(endedOn ? { endedOn: 'Ngày kết thúc phải nằm trong năm học.' } : {}) } }); }
  private activeYear(year: any) { const today = this.businessToday(); if (!(year.startsOn.toISOString().slice(0, 10) <= today && today < year.endsOn.toISOString().slice(0, 10))) throw new ConflictException({ code: 'SCHOOL_YEAR_NOT_ACTIVE', message: 'Chỉ có thể tạo enrollment trong năm học đang hoạt động.' }); }
  private async year(schoolId: string, schoolYearId: string, client: any = this.prisma) { if (!uuid.test(schoolYearId)) throw new NotFoundException({ code: 'SCHOOL_YEAR_NOT_FOUND', message: 'Không tìm thấy năm học.' }); const year = await client.schoolYear.findFirst({ where: { id: schoolYearId, schoolId } }); if (!year) throw new NotFoundException({ code: 'SCHOOL_YEAR_NOT_FOUND', message: 'Không tìm thấy năm học.' }); return year; }
  private async lockClass(tx: any, schoolId: string, classId: string) { if (!uuid.test(classId)) throw new NotFoundException({ code: 'CLASS_NOT_FOUND', message: 'Không tìm thấy lớp.' }); await tx.$queryRaw`SELECT 1 FROM "Class" WHERE "id" = ${classId}::uuid AND "schoolId" = ${schoolId}::uuid FOR UPDATE`; const classroom = await tx.class.findFirst({ where: { id: classId, schoolId } }); if (!classroom) throw new NotFoundException({ code: 'CLASS_NOT_FOUND', message: 'Không tìm thấy lớp.' }); return classroom; }
  private async transition(tx: any, schoolId: string, enrollment: any, previousLifecycle: string | null, actorIdentityId: string, membershipId: string, operationId: string) { await tx.studentEnrollmentLifecycleTransition.create({ data: { schoolId, enrollmentId: enrollment.id, previousLifecycle, lifecycle: enrollment.lifecycle, effectiveFrom: enrollment.effectiveFrom, endedOn: enrollment.endedOn, actorIdentityId, membershipId, operationId } }); }
  private async audit(tx: any, schoolId: string, identityId: string, membershipId: string, action: string, operationId: string, provenance: object) { await tx.auditRecord.create({ data: auditData(schoolId, { identityId, type: 'SCHOOL_MEMBERSHIP', reference: membershipId, membershipId }, action, { operationId, ...provenance }) }); }
  private async mutate(actor: { membershipId: string }, identityId: string, schoolId: string, command: string, key: string, operationId: string, body: unknown, work: (tx: any, operationId: string) => Promise<unknown>) { if (!uuid.test(key) || !uuid.test(operationId)) throw new UnauthorizedException({ code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Cần Idempotency-Key và X-Operation-Id UUID.' }); const fingerprint = requestFingerprint(body); const existing = await this.prisma.operation.findFirst({ where: { schoolId, actorReference: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP', route: command, idempotencyKey: key } }); if (existing) { if (existing.fingerprint !== fingerprint) throw new ConflictException({ code: 'IDEMPOTENCY_CONFLICT', message: 'Idempotency-Key đã dùng cho yêu cầu khác.' }); return { id: existing.id, status: existing.status, outcome: existing.outcome }; } try { return await this.prisma.$transaction(async (tx) => { await tx.$queryRaw`SELECT 1 FROM "School" WHERE "id" = ${schoolId}::uuid FOR UPDATE`; const active = await tx.school.findFirst({ where: { id: schoolId, status: 'ACTIVE' }, select: { id: true } }); if (!active) throw new NotFoundException({ code: 'SCHOOL_CONTEXT_DENIED', message: 'Không thể truy cập ngữ cảnh trường này.' }); const current = await tx.schoolMembership.findFirst({ where: { id: actor.membershipId, schoolId, userIdentityId: identityId, status: 'ACTIVE', roleGrants: { some: { role: 'SCHOOL_ADMIN' } } } }); if (!current) throw new ForbiddenException({ code: 'CAPABILITY_DENIED', message: 'Bạn không có quyền thực hiện thao tác này.' }); const op = await tx.operation.create({ data: { id: operationId, schoolId, membershipId: actor.membershipId, actorIdentityId: identityId, actorType: 'SCHOOL_MEMBERSHIP', actorReference: actor.membershipId, route: command, idempotencyKey: key, fingerprint } }); const outcome = await work(tx, op.id); const completed = await tx.operation.update({ where: { id: op.id }, data: { status: 'COMPLETED', outcome: outcome as never } }); return { id: completed.id, status: completed.status, outcome: completed.outcome }; }); } catch (error) { if (isOperationIdempotencyCollision(error)) { const collision = await this.prisma.operation.findFirst({ where: { schoolId, actorReference: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP', route: command, idempotencyKey: key } }); if (collision && collision.fingerprint === fingerprint) return { id: collision.id, status: collision.status, outcome: collision.outcome }; } if (command === route.schoolYear && this.schoolYearConflict(error)) throw new ConflictException({ code: 'SCHOOL_YEAR_OVERLAP', message: 'Năm học bị trùng khoảng thời gian.' }); throw error; } }
  private schoolYearConflict(error: unknown) { return Boolean(error && typeof error === 'object' && (error as { code?: string; meta?: unknown }).code === 'P2039' && JSON.stringify((error as { meta?: unknown }).meta).includes('SchoolYear_school_interval_excl')); }
}
