import { useEffect, useRef, useState } from "react";

type Report = { workspace: string; asOf: string; generatedAt: string; timezone: string; reportDefinitionVersion: string; filters: Record<string, string | null>; summary: Record<string, string | { exact: string; shortfall: string; overpayment: string }>; rows: Array<{ id: string; postedAt?: string; type?: string; billingMonth: string | null; amount?: string; netBilled?: string; actualReceipt?: string; outstanding?: string; formula?: string }> };
const apiUrl = typeof __API_URL__ === "undefined" ? "" : __API_URL__;
const csrfName = typeof __CSRF_COOKIE_NAME__ === "undefined" ? "app_csrf" : __CSRF_COOKIE_NAME__;
const csrf = () => document.cookie.split("; ").find((item) => item.startsWith(`${csrfName}=`))?.slice(csrfName.length + 1);
const vnd = (value: string) => new Intl.NumberFormat("vi-VN").format(BigInt(value));
const workspaces = [{ id: "overview", label: "Tổng quan Finance" }, { id: "collection-runs", label: "Đối soát đợt thu" }, { id: "outstanding", label: "Công nợ" }, { id: "cash-adjustments", label: "Sổ cash/điều chỉnh" }];
const hcmInstant = (value: string) => value ? `${value}:00+07:00` : "";

export function FinanceReportsWorkspace({ schoolId, schoolName, denied }: { schoolId: string; schoolName: string; denied: () => void }) {
  const [workspace, setWorkspace] = useState("overview"); const [asOf, setAsOf] = useState(""); const [report, setReport] = useState<Report>(); const [message, setMessage] = useState(""); const [exporting, setExporting] = useState(false); const active = useRef(schoolId); const sequence = useRef(0);
  const load = async () => { const token = ++sequence.current; setMessage(""); setReport(undefined); const query = hcmInstant(asOf); const response = await fetch(`${apiUrl}/api/app/schools/${schoolId}/finance/reports/${workspace}${query ? `?asOf=${encodeURIComponent(query)}` : ""}`, { credentials: "include" }); if (token !== sequence.current || active.current !== schoolId) return; if ([401, 403].includes(response.status)) { denied(); return; } if (!response.ok) throw new Error("Không thể tải báo cáo từ sổ cái."); const payload = await response.json() as { data: Report }; if (token === sequence.current && active.current === schoolId) setReport(payload.data); };
  useEffect(() => { active.current = schoolId; setExporting(false); void load().catch((error: Error) => setMessage(error.message)); return () => { ++sequence.current; }; }, [schoolId, workspace]);
  const exportCsv = async () => { if (!report || exporting) return; const token = ++sequence.current; const exportSchool = schoolId; setExporting(true); setMessage(""); const filters = { schoolYearId: null, billingMonth: null, runId: null, className: null, groupName: null, status: null, ...report.filters }; try { const response = await fetch(`${apiUrl}/api/app/schools/${exportSchool}/finance/reports/${report.workspace}/exports`, { method: "POST", credentials: "include", headers: { "content-type": "application/json", "x-csrf-token": decodeURIComponent(csrf() ?? "") }, body: JSON.stringify({ asOf: report.asOf, ...filters }) }); if (token !== sequence.current || active.current !== exportSchool) return; if ([401, 403].includes(response.status)) { denied(); return; } if (!response.ok) { setMessage("Không thể tạo tệp CSV."); return; } const { data } = await response.json() as { data: { exportId: string } }; if (token === sequence.current && active.current === exportSchool) window.location.assign(`${apiUrl}/api/app/schools/${exportSchool}/finance/report-exports/${data.exportId}/download`); } finally { if (token === sequence.current && active.current === exportSchool) setExporting(false); } };
  const money = (value: unknown, fallback = "0") => typeof value === "string" ? value : fallback;
  const summaryItems: Array<[string, string]> = report ? [["Tổng gốc", money(report.summary.gross)], ["Giảm ưu đãi", money(report.summary.promotionDiscount)], ["Hoàn/đảo", money(report.summary.refund, money(report.summary.adjustments))], ["Đã lập ròng", money(report.summary.netBilled, money(report.summary.billed))], ["Thực nhận", money(report.summary.actualReceipt)], ["Chênh lệch", money(report.summary.openDifference)], ["Carry", money(report.summary.carryAdjustment)], ["Công nợ chuyển", money(report.summary.debtTransfer)], ["Coverage", money(report.summary.coverage)], ["Còn phải thu", money(report.summary.outstanding)]] : [];
  return <section aria-labelledby="finance-reports-title"><h2 id="finance-reports-title">Báo cáo Finance</h2><p>{schoolName}. Báo cáo chỉ hiển thị dữ liệu sổ cái do máy chủ xác nhận.</p><div role="tablist" aria-label="Không gian báo cáo">{workspaces.map((item) => <button key={item.id} type="button" role="tab" aria-selected={workspace === item.id} onClick={() => setWorkspace(item.id)}>{item.label}</button>)}</div><label>Thời điểm chốt (giờ Việt Nam)<input type="datetime-local" value={asOf} onChange={(event) => setAsOf(event.target.value)} /></label><button type="button" onClick={() => void load().catch((error: Error) => setMessage(error.message))}>Cập nhật báo cáo</button>{message && <p role="alert">{message}</p>}{!report && !message && <p aria-live="polite">Đang tải báo cáo...</p>}{report && <><p>Chốt tại {report.asOf}; tạo lúc {report.generatedAt}; {report.timezone}; {report.reportDefinitionVersion}.</p><p>Bộ lọc máy chủ: {JSON.stringify(report.filters)}</p><dl>{summaryItems.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{`${vnd(value)} VND`}</dd></div>)}</dl><button type="button" disabled={exporting} onClick={() => void exportCsv()}>{exporting ? "Đang tạo CSV..." : "Tải CSV từ máy chủ"}</button><table><caption>{report.workspace === "outstanding" ? "Công nợ effective tại thời điểm chốt" : report.workspace === "collection-runs" ? "Đối soát đợt thu tại thời điểm chốt" : "Ledger Finance tại thời điểm chốt"}</caption><thead><tr><th>Thời điểm</th><th>Loại</th><th>Tháng thu</th><th>VND</th>{report.workspace === "outstanding" && <th>Còn phải thu</th>}</tr></thead><tbody>{report.rows.length ? report.rows.map((row) => <tr key={row.id}><td>{row.postedAt ?? "-"}</td><td>{row.type ?? "Đợt thu"}{row.formula ? ` (${row.formula})` : ""}</td><td>{row.billingMonth ?? "-"}</td><td style={{ textAlign: "right" }}>{vnd(row.amount ?? row.netBilled ?? "0")}</td>{report.workspace === "outstanding" && <td style={{ textAlign: "right" }}>{vnd(row.outstanding ?? "0")}</td>}</tr>) : <tr><td colSpan={report.workspace === "outstanding" ? 5 : 4}>Không có hoạt động sổ cái phù hợp tại thời điểm chốt.</td></tr>}</tbody></table></>}</section>;
}
