-- Every DateTime column becomes TIMESTAMPTZ(3) so an instant no longer depends on the session time zone.
-- Prisma wrote these columns as UTC wall-clock values, so they convert AT TIME ZONE 'UTC'. Values written by
-- a database default (now() in the server time zone) through raw SQL are converted from the server time zone.

-- Invoices generated by raw INSERT took "createdAt" from now() in the server time zone. Their lines were written
-- by Prisma in UTC in the same transaction, so the reading closest to the first line is the true instant.
ALTER TABLE "Invoice" ADD COLUMN "createdAtInstant" TIMESTAMPTZ(3);
-- A helper column, not an Invoice change: the snapshot guards stay off only for this backfill.
ALTER TABLE "Invoice" DISABLE TRIGGER USER;
UPDATE "Invoice" invoice SET "createdAtInstant" = CASE
  WHEN first_line.at IS NOT NULL AND abs(extract(epoch FROM (invoice."createdAt" AT TIME ZONE current_setting('TimeZone')) - (first_line.at AT TIME ZONE 'UTC')))
    < abs(extract(epoch FROM (invoice."createdAt" AT TIME ZONE 'UTC') - (first_line.at AT TIME ZONE 'UTC')))
  THEN invoice."createdAt" AT TIME ZONE current_setting('TimeZone')
  ELSE invoice."createdAt" AT TIME ZONE 'UTC' END
FROM (SELECT i."id", (SELECT min(line."createdAt") FROM "InvoiceLine" line WHERE line."schoolId" = i."schoolId" AND line."invoiceId" = i."id") AS at FROM "Invoice" i) first_line
WHERE first_line."id" = invoice."id";
ALTER TABLE "Invoice" ENABLE TRIGGER USER;

ALTER TABLE "AttendancePolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "AttendanceRecord"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "AuditRecord"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "BankAccount"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "BankAccountLifecycleTransition"
  ALTER COLUMN "changedAt" TYPE TIMESTAMPTZ(3) USING "changedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Class"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRun"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunGeneration"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "leaseExpiresAt" TYPE TIMESTAMPTZ(3) USING "leaseExpiresAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunGenerationItem"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunLifecycleTransition"
  ALTER COLUMN "changedAt" TYPE TIMESTAMPTZ(3) USING "changedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunSelection"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunTemplateLine"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "CoverageRefundEligibility"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "DailyJournal"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "DailyJournalMedia"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "DailyJournalPolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "DailyJournalVersion"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "EnrollmentClassAssignment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "EvidenceReference"
  ALTER COLUMN "confirmedAt" TYPE TIMESTAMPTZ(3) USING "confirmedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "deletedAt" TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC';
ALTER TABLE "FinancePolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "FinanceReportExport"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "downloadedAt" TYPE TIMESTAMPTZ(3) USING "downloadedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "revokedAt" TYPE TIMESTAMPTZ(3) USING "revokedAt" AT TIME ZONE 'UTC';
ALTER TABLE "HandoverPolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "HandoverRecord"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "pickedUpAt" TYPE TIMESTAMPTZ(3) USING "pickedUpAt" AT TIME ZONE 'UTC';
ALTER TABLE "Invoice"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAtInstant",
  ALTER COLUMN "issuedAt" TYPE TIMESTAMPTZ(3) USING "issuedAt" AT TIME ZONE 'UTC';
ALTER TABLE "InvoiceLine"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "sourceRecordedAt" TYPE TIMESTAMPTZ(3) USING "sourceRecordedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "IssuedPromotionApplication"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "LeaveDaySource"
  ALTER COLUMN "issuedAt" TYPE TIMESTAMPTZ(3) USING "issuedAt" AT TIME ZONE 'UTC';
ALTER TABLE "LeaveDaySourceExclusion"
  ALTER COLUMN "excludedAt" TYPE TIMESTAMPTZ(3) USING "excludedAt" AT TIME ZONE 'UTC';
ALTER TABLE "LeavePolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "LeaveRequest"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "decidedAt" TYPE TIMESTAMPTZ(3) USING "decidedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "LeaveRequestDay"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "NotificationSourceEvent"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "pickedUpAt" TYPE TIMESTAMPTZ(3) USING "pickedUpAt" AT TIME ZONE 'UTC';
ALTER TABLE "OAuthTransaction"
  ALTER COLUMN "consumedAt" TYPE TIMESTAMPTZ(3) USING "consumedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC';
ALTER TABLE "Operation"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "ParentAccessPolicyVersion"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "ParentInboxEventRead"
  ALTER COLUMN "readAt" TYPE TIMESTAMPTZ(3) USING "readAt" AT TIME ZONE 'UTC';
ALTER TABLE "ParentProfile"
  ALTER COLUMN "boundAt" TYPE TIMESTAMPTZ(3) USING "boundAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "PlatformOperatorGrant"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "revokedAt" TYPE TIMESTAMPTZ(3) USING "revokedAt" AT TIME ZONE 'UTC';
ALTER TABLE "PositionCapabilityGrant"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "PromotionPolicy"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "PromotionPolicyTarget"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "PromotionPolicyVersion"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Receivable"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "ReceivableGroup"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "ReceivableGroupLifecycleTransition"
  ALTER COLUMN "changedAt" TYPE TIMESTAMPTZ(3) USING "changedAt" AT TIME ZONE 'UTC';
ALTER TABLE "ReceivableLifecycleTransition"
  ALTER COLUMN "changedAt" TYPE TIMESTAMPTZ(3) USING "changedAt" AT TIME ZONE 'UTC';
ALTER TABLE "School"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolCalendarHoliday"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolCalendarVersion"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolMembership"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolPosition"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolProfileVersion"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "SchoolYear"
  ALTER COLUMN "closedAt" TYPE TIMESTAMPTZ(3) USING "closedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StaffClassAssignment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StaffProfile"
  ALTER COLUMN "boundAt" TYPE TIMESTAMPTZ(3) USING "boundAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Student"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StudentEnrollment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StudentEnrollmentLifecycleTransition"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';
ALTER TABLE "StudentParent"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "revokedAt" TYPE TIMESTAMPTZ(3) USING "revokedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StudentPhoto"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "StudentPromotionAssignment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "endedAt" TYPE TIMESTAMPTZ(3) USING "endedAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "UserIdentity"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';
ALTER TABLE "Invoice" DROP COLUMN "createdAtInstant";

-- Columns that were already TIMESTAMPTZ were written by Prisma as UTC wall-clock values without an offset, which
-- a non-UTC server session read as local time: each such instant is early by the server offset. The API now
-- connects with TimeZone=UTC; shift the stored rows back. On a UTC server these updates change nothing.
-- StudentPromotionalCoverage."issuedAt" comes from the database default and is already a true instant.
ALTER TABLE "CollectionRunCoverageSelection" DISABLE TRIGGER USER;
UPDATE "CollectionRunCoverageSelection" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "CollectionRunCoverageSelection" ENABLE TRIGGER USER;
ALTER TABLE "CoverageReversalRequest" DISABLE TRIGGER USER;
UPDATE "CoverageReversalRequest" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC', "decidedAt" = ("decidedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "CoverageReversalRequest" ENABLE TRIGGER USER;
ALTER TABLE "CoverageReversal" DISABLE TRIGGER USER;
UPDATE "CoverageReversal" SET "postedAt" = ("postedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "CoverageReversal" ENABLE TRIGGER USER;
ALTER TABLE "DebtTransfer" DISABLE TRIGGER USER;
UPDATE "DebtTransfer" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "DebtTransfer" ENABLE TRIGGER USER;
ALTER TABLE "InvoicePromotionCoverageFact" DISABLE TRIGGER USER;
UPDATE "InvoicePromotionCoverageFact" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "InvoicePromotionCoverageFact" ENABLE TRIGGER USER;
ALTER TABLE "Receipt" DISABLE TRIGGER USER;
UPDATE "Receipt" SET "postedAt" = ("postedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "Receipt" ENABLE TRIGGER USER;
ALTER TABLE "SettlementCarry" DISABLE TRIGGER USER;
UPDATE "SettlementCarry" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "SettlementCarry" ENABLE TRIGGER USER;
ALTER TABLE "SettlementDifference" DISABLE TRIGGER USER;
UPDATE "SettlementDifference" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "SettlementDifference" ENABLE TRIGGER USER;
ALTER TABLE "SettlementTransfer" DISABLE TRIGGER USER;
UPDATE "SettlementTransfer" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "SettlementTransfer" ENABLE TRIGGER USER;
ALTER TABLE "StaffCodeRegistry" DISABLE TRIGGER USER;
UPDATE "StaffCodeRegistry" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "StaffCodeRegistry" ENABLE TRIGGER USER;
ALTER TABLE "StaffPhoto" DISABLE TRIGGER USER;
UPDATE "StaffPhoto" SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC', "updatedAt" = ("updatedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "StaffPhoto" ENABLE TRIGGER USER;
-- Ledger events: migration backfills are true instants and Prisma rows written before the ledger became
-- TIMESTAMPTZ were converted from UTC; only later Prisma rows are shifted. Coverage issue events copy their coverage.
ALTER TABLE "FinanceLedgerEvent" DISABLE TRIGGER USER;
UPDATE "FinanceLedgerEvent" SET "postedAt" = ("postedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
WHERE "type" <> 'COVERAGE_ISSUED' AND COALESCE("provenance" ->> 'backfill', 'false') <> 'true'
  AND "postedAt" >= COALESCE((SELECT min("finished_at") FROM "_prisma_migrations" WHERE "migration_name" = '20260926000002_finance_ledger_timestamptz_and_full_backfill'), '-infinity'::timestamptz)
    - (((now() AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC') - now());
UPDATE "FinanceLedgerEvent" event SET "postedAt" = coverage."issuedAt"
FROM "StudentPromotionalCoverage" coverage
WHERE event."type" = 'COVERAGE_ISSUED' AND event."schoolId" = coverage."schoolId" AND event."sourceKey" = coverage."id"::text;
ALTER TABLE "FinanceLedgerEvent" ENABLE TRIGGER USER;

-- "issuedAt" is now an instant: its Vietnam calendar date no longer needs the UTC wall-clock conversion.
DO $$
DECLARE definition text;
BEGIN
  definition := pg_get_functiondef('reject_invoice_snapshot_mutation'::regproc);
  IF position('((NEW."issuedAt" AT TIME ZONE ''UTC'') AT TIME ZONE ''Asia/Ho_Chi_Minh'')::date' IN definition) = 0 THEN
    RAISE EXCEPTION 'reject_invoice_snapshot_mutation no longer has the expected issuedAt conversion';
  END IF;
  EXECUTE replace(definition, '((NEW."issuedAt" AT TIME ZONE ''UTC'') AT TIME ZONE ''Asia/Ho_Chi_Minh'')::date', '(NEW."issuedAt" AT TIME ZONE ''Asia/Ho_Chi_Minh'')::date');
END;
$$;
