import { Dialog } from '@base-ui/react/dialog';
import { Link, useLocation } from 'react-router-dom';
import { useEffect, useEffectEvent, useState } from 'react';
import { ApiError, createOperationId } from '../../app/api/client';
import { getParentOperation, type ParentLink, useGrantParents, useParentLinks, useRevokeParent, useStudent } from './api';

const pendingKey = 'anhhoa.pending-parent-mutation';
type PendingMutation = { studentId: string; operationId: string; type: 'grant'; emails: string[] } | { studentId: string; operationId: string; type: 'revoke'; parentId: string; email: string };

function loadPending(studentId: string): PendingMutation | null { try { const raw = sessionStorage.getItem(pendingKey); if (!raw) return null; const pending = JSON.parse(raw) as Partial<PendingMutation>; if (pending.studentId !== studentId || typeof pending.operationId !== 'string' || (pending.type !== 'grant' && pending.type !== 'revoke')) return null; if (pending.type === 'grant' && Array.isArray(pending.emails) && pending.emails.every((email) => typeof email === 'string')) return pending as PendingMutation; if (pending.type === 'revoke' && typeof pending.parentId === 'string' && typeof pending.email === 'string') return pending as PendingMutation; return null; } catch { return null; } }
function savePending(pending: PendingMutation): boolean { try { sessionStorage.setItem(pendingKey, JSON.stringify(pending)); return true; } catch { return false; } }
function clearPending(): void { try { sessionStorage.removeItem(pendingKey); } catch {} }
function isDefiniteClientError(cause: unknown): cause is ApiError { return cause instanceof ApiError && cause.status >= 400 && cause.status < 500 && cause.code !== 'IDEMPOTENCY_CONFLICT'; }

export function StudentDetailPage(): React.JSX.Element {
  const id = useLocation().pathname.split('/')[2] ?? '';
  const student = useStudent(id); const parents = useParentLinks(id); const grant = useGrantParents(); const revoke = useRevokeParent();
  const initialPending = loadPending(id);
  const [emails, setEmails] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [target, setTarget] = useState<ParentLink | null>(null); const [pending, setPending] = useState<PendingMutation | null>(initialPending);
  const reconcile = async (operationId: string) => { setNotice('Đang kiểm tra kết quả'); setError(''); try { const result = await getParentOperation(operationId); if ('state' in result && result.state === 'PENDING') { setError('Thao tác đang được xử lý. Không gửi lại yêu cầu mới; hãy kiểm tra lại kết quả sau.'); return; } clearPending(); setPending(null); await parents.refetch(); setNotice('Đã cập nhật quyền Parent.'); setTarget(null); } catch { setError('Chưa xác định được kết quả thao tác. Không gửi lại yêu cầu mới; hãy kiểm tra lại với cùng thao tác này.'); } };
  const reconcileSaved = useEffectEvent((operationId: string) => { void reconcile(operationId); });
  useEffect(() => { if (initialPending) reconcileSaved(initialPending.operationId); }, []);
  const grantParents = () => { const values = emails.split(/[\n,]/).map((email) => email.trim()).filter(Boolean); if (!values.length) return setError('Nhập ít nhất một email Parent.'); const operationId = createOperationId(); const request: PendingMutation = { studentId: id, operationId, type: 'grant', emails: values }; if (!savePending(request)) return setError('Không thể lưu thao tác an toàn để đối soát. Vui lòng thử lại.'); setPending(request); setError(''); grant.mutate({ studentId: id, emails: values, operationId }, { onSuccess: async (result) => { if ('state' in result && result.state === 'PENDING') return void reconcile(operationId); clearPending(); setPending(null); setEmails(''); await parents.refetch(); setNotice('Đã cấp quyền Parent.'); }, onError: (cause) => { if (isDefiniteClientError(cause)) { clearPending(); setPending(null); setError(cause.message); } else void reconcile(operationId); } }); };
  const revokeParent = () => { if (!target) return; const operationId = createOperationId(); const request: PendingMutation = { studentId: id, operationId, type: 'revoke', parentId: target.parentId, email: target.email }; if (!savePending(request)) return setError('Không thể lưu thao tác an toàn để đối soát. Vui lòng thử lại.'); setPending(request); setError(''); revoke.mutate({ studentId: id, parentId: target.parentId, operationId }, { onSuccess: async (result) => { if ('state' in result && result.state === 'PENDING') return void reconcile(operationId); clearPending(); setPending(null); await parents.refetch(); setTarget(null); setNotice('Đã thu hồi quyền Parent.'); }, onError: (cause) => { if (isDefiniteClientError(cause)) { clearPending(); setPending(null); setError(cause.message); } else void reconcile(operationId); } }); };
  if (student.isPending) return <section className="page"><p aria-live="polite">Đang tải học sinh...</p></section>;
  if (student.error || !student.data) return <section className="page"><h1>Không tìm thấy học sinh</h1><Link to="/hoc-sinh">Quay lại danh sách học sinh</Link></section>;
  const locked = grant.isPending || revoke.isPending || Boolean(pending);
  return <section className="page students-page"><div className="page-heading"><div><h1>{student.data.fullName}</h1><p>Quản lý quyền xem của Parent cho học sinh này.</p></div><Link to="/hoc-sinh">Quay lại danh sách học sinh</Link></div>{notice && <p role="status">{notice}</p>}<section className="table-card parent-grant-card"><h2>Cấp quyền Parent</h2><label>Email Parent, cách nhau bằng dấu phẩy hoặc dòng mới<textarea value={emails} disabled={locked} placeholder="parent1@example.com, parent2@example.com" autoComplete="email" inputMode="email" aria-invalid={Boolean(error)} aria-describedby={error ? 'parent-email-error' : undefined} onChange={(event) => { setEmails(event.target.value); setError(''); }} /></label>{error && <p id="parent-email-error" role="alert">{error}</p>}<div className="parent-grant-actions">{pending && <button type="button" onClick={() => void reconcile(pending.operationId)}>Kiểm tra lại kết quả</button>}<button className="primary-action" type="button" disabled={locked} onClick={grantParents}>{grant.isPending ? 'Đang cấp quyền...' : 'Cấp quyền Parent'}</button></div></section><section className="table-card table-scroll"><h2>Liên kết Parent</h2>{parents.isPending ? <p aria-live="polite">Đang tải Parent...</p> : parents.error ? <p role="alert">Không thể tải Parent.</p> : parents.data?.length === 0 ? <p>Chưa có Parent nào được liên kết với học sinh này.</p> : <table aria-label="Parent của học sinh"><thead><tr><th>Email</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{parents.data?.map((link) => <tr key={link.parentId}><th scope="row">{link.email}</th><td><span className={`status ${link.status === 'ACTIVE' ? 'active' : 'archived'}`}>{link.status === 'ACTIVE' ? 'Đang hiệu lực' : 'Đã thu hồi'}</span></td><td>{link.status === 'ACTIVE' && <button type="button" disabled={locked} onClick={() => setTarget(link)}>Thu hồi</button>}</td></tr>)}</tbody></table>}</section>{target && <Dialog.Root open onOpenChange={(open) => { if (!open && !locked) setTarget(null); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>Thu hồi quyền Parent?</Dialog.Title><p>{target.email} sẽ không còn xem được thông tin của {student.data.fullName}.</p><div className="dialog-actions"><button type="button" disabled={locked} onClick={() => setTarget(null)}>Hủy</button><button className="danger-action" type="button" disabled={locked} onClick={revokeParent}>{revoke.isPending ? 'Đang thu hồi...' : 'Xác nhận thu hồi'}</button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>}</section>;
}
