import { Dialog } from '@base-ui/react/dialog';
import { Link, useLocation } from 'react-router-dom';
import { useEffect, useEffectEvent, useState } from 'react';
import { ApiError, ApiTimeoutError, createOperationId } from '../../app/api/client';
import { getParentOperation, type ParentLink, useGrantParents, useParentLinks, useRevokeParent, useStudent } from './api';

const pendingKey = 'anhhoa.pending-parent-mutation';
type PendingMutation = { studentId: string; operationId: string };

function loadPending(studentId: string): PendingMutation | null {
  try { const raw = sessionStorage.getItem(pendingKey); if (!raw) return null; const pending = JSON.parse(raw) as Partial<PendingMutation>; return pending.studentId === studentId && typeof pending.operationId === 'string' ? pending as PendingMutation : null; } catch { return null; }
}

export function StudentDetailPage(): React.JSX.Element {
  const id = useLocation().pathname.split('/')[2] ?? '';
  const student = useStudent(id); const parents = useParentLinks(id); const grant = useGrantParents(); const revoke = useRevokeParent();
  const initialPending = loadPending(id);
  const [emails, setEmails] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [target, setTarget] = useState<ParentLink | null>(null); const [pending, setPending] = useState<PendingMutation | null>(initialPending);
  const reconcile = async (operationId: string) => { setNotice('Đang kiểm tra kết quả'); setError(''); try { const result = await getParentOperation(operationId); if (result.state === 'PENDING') { setError('Thao tác đang được xử lý. Không gửi lại yêu cầu mới; hãy kiểm tra lại kết quả sau.'); return; } sessionStorage.removeItem(pendingKey); setPending(null); await parents.refetch(); setNotice('Đã cập nhật quyền Parent.'); setTarget(null); } catch { setError('Chưa xác định được kết quả thao tác. Không gửi lại yêu cầu mới; hãy kiểm tra lại với cùng thao tác này.'); } };
  const reconcileSaved = useEffectEvent((operationId: string) => { void reconcile(operationId); });
  useEffect(() => { if (initialPending) reconcileSaved(initialPending.operationId); }, []);
  const grantParents = () => { const values = emails.split(/[\n,]/).map((email) => email.trim()).filter(Boolean); if (!values.length) return setError('Nhập ít nhất một email Parent.'); const operationId = createOperationId(); const request = { studentId: id, operationId }; sessionStorage.setItem(pendingKey, JSON.stringify(request)); setPending(request); setError(''); grant.mutate({ studentId: id, emails: values, operationId }, { onSuccess: async (result) => { if (result.state === 'PENDING') return void reconcile(operationId); sessionStorage.removeItem(pendingKey); setPending(null); setEmails(''); await parents.refetch(); setNotice('Đã cấp quyền Parent.'); }, onError: (cause) => { if (cause instanceof ApiTimeoutError) void reconcile(operationId); else { sessionStorage.removeItem(pendingKey); setPending(null); setError(cause instanceof ApiError ? cause.message : 'Không thể cấp quyền Parent.'); } } }); };
  const revokeParent = () => { if (!target) return; const operationId = createOperationId(); const request = { studentId: id, operationId }; sessionStorage.setItem(pendingKey, JSON.stringify(request)); setPending(request); setError(''); revoke.mutate({ studentId: id, parentId: target.parentId, operationId }, { onSuccess: async (result) => { if (result.state === 'PENDING') return void reconcile(operationId); sessionStorage.removeItem(pendingKey); setPending(null); await parents.refetch(); setTarget(null); setNotice('Đã thu hồi quyền Parent.'); }, onError: (cause) => { if (cause instanceof ApiTimeoutError) void reconcile(operationId); else { sessionStorage.removeItem(pendingKey); setPending(null); setError(cause instanceof ApiError ? cause.message : 'Không thể thu hồi quyền Parent.'); } } }); };
  if (student.isPending) return <section className="page"><p aria-live="polite">Đang tải học sinh...</p></section>;
  if (student.error || !student.data) return <section className="page"><h1>Không tìm thấy học sinh</h1><Link to="/hoc-sinh">Quay lại danh sách học sinh</Link></section>;
  const locked = grant.isPending || revoke.isPending || Boolean(pending);
  return <section className="page students-page"><div className="page-heading"><div><h1>{student.data.fullName}</h1><p>Quản lý quyền xem của Parent cho học sinh này.</p></div><Link to="/hoc-sinh">Quay lại danh sách học sinh</Link></div>{notice && <p role="status">{notice}</p>}<section className="table-card"><h2>Cấp quyền Parent</h2><label>Email Parent, cách nhau bằng dấu phẩy hoặc dòng mới<textarea value={emails} disabled={locked} onChange={(event) => setEmails(event.target.value)} /></label>{error && <p role="alert">{error}</p>}{pending && <button type="button" onClick={() => void reconcile(pending.operationId)}>Kiểm tra lại kết quả</button>}<button className="primary-action" type="button" disabled={locked} onClick={grantParents}>{grant.isPending ? 'Đang cấp quyền...' : 'Cấp quyền Parent'}</button></section><section className="table-card table-scroll"><h2>Liên kết Parent</h2>{parents.isPending ? <p aria-live="polite">Đang tải Parent...</p> : parents.error ? <p role="alert">Không thể tải Parent.</p> : <table aria-label="Parent của học sinh"><thead><tr><th>Email</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{parents.data?.map((link) => <tr key={link.parentId}><th scope="row">{link.email}</th><td><span className={`status ${link.status === 'ACTIVE' ? 'active' : 'archived'}`}>{link.status}</span></td><td>{link.status === 'ACTIVE' && <button type="button" disabled={locked} onClick={() => setTarget(link)}>Thu hồi</button>}</td></tr>)}</tbody></table>}</section>{target && <Dialog.Root open onOpenChange={(open) => { if (!open && !locked) setTarget(null); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>Thu hồi quyền Parent?</Dialog.Title><p>{target.email} sẽ không còn xem được thông tin của {student.data.fullName}.</p><div className="dialog-actions"><button type="button" disabled={locked} onClick={() => setTarget(null)}>Hủy</button><button className="danger-action" type="button" disabled={locked} onClick={revokeParent}>{revoke.isPending ? 'Đang thu hồi...' : 'Xác nhận thu hồi'}</button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>}</section>;
}
