import { Dialog } from '@base-ui/react/dialog';
import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ApiError, ApiTimeoutError } from '../../app/api/client';
import { type Student, type StudentFilters, useSaveStudent, useStudents, useStudentStatus } from './api';

function filtersFromUrl(params: URLSearchParams): StudentFilters { const page = Number(params.get('page')); const status = params.get('status'); return { search: params.get('search') ?? '', status: status === 'ACTIVE' || status === 'INACTIVE' ? status : '', page: Number.isInteger(page) && page > 0 ? page : 1 }; }

export function StudentsPage(): React.JSX.Element {
  const [params, setParams] = useSearchParams(); const filters = filtersFromUrl(params); const students = useStudents(filters);
  const [editing, setEditing] = useState<Student | null | undefined>(undefined); const [changing, setChanging] = useState<Student | null>(null); const [notice, setNotice] = useState(''); const trigger = useRef<HTMLElement | null>(null);
  const updateFilters = (next: Partial<StudentFilters>) => { const value = { ...filters, ...next, page: next.search !== undefined || next.status !== undefined ? 1 : (next.page ?? filters.page) }; const search = new URLSearchParams(); if (value.search) search.set('search', value.search); if (value.status) search.set('status', value.status); if (value.page > 1) search.set('page', String(value.page)); setParams(search); };
  const closeForm = () => { setEditing(undefined); requestAnimationFrame(() => trigger.current?.focus()); };
  return <section className="page students-page"><div className="page-heading"><div><h1>Học sinh</h1><p>Quản lý danh sách đang học và nghỉ học. Lớp hiện tại sẽ được quản lý ở Story 2.3.</p></div><button className="primary-action" type="button" onClick={(event) => { trigger.current = event.currentTarget; setEditing(null); }}>Thêm học sinh</button></div>
    <div className="table-toolbar"><label>Tìm học sinh<input value={filters.search} onChange={(event) => updateFilters({ search: event.target.value })} placeholder="Tìm theo tên hoặc biệt danh" /></label><label>Trạng thái<select value={filters.status} onChange={(event) => updateFilters({ status: event.target.value as StudentFilters['status'] })}><option value="">Tất cả</option><option value="ACTIVE">Đang học</option><option value="INACTIVE">Nghỉ học</option></select></label></div>
    {students.isPending ? <div className="table-card skeleton" aria-live="polite">Đang tải danh sách học sinh...</div> : students.error ? <div className="table-card error-state" role="alert"><p>Không thể tải danh sách học sinh.</p><button type="button" onClick={() => void students.refetch()}>Thử lại</button></div> : students.data!.data.length === 0 ? students.data!.meta.total > 0 ? <div className="table-card empty-state"><p>Trang này không còn học sinh nào.</p><div className="pagination"><span>Trang {students.data!.meta.page} / {students.data!.meta.pageCount}</span><button type="button" onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button></div></div> : <div className="table-card empty-state"><p>Chưa có học sinh nào phù hợp.</p><button className="primary-action" type="button" onClick={(event) => { trigger.current = event.currentTarget; setEditing(null); }}>Thêm học sinh</button></div> : <><div className="table-card table-scroll"><table aria-label="Danh sách học sinh"><caption className="sr-only">Danh sách học sinh</caption><thead><tr><th>Học sinh</th><th>Biệt danh</th><th>Trạng thái</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{students.data!.data.map((item) => <tr key={item.id}><th scope="row">{item.fullName}</th><td>{item.nickname ?? '-'}</td><td><span className={`status ${item.status === 'ACTIVE' ? 'active' : 'archived'}`}>{item.status === 'ACTIVE' ? 'Đang học' : 'Nghỉ học'}</span></td><td className="row-actions"><button type="button" onClick={(event) => { trigger.current = event.currentTarget; setEditing(item); }}>Sửa</button><button type="button" onClick={(event) => { trigger.current = event.currentTarget; setChanging(item); }}>{item.status === 'ACTIVE' ? 'Cho nghỉ học' : 'Kích hoạt lại'}</button></td></tr>)}</tbody></table></div><div className="pagination"><span>Trang {students.data!.meta.page} / {students.data!.meta.pageCount}</span><button type="button" disabled={filters.page <= 1} onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button><button type="button" disabled={filters.page >= students.data!.meta.pageCount} onClick={() => updateFilters({ page: filters.page + 1 })}>Sau</button></div></>}
    {notice && <p className="action-notice" role="status">{notice}</p>}{editing !== undefined && <StudentForm item={editing} onClose={closeForm} />}{changing && <StatusDialog item={changing} onClose={(message) => { setChanging(null); if (message) setNotice(message); requestAnimationFrame(() => trigger.current?.focus()); }} />}</section>;
}

function StudentForm({ item, onClose }: { item: Student | null; onClose: () => void }): React.JSX.Element {
  const save = useSaveStudent(); const [fullName, setFullName] = useState(item?.fullName ?? ''); const [nickname, setNickname] = useState(item?.nickname ?? ''); const [errors, setErrors] = useState<{ fullName?: string; nickname?: string; form?: string }>({});
  const validateName = () => { const value = fullName.trim(); setFullName(value); const error = !value ? 'Họ tên không được để trống.' : value.length > 100 ? 'Họ tên không được dài quá 100 ký tự.' : undefined; setErrors((current) => ({ ...current, fullName: error })); return !error; };
  const validateNickname = () => { const value = nickname.trim(); setNickname(value); const error = value.length > 100 ? 'Biệt danh không được dài quá 100 ký tự.' : undefined; setErrors((current) => ({ ...current, nickname: error })); return !error; };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!validateName() || !validateNickname()) return; save.mutate({ id: item?.id, input: { fullName: fullName.trim(), ...(nickname.trim() ? { nickname: nickname.trim() } : item ? { nickname: null } : {}) } }, { onSuccess: onClose, onError: (cause) => setErrors(serverErrors(cause)) }); };
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !save.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>{item ? 'Sửa học sinh' : 'Thêm học sinh'}</Dialog.Title><form noValidate onSubmit={submit}><label>Họ tên<input autoFocus maxLength={100} value={fullName} disabled={save.isPending} onChange={(event) => setFullName(event.target.value)} onBlur={validateName} aria-invalid={Boolean(errors.fullName)} aria-describedby={errors.fullName ? 'student-name-error' : undefined} /></label>{errors.fullName && <p id="student-name-error" role="alert">{errors.fullName}</p>}<label>Biệt danh (tùy chọn)<input maxLength={100} value={nickname} disabled={save.isPending} onChange={(event) => setNickname(event.target.value)} onBlur={validateNickname} aria-invalid={Boolean(errors.nickname)} aria-describedby={errors.nickname ? 'student-nickname-error' : undefined} /></label>{errors.nickname && <p id="student-nickname-error" role="alert">{errors.nickname}</p>}<p>Lớp hiện tại sẽ được quản lý ở Story 2.3.</p>{errors.form && <p role="alert">{errors.form}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={save.isPending}>Hủy</button>} /><button className="primary-action" type="submit" disabled={save.isPending}>{save.isPending ? 'Đang lưu...' : 'Lưu học sinh'}</button></div></form></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}

function serverErrors(cause: unknown): { fullName?: string; nickname?: string; form?: string } { if (cause instanceof ApiTimeoutError) return { form: cause.message }; if (!(cause instanceof ApiError)) return { form: 'Không thể lưu học sinh.' }; const errors = cause.fieldErrors ?? []; const fullName = errors.find((error) => error.startsWith('fullName ')); const nickname = errors.find((error) => error.startsWith('nickname ')); return fullName || nickname ? { ...(fullName ? { fullName } : {}), ...(nickname ? { nickname } : {}) } : { form: cause.message }; }

function StatusDialog({ item, onClose }: { item: Student; onClose: (message?: string) => void }): React.JSX.Element {
  const action = useStudentStatus(); const withdrawing = item.status === 'ACTIVE'; const [error, setError] = useState(''); const focus = useRef<HTMLElement | null>(document.activeElement instanceof HTMLElement ? document.activeElement : null);
  useEffect(() => () => focus.current?.focus(), []);
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !action.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>{withdrawing ? `Cho ${item.fullName} nghỉ học?` : `Kích hoạt lại ${item.fullName}?`}</Dialog.Title><p>{withdrawing ? 'Học sinh vẫn được tra cứu nhưng không đủ điều kiện cho các luồng mới.' : 'Học sinh sẽ trở lại trạng thái đang học, không được tự gán Lớp.'}</p>{error && <p role="alert">{error}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={action.isPending}>Hủy</button>} /><button className={withdrawing ? 'danger-action' : 'primary-action'} type="button" disabled={action.isPending} onClick={() => action.mutate({ id: item.id, status: withdrawing ? 'INACTIVE' : 'ACTIVE' }, { onSuccess: () => onClose(withdrawing ? `${item.fullName} đã nghỉ học.` : `${item.fullName} đã được kích hoạt lại.`), onError: (cause) => setError(cause instanceof ApiError ? cause.message : 'Không thể cập nhật trạng thái học sinh.') })}>{action.isPending ? 'Đang cập nhật...' : withdrawing ? 'Xác nhận nghỉ học' : 'Xác nhận kích hoạt lại'}</button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}
