import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { SchoolContext } from './school-context';

const context = { schoolId: 'a', schoolName: 'Trường A', membershipId: 'member-a', capabilities: ['SCHOOL_CONTEXT_READ', 'ACCESS_MANAGE'], navigation: [{ id: 'overview', label: 'Tổng quan' }, { id: 'access', label: 'Quản lý truy cập' }] };
afterEach(() => { vi.unstubAllGlobals(); sessionStorage.clear(); });
describe('SchoolContext', () => {
  it('loads Admin membership management and submits only preset REST input', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] })));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('heading', { name: 'PassionEdu - Trường A' }); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'staff@example.com' } }); fireEvent.submit(screen.getByRole('button', { name: 'Cấp quyền' }).closest('form')!);
    await waitFor(() => expect(fetch).toHaveBeenLastCalledWith('/api/app/schools/a/memberships', expect.objectContaining({ method: 'POST', body: JSON.stringify({ email: 'staff@example.com', roles: ['CLASS_TEACHER'] }) }))); 
  });
  it('requires remain or discard before switching a dirty form', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }, { schoolId: 'b', schoolName: 'Trường B' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: { ...context, schoolId: 'b', schoolName: 'Trường B' } }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] })));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('heading', { name: 'PassionEdu - Trường A' }); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'staff@example.com' } }); fireEvent.change(screen.getByLabelText('Chọn trường'), { target: { value: 'b' } }); expect((await screen.findByRole('dialog')).textContent).toContain('Biểu mẫu đang có nội dung chưa gửi'); expect(fetch).toHaveBeenCalledTimes(3); fireEvent.click(screen.getByRole('button', { name: 'Bỏ nội dung và đổi trường' })); await screen.findByRole('heading', { name: 'PassionEdu - Trường B' }); expect(document.activeElement).toBe(screen.getByRole('heading', { name: 'PassionEdu - Trường B' }));
  });
  it('clears a denied rendered School while preserving the chooser and alternative School', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }, { schoolId: 'b', schoolName: 'Trường B' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] }))).mockResolvedValueOnce(new Response(null, { status: 404 })).mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'b', schoolName: 'Trường B' }] })));
    const clear = vi.fn(); vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={clear} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('heading', { name: 'PassionEdu - Trường A' }); fireEvent.change(screen.getByLabelText('Chọn trường'), { target: { value: 'b' } }); await waitFor(() => expect(screen.queryByRole('heading', { name: 'PassionEdu - Trường A' })).toBeNull()); expect(screen.getByRole('option', { name: 'Trường B' })).toBeTruthy(); expect(clear).not.toHaveBeenCalled();
  });
  it('revalidates the open School when the browser returns to the foreground', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }, { schoolId: 'b', schoolName: 'Trường B' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] }))).mockResolvedValueOnce(new Response(null, { status: 404 })).mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'b', schoolName: 'Trường B' }] })));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('heading', { name: 'PassionEdu - Trường A' }); fireEvent.focus(window);
    await waitFor(() => expect(screen.queryByRole('heading', { name: 'PassionEdu - Trường A' })).toBeNull()); expect(screen.getByRole('option', { name: 'Trường B' })).toBeTruthy();
  });
  it('keeps a timeout reconcile scoped to the selected School and disables switch actions', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] }))).mockRejectedValueOnce(new TypeError('timeout'));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('heading', { name: 'PassionEdu - Trường A' }); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'staff@example.com' } }); fireEvent.submit(screen.getByRole('button', { name: 'Cấp quyền' }).closest('form')!); await waitFor(() => expect(screen.getByLabelText('Chọn trường')).toHaveProperty('disabled', true)); expect(sessionStorage.getItem('passionedu.app.pending-membership-operation')).toContain('schoolId');
    expect((screen.getByLabelText('Email') as HTMLInputElement).value).toBe('staff@example.com'); expect((screen.getByLabelText('CLASS_TEACHER') as HTMLInputElement).checked).toBe(true);
  });
  it('does not let delayed success or denial for A overwrite selected School B', async () => {
    let resolveA!: (response: Response) => void; const delayedA = new Promise<Response>((resolve) => { resolveA = resolve; }); const contextB = { ...context, schoolId: 'b', schoolName: 'Trường B' };
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }, { schoolId: 'b', schoolName: 'Trường B' }] }))).mockReturnValueOnce(delayedA).mockResolvedValueOnce(new Response(JSON.stringify({ data: contextB }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] })));
    const clear = vi.fn(); vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={clear} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); fireEvent.change(screen.getByLabelText('Chọn trường'), { target: { value: 'b' } }); resolveA(new Response(null, { status: 404 })); await screen.findByRole('heading', { name: 'PassionEdu - Trường B' }); expect(screen.queryByRole('heading', { name: 'PassionEdu - Trường A' })).toBeNull(); expect(clear).not.toHaveBeenCalled();
  });
  it('restores role replacement and revocation behind a required reason dialog', async () => {
    const member = { id: 'membership-a', email: 'staff@example.com', status: 'ACTIVE', roles: ['CLASS_TEACHER'] };
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: context }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [member] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: {} }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [member] })));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); await screen.findByRole('button', { name: 'Thu hồi' });
    expect(screen.getByRole('columnheader', { name: 'Thao tác' })).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Thu hồi' })); fireEvent.click(screen.getByRole('button', { name: 'Xác nhận' })); expect(await screen.findByText('Cần nêu lý do.')).toBeTruthy(); fireEvent.change(screen.getByLabelText('Lý do'), { target: { value: 'Nghỉ việc' } }); fireEvent.click(screen.getByRole('button', { name: 'Xác nhận' }));
    await waitFor(() => expect(fetch).toHaveBeenCalledWith('/api/app/schools/a/memberships/membership-a/revoke', expect.objectContaining({ method: 'POST', body: JSON.stringify({ reason: 'Nghỉ việc' }) })));
  });
  it('exposes server-projected roster navigation and protects dirty roster input on switch', async () => {
    const rosterContext = { ...context, capabilities: ['SCHOOL_CONTEXT_READ', 'ROSTER_MANAGE'] as const, navigation: [{ id: 'roster', label: 'Danh bộ' }] };
    const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ data: [{ schoolId: 'a', schoolName: 'Trường A' }, { schoolId: 'b', schoolName: 'Trường B' }] }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: rosterContext }))).mockResolvedValueOnce(new Response(JSON.stringify({ data: [] })));
    vi.stubGlobal('fetch', fetch); render(<SchoolContext clear={vi.fn()} />); fireEvent.change(await screen.findByLabelText('Chọn trường'), { target: { value: 'a' } }); fireEvent.click(await screen.findByRole('button', { name: 'Danh bộ' })); await screen.findByRole('heading', { name: 'Danh bộ' }); fireEvent.change(screen.getByLabelText('Tên năm học'), { target: { value: 'Năm 2026' } }); fireEvent.change(screen.getByLabelText('Chọn trường'), { target: { value: 'b' } });
    expect((await screen.findByRole('dialog')).textContent).toContain('Biểu mẫu đang có nội dung chưa gửi'); expect((screen.getByLabelText('Tên năm học') as HTMLInputElement).value).toBe('Năm 2026');
  });
});
