import { Dialog } from '@base-ui/react/dialog';
import { useRef, useState } from 'react';
import { ApiError, ApiTimeoutError } from '../../app/api/client';
import { type InvoiceTemplateItem, type AmountSource, useDeleteInvoiceTemplateItem, useInvoiceTemplate, useMoveInvoiceTemplateItem, useSaveInvoiceTemplateItem } from './api';

function formatVnd(amount: number): string { return `${new Intl.NumberFormat('vi-VN').format(amount)} đ`; }
export function InvoiceTemplatePage(): React.JSX.Element {
  const template = useInvoiceTemplate(); const [editing, setEditing] = useState<InvoiceTemplateItem | null | undefined>(undefined); const [deleting, setDeleting] = useState<InvoiceTemplateItem | null>(null); const [moveError, setMoveError] = useState(''); const trigger = useRef<HTMLElement | null>(null); const deleteTrigger = useRef<HTMLElement | null>(null); const move = useMoveInvoiceTemplateItem();
  if (template.isPending) return <section className="page"><h1>Mẫu hóa đơn</h1><div className="table-card skeleton" aria-live="polite">Đang tải mẫu hóa đơn...</div></section>;
  if (template.error) return <section className="page"><h1>Mẫu hóa đơn</h1><div className="table-card error-state" role="alert"><p>Không thể tải mẫu hóa đơn.</p><button type="button" onClick={() => void template.refetch()}>Thử lại</button></div></section>;
  const items = template.data!.items;
  const openForm = (event: React.MouseEvent<HTMLButtonElement>, item: InvoiceTemplateItem | null) => { trigger.current = event.currentTarget; setEditing(item); };
  const closeForm = () => { setEditing(undefined); requestAnimationFrame(() => trigger.current?.focus()); };
  return <section className="page"><div className="page-heading"><div><h1>Mẫu hóa đơn</h1><p>Cấu hình các dòng sẽ được dùng cho hóa đơn tạo sau này.</p></div><button className="primary-action" type="button" onClick={(event) => openForm(event, null)}>Thêm dòng mẫu</button></div>
    {moveError && <p role="alert">{moveError}</p>}{items.length === 0 ? <div className="table-card empty-state"><p>Chưa có Dòng mẫu. Hãy thêm dòng đầu tiên trước khi lập hóa đơn.</p><button className="primary-action" type="button" onClick={(event) => openForm(event, null)}>Thêm dòng mẫu</button></div> : <div className="table-card table-scroll"><table aria-label="Dòng mẫu hóa đơn"><caption className="sr-only">Danh sách dòng mẫu hóa đơn</caption><thead><tr><th>Mô tả</th><th>Nhóm thu</th><th>Nguồn tiền</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id}><th scope="row">{item.description}</th><td>{item.feeGroup ?? 'Không phân nhóm'}</td><td>{item.amountSource === 'FIXED' ? formatVnd(item.fixedAmount!) : 'Học phí Lớp'}</td><td className="row-actions"><button type="button" aria-label={`Lên ${item.description}`} disabled={index === 0 || move.isPending} onClick={() => { setMoveError(''); move.mutate({ id: item.id, direction: 'up' }, { onError: (cause) => setMoveError(cause instanceof ApiError ? cause.message : 'Không thể đổi vị trí. Hãy làm mới danh sách để đối soát.') }); }}>Lên</button><button type="button" aria-label={`Xuống ${item.description}`} disabled={index === items.length - 1 || move.isPending} onClick={() => { setMoveError(''); move.mutate({ id: item.id, direction: 'down' }, { onError: (cause) => setMoveError(cause instanceof ApiError ? cause.message : 'Không thể đổi vị trí. Hãy làm mới danh sách để đối soát.') }); }}>Xuống</button><button type="button" onClick={(event) => openForm(event, item)}>Sửa</button><button type="button" onClick={(event) => { deleteTrigger.current = event.currentTarget; setDeleting(item); }}>Bỏ</button></td></tr>)}</tbody></table></div>}
    {editing !== undefined && <ItemForm item={editing} onClose={closeForm} />}{deleting && <DeleteDialog item={deleting} onClose={() => { setDeleting(null); requestAnimationFrame(() => deleteTrigger.current?.focus()); }} />}</section>;
}
function ItemForm({ item, onClose }: { item: InvoiceTemplateItem | null; onClose: () => void }): React.JSX.Element {
  const save = useSaveInvoiceTemplateItem(); const [description, setDescription] = useState(item?.description ?? ''); const [feeGroup, setFeeGroup] = useState(item?.feeGroup ?? ''); const [amountSource, setAmountSource] = useState<AmountSource>(item?.amountSource ?? 'FIXED'); const [fixedAmount, setFixedAmount] = useState(item?.fixedAmount === undefined ? '' : String(item.fixedAmount)); const [errors, setErrors] = useState<{ description?: string; feeGroup?: string; fixedAmount?: string; form?: string }>({});
  const serverErrors = (cause: unknown) => { if (cause instanceof ApiTimeoutError) return { form: cause.message }; if (!(cause instanceof ApiError)) return { form: 'Không thể lưu Dòng mẫu.' }; const fieldErrors = cause.fieldErrors ?? []; const descriptionError = fieldErrors.find((value) => value.startsWith('description ')); const feeGroupError = fieldErrors.find((value) => value.startsWith('feeGroup ')); const fixedAmountError = fieldErrors.find((value) => value.startsWith('fixedAmount ')); return descriptionError || feeGroupError || fixedAmountError ? { ...(descriptionError ? { description: descriptionError } : {}), ...(feeGroupError ? { feeGroup: feeGroupError } : {}), ...(fixedAmountError ? { fixedAmount: fixedAmountError } : {}) } : { form: cause.message }; };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const amount = Number(fixedAmount.replaceAll(/[^0-9]/g, '')); if (!description.trim()) return setErrors({ description: 'Mô tả không được để trống.' }); if (amountSource === 'FIXED' && (!fixedAmount || !Number.isSafeInteger(amount))) return setErrors({ fixedAmount: 'Số tiền phải là số nguyên VND hợp lệ.' }); setErrors({}); save.mutate({ id: item?.id, input: { description: description.trim(), ...(feeGroup.trim() ? { feeGroup: feeGroup.trim() } : {}), amountSource, ...(amountSource === 'FIXED' ? { fixedAmount: amount } : {}) } }, { onSuccess: onClose, onError: (cause) => setErrors(serverErrors(cause)) }); };
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !save.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>{item ? 'Sửa Dòng mẫu' : 'Thêm Dòng mẫu'}</Dialog.Title><form onSubmit={submit} noValidate><label>Mô tả<input aria-invalid={Boolean(errors.description)} aria-describedby={errors.description ? 'template-description-error' : undefined} value={description} maxLength={200} onChange={(event) => setDescription(event.target.value)} disabled={save.isPending} autoFocus /></label>{errors.description && <p id="template-description-error" role="alert">{errors.description}</p>}<label>Nhóm thu (không bắt buộc)<input aria-invalid={Boolean(errors.feeGroup)} aria-describedby={errors.feeGroup ? 'template-fee-group-error' : undefined} value={feeGroup} maxLength={100} onChange={(event) => setFeeGroup(event.target.value)} disabled={save.isPending} /></label>{errors.feeGroup && <p id="template-fee-group-error" role="alert">{errors.feeGroup}</p>}<label>Nguồn tiền<select value={amountSource} onChange={(event) => setAmountSource(event.target.value as AmountSource)} disabled={save.isPending}><option value="FIXED">Số tiền cố định</option><option value="CLASS_TUITION">Học phí Lớp</option></select></label>{amountSource === 'FIXED' && <><label>Số tiền (VND)<input aria-invalid={Boolean(errors.fixedAmount)} aria-describedby={errors.fixedAmount ? 'template-fixed-amount-error' : undefined} inputMode="numeric" value={fixedAmount} onChange={(event) => setFixedAmount(event.target.value.replaceAll(/[^0-9]/g, ''))} disabled={save.isPending} /></label>{errors.fixedAmount && <p id="template-fixed-amount-error" role="alert">{errors.fixedAmount}</p>}</>}{errors.form && <p role="alert">{errors.form}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={save.isPending}>Hủy</button>} /><button className="primary-action" type="submit" disabled={save.isPending}>{save.isPending ? 'Đang lưu...' : 'Lưu Dòng mẫu'}</button></div></form></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}
function DeleteDialog({ item, onClose }: { item: InvoiceTemplateItem; onClose: () => void }): React.JSX.Element { const remove = useDeleteInvoiceTemplateItem(); const [error, setError] = useState(''); return <Dialog.Root open onOpenChange={(open) => { if (!open && !remove.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>Bỏ {item.description}?</Dialog.Title><p>Dòng mẫu này sẽ không còn được dùng cho các hóa đơn tạo sau.</p>{error && <p role="alert">{error}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={remove.isPending}>Hủy</button>} /><button className="danger-action" type="button" disabled={remove.isPending} onClick={() => remove.mutate(item.id, { onSuccess: onClose, onError: (cause) => setError(cause instanceof ApiError ? cause.message : 'Không thể bỏ Dòng mẫu.') })}>{remove.isPending ? 'Đang bỏ...' : 'Xác nhận bỏ'}</button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>; }
