import { afterAll, afterEach, describe, expect, it } from 'vitest';
import { AuthService } from '../modules/auth/auth.service.js';
import { PrismaService } from '../modules/identity/prisma.service.js';
import { OpsService } from '../modules/ops/ops.service.js';

const prisma = new PrismaService(); const ops = new OpsService(prisma); const auth = new AuthService(prisma); const prefix = `ops-${crypto.randomUUID()}`; const identityIds: string[] = []; const schoolIds: string[] = []; const transactionIds: string[] = [];
const key = () => crypto.randomUUID();
async function operator() { const identity = await prisma.userIdentity.create({ data: { emailNormalized: `${prefix}-${crypto.randomUUID()}@example.com`, googleSubject: `subject-${crypto.randomUUID()}` } }); identityIds.push(identity.id); await prisma.platformOperatorGrant.create({ data: { userIdentityId: identity.id } }); return identity.id; }
afterEach(async () => { await prisma.oAuthTransaction.deleteMany({ where: { id: { in: transactionIds.splice(0) } } }); await prisma.auditRecord.deleteMany({ where: { schoolId: { in: schoolIds } } }); await prisma.operation.deleteMany({ where: { OR: [{ schoolId: { in: schoolIds } }, { actorIdentityId: { in: identityIds } }] } }); await prisma.schoolRoleGrant.deleteMany({ where: { schoolId: { in: schoolIds } } }); await prisma.schoolMembership.deleteMany({ where: { schoolId: { in: schoolIds } } }); await prisma.school.deleteMany({ where: { id: { in: schoolIds.splice(0) } } }); await prisma.platformOperatorGrant.deleteMany({ where: { userIdentityId: { in: identityIds } } }); await prisma.userIdentity.deleteMany({ where: { id: { in: identityIds.splice(0) } } }); });
afterAll(async () => prisma.$disconnect());

describe.skipIf(!process.env.TARGET_INTEGRATION_DATABASE_URL)('Ops PostgreSQL provisioning', () => {
  it('atomically creates the school owner graph and a platform-scoped operation', async () => {
    const actor = await operator(); const ownerEmail = `${prefix}-owner@example.com`; const result = await ops.provision(actor, key(), key(), { name: 'Trường test', slug: `${prefix}-school`, ownerEmail }); const schoolId = (result.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId);
    const school = await prisma.school.findUniqueOrThrow({ where: { id: schoolId }, include: { memberships: { include: { roleGrants: true, userIdentity: true } } } }); expect(school.memberships).toHaveLength(1); const membership = school.memberships[0]!; expect(membership.userIdentity.emailNormalized).toBe(ownerEmail); expect(membership.roleGrants).toMatchObject([{ role: 'SCHOOL_ADMIN' }]); const operation = await prisma.operation.findUniqueOrThrow({ where: { id: result.id } }); expect(operation.schoolId).toBeNull(); expect(operation.platformOperatorGrantId).not.toBeNull();
  });
  it('replays the same provision identity and binds a pending owner on matching Google login', async () => {
    const actor = await operator(); const requestKey = key(); const operationId = key(); const input = { name: 'Trường replay', slug: `${prefix}-replay`, ownerEmail: `${prefix}-pending@example.com` }; const first = await ops.provision(actor, requestKey, operationId, input); schoolIds.push((first.outcome as { schoolId: string }).schoolId); const replay = await ops.provision(actor, requestKey, operationId, input); expect(replay.id).toBe(first.id); await expect(ops.provision(actor, requestKey, operationId, { ...input, name: 'Khác' })).rejects.toMatchObject({ status: 409 }); const pending = await prisma.userIdentity.findUniqueOrThrow({ where: { emailNormalized: input.ownerEmail } }); identityIds.push(pending.id); expect(pending.googleSubject).toBeNull();
    const token = (nonce: string) => Buffer.from(JSON.stringify({ iss: 'https://accounts.google.com', sub: `subject-${crypto.randomUUID()}`, email: input.ownerEmail, email_verified: true, aud: 'test-client-id', nonce, exp: Math.ceil(Date.now() / 1000) + 600 })).toString('base64url'); const start = await auth.start('app'); const nonce = new URL(start.authorizationUrl).searchParams.get('nonce')!; const state = new URL(start.authorizationUrl).searchParams.get('state')!; const transaction = await prisma.oAuthTransaction.findUniqueOrThrow({ where: { stateHash: (await import('node:crypto')).createHash('sha256').update(state).digest('base64url') } }); transactionIds.push(transaction.id); await auth.callback('app', state, start.correlation, token(nonce)); await expect(prisma.userIdentity.findUniqueOrThrow({ where: { id: pending.id } })).resolves.toMatchObject({ googleSubject: expect.any(String) });
  });
  it('scopes lifecycle Operations to their School and denies use after grant revoke', async () => {
    const actor = await operator(); const provision = await ops.provision(actor, key(), key(), { name: 'Trường lifecycle', slug: `${prefix}-lifecycle`, ownerEmail: `${prefix}-lifecycle@example.com` }); const schoolId = (provision.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId); const lifecycle = await ops.lifecycle(actor, schoolId, 'SUSPENDED', key(), key()); const operation = await prisma.operation.findUniqueOrThrow({ where: { id: lifecycle.id } }); expect(operation.schoolId).toBe(schoolId); expect(operation.platformOperatorGrantId).not.toBeNull(); await prisma.platformOperatorGrant.update({ where: { userIdentityId: actor }, data: { revokedAt: new Date() } }); await expect(prisma.operation.findUniqueOrThrow({ where: { id: lifecycle.id } })).resolves.toMatchObject({ platformOperatorGrantId: operation.platformOperatorGrantId }); await expect(ops.operation(actor, lifecycle.id)).rejects.toMatchObject({ status: 403 });
  });
});
