import { afterAll, afterEach, describe, expect, it } from 'vitest';
import { AuthService } from '../modules/auth/auth.service.js';
import { PrismaService } from '../modules/identity/prisma.service.js';
import { OpsService } from '../modules/ops/ops.service.js';

const prisma = new PrismaService(); const ops = new OpsService(prisma); const auth = new AuthService(prisma); const prefix = `ops-${crypto.randomUUID()}`; const identityIds: string[] = []; const schoolIds: string[] = []; const transactionIds: string[] = [];
const key = () => crypto.randomUUID();
async function operator() { const identity = await prisma.userIdentity.create({ data: { emailNormalized: `${prefix}-${crypto.randomUUID()}@example.com`, googleSubject: `subject-${crypto.randomUUID()}` } }); identityIds.push(identity.id); await prisma.platformOperatorGrant.create({ data: { userIdentityId: identity.id } }); return identity.id; }
 afterEach(async () => { const schools = schoolIds.splice(0); const identities = identityIds.splice(0); await prisma.$transaction(async (tx) => { await tx.$executeRaw`SELECT set_config('passionedu.allow_history_cleanup', 'on', true)`; await tx.oAuthTransaction.deleteMany({ where: { id: { in: transactionIds.splice(0) } } }); await tx.auditRecord.deleteMany({ where: { schoolId: { in: schools } } }); await tx.receivableGroupLifecycleTransition.deleteMany({ where: { schoolId: { in: schools } } }); await tx.receivableGroup.deleteMany({ where: { schoolId: { in: schools } } }); await tx.operation.deleteMany({ where: { OR: [{ schoolId: { in: schools } }, { actorIdentityId: { in: identities } }] } }); await tx.staffProfile.deleteMany({ where: { schoolId: { in: schools } } }); await tx.positionCapabilityGrant.deleteMany({ where: { schoolId: { in: schools } } }); await tx.schoolPosition.deleteMany({ where: { schoolId: { in: schools } } }); await tx.schoolMembership.deleteMany({ where: { schoolId: { in: schools } } }); await tx.school.deleteMany({ where: { id: { in: schools } } }); await tx.platformOperatorGrant.deleteMany({ where: { userIdentityId: { in: identities } } }); await tx.userIdentity.deleteMany({ where: { id: { in: identities } } }); }); });
afterAll(async () => prisma.$disconnect());

describe.skipIf(!process.env.TARGET_INTEGRATION_DATABASE_URL)('Ops PostgreSQL provisioning', () => {
  it('atomically creates the school owner graph and a platform-scoped operation', async () => {
    const actor = await operator(); const ownerEmail = `${prefix}-owner@example.com`; const result = await ops.provision(actor, key(), key(), { name: 'Trường test', slug: `${prefix}-school`, ownerEmail, studentCodePrefix: 'S' }); const schoolId = (result.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId);
    const positions = await prisma.schoolPosition.findMany({ where: { schoolId }, include: { grants: true, staffProfiles: true } }); expect(positions).toHaveLength(7); const owner = positions.find((position) => position.code === 'HIEU_TRUONG')!; const finance = positions.find((position) => position.code === 'KE_TOAN')!; expect(owner.grants).toEqual(expect.arrayContaining([expect.objectContaining({ capability: 'ROSTER_MANAGE' })])); expect(finance.grants).toEqual(expect.arrayContaining([expect.objectContaining({ capability: 'FINANCE_MANAGE' }), expect.objectContaining({ capability: 'OPERATIONAL_QUEUE_READ' })])); expect(owner.staffProfiles).toMatchObject([{ schoolMembershipId: expect.any(String), employmentStatus: 'ACTIVE' }]); const operation = await prisma.operation.findUniqueOrThrow({ where: { id: result.id } }); expect(operation.schoolId).toBeNull(); expect(operation.platformOperatorGrantId).not.toBeNull(); const groups = await prisma.receivableGroup.findMany({ where: { schoolId }, include: { lifecycleTransitions: true }, orderBy: { name: 'asc' } }); expect(groups.map((group) => group.name)).toEqual(['Khoản thu chung', 'Khoản thu đột xuất', 'Ngoại khóa']); const transitions = groups.flatMap((group) => group.lifecycleTransitions); expect(transitions).toHaveLength(3); expect(transitions).toEqual(expect.arrayContaining(groups.map((group) => expect.objectContaining({ schoolId, receivableGroupId: group.id, previousStatus: null, status: 'ACTIVE', actorIdentityId: actor, membershipId: null, sequence: 1 })))); const defaultOperations = await prisma.operation.findMany({ where: { schoolId, route: 'POST /api/ops/schools/default-receivable-groups' } }); expect(defaultOperations).toHaveLength(1); const [defaultOperation] = defaultOperations; expect(defaultOperation).toMatchObject({ status: 'COMPLETED', platformOperatorGrantId: operation.platformOperatorGrantId, actorIdentityId: actor }); expect(transitions.every((transition) => transition.operationId === defaultOperation!.id)).toBe(true);
  });
  it('replays the same provision identity and binds a pending owner on matching Google login', async () => {
    const actor = await operator(); const requestKey = key(); const operationId = key(); const input = { name: 'Trường replay', slug: `${prefix}-replay`, ownerEmail: `${prefix}-pending@example.com`, studentCodePrefix: 'S' }; const first = await ops.provision(actor, requestKey, operationId, input); const schoolId = (first.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId); const replay = await ops.provision(actor, requestKey, operationId, input); expect(replay.id).toBe(first.id); await expect(prisma.receivableGroup.count({ where: { schoolId } })).resolves.toBe(3); await expect(prisma.receivableGroupLifecycleTransition.count({ where: { schoolId } })).resolves.toBe(3); await expect(prisma.operation.count({ where: { schoolId, route: 'POST /api/ops/schools/default-receivable-groups' } })).resolves.toBe(1); await expect(ops.provision(actor, requestKey, operationId, { ...input, name: 'Khác' })).rejects.toMatchObject({ status: 409 }); const pending = await prisma.userIdentity.findUniqueOrThrow({ where: { emailNormalized: input.ownerEmail } }); identityIds.push(pending.id); expect(pending.googleSubject).toBeNull();
    const token = (nonce: string) => Buffer.from(JSON.stringify({ iss: 'https://accounts.google.com', sub: `subject-${crypto.randomUUID()}`, email: input.ownerEmail, email_verified: true, aud: 'test-client-id', nonce, exp: Math.ceil(Date.now() / 1000) + 600 })).toString('base64url'); const start = await auth.start('app'); const nonce = new URL(start.authorizationUrl).searchParams.get('nonce')!; const state = new URL(start.authorizationUrl).searchParams.get('state')!; const transaction = await prisma.oAuthTransaction.findUniqueOrThrow({ where: { stateHash: (await import('node:crypto')).createHash('sha256').update(state).digest('base64url') } }); transactionIds.push(transaction.id); await auth.callback('app', state, start.correlation, token(nonce)); await expect(prisma.userIdentity.findUniqueOrThrow({ where: { id: pending.id } })).resolves.toMatchObject({ googleSubject: expect.any(String) });
  });
  it('permits null group-transition membership only for the same-School Platform Operator Operation', async () => {
    const actor = await operator(); const provision = await ops.provision(actor, key(), key(), { name: 'Trường guard', slug: `${prefix}-guard`, ownerEmail: `${prefix}-guard@example.com`, studentCodePrefix: 'S' }); const schoolId = (provision.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId);
    const group = await prisma.receivableGroup.findFirstOrThrow({ where: { schoolId } }); const membership = await prisma.schoolMembership.findFirstOrThrow({ where: { schoolId } }); const invalidOperation = await prisma.operation.create({ data: { schoolId, membershipId: membership.id, actorIdentityId: membership.userIdentityId, actorType: 'SCHOOL_MEMBERSHIP', actorReference: membership.id, route: 'guard', fingerprint: 'guard', idempotencyKey: key(), status: 'COMPLETED' } });
    await expect(prisma.receivableGroupLifecycleTransition.create({ data: { schoolId, receivableGroupId: group.id, previousStatus: 'ACTIVE', status: 'INACTIVE', reason: 'Guard test', actorIdentityId: membership.userIdentityId, membershipId: null, operationId: invalidOperation.id, sequence: 2 } })).rejects.toThrow(/Platform Operator Operation/);
  });
  it('scopes lifecycle Operations to their School and denies use after grant revoke', async () => {
    const actor = await operator(); const provision = await ops.provision(actor, key(), key(), { name: 'Trường lifecycle', slug: `${prefix}-lifecycle`, ownerEmail: `${prefix}-lifecycle@example.com`, studentCodePrefix: 'S' }); const schoolId = (provision.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId); const lifecycle = await ops.lifecycle(actor, schoolId, 'SUSPENDED', key(), key()); const operation = await prisma.operation.findUniqueOrThrow({ where: { id: lifecycle.id } }); expect(operation.schoolId).toBe(schoolId); expect(operation.platformOperatorGrantId).not.toBeNull(); await prisma.platformOperatorGrant.update({ where: { userIdentityId: actor }, data: { revokedAt: new Date() } }); await expect(prisma.operation.findUniqueOrThrow({ where: { id: lifecycle.id } })).resolves.toMatchObject({ platformOperatorGrantId: operation.platformOperatorGrantId }); await expect(ops.operation(actor, lifecycle.id)).rejects.toMatchObject({ status: 403 });
  });
  it('records typed platform provenance for provisioning and lifecycle audits', async () => {
    const actor = await operator(); const provision = await ops.provision(actor, key(), key(), { name: 'Trường audit', slug: `${prefix}-audit`, ownerEmail: `${prefix}-audit@example.com`, studentCodePrefix: 'S' }); const schoolId = (provision.outcome as { schoolId: string }).schoolId; schoolIds.push(schoolId); const grant = await prisma.platformOperatorGrant.findFirstOrThrow({ where: { userIdentityId: actor } });
    const suspended = await ops.lifecycle(actor, schoolId, 'SUSPENDED', key(), key()); const reactivated = await ops.lifecycle(actor, schoolId, 'ACTIVE', key(), key()); const audits = await prisma.auditRecord.findMany({ where: { schoolId }, orderBy: { createdAt: 'asc' } }); expect(audits).toEqual(expect.arrayContaining([expect.objectContaining({ action: 'SCHOOL_PROVISIONED', actorIdentityId: actor, actorType: 'PLATFORM_OPERATOR_GRANT', actorReference: grant.id, membershipId: null, reason: null, provenance: expect.objectContaining({ operationId: provision.id }) }), expect.objectContaining({ action: 'SCHOOL_SUSPENDED', actorIdentityId: actor, actorType: 'PLATFORM_OPERATOR_GRANT', actorReference: grant.id, membershipId: null, reason: null, provenance: expect.objectContaining({ operationId: suspended.id }) }), expect.objectContaining({ action: 'SCHOOL_REACTIVATED', actorIdentityId: actor, actorType: 'PLATFORM_OPERATOR_GRANT', actorReference: grant.id, membershipId: null, reason: null, provenance: expect.objectContaining({ operationId: reactivated.id }) })])); expect(audits.every((audit) => audit.provenance && audit.createdAt instanceof Date)).toBe(true);
  });
  it('scopes the same idempotency key independently for platform provisioning and each lifecycle School', async () => {
    const actor = await operator(); const sharedKey = key(); const first = await ops.provision(actor, sharedKey, key(), { name: 'Scope A', slug: `${prefix}-scope-a`, ownerEmail: `${prefix}-scope-a@example.com`, studentCodePrefix: 'S' }); const second = await ops.provision(actor, key(), key(), { name: 'Scope B', slug: `${prefix}-scope-b`, ownerEmail: `${prefix}-scope-b@example.com`, studentCodePrefix: 'S' }); const firstSchool = (first.outcome as { schoolId: string }).schoolId; const secondSchool = (second.outcome as { schoolId: string }).schoolId; schoolIds.push(firstSchool, secondSchool);
    const lifecycleA = await ops.lifecycle(actor, firstSchool, 'SUSPENDED', sharedKey, key()); const lifecycleB = await ops.lifecycle(actor, secondSchool, 'SUSPENDED', sharedKey, key()); expect(lifecycleA.id).not.toBe(lifecycleB.id); await expect(prisma.operation.count({ where: { idempotencyKey: sharedKey } })).resolves.toBe(3);
  });
  it('rethrows a duplicate Operation id without creating a second School or audit', async () => {
    const actor = await operator(); const operationId = key(); const first = await ops.provision(actor, key(), operationId, { name: 'First collision', slug: `${prefix}-collision-first`, ownerEmail: `${prefix}-collision-first@example.com`, studentCodePrefix: 'S' }); schoolIds.push((first.outcome as { schoolId: string }).schoolId); const audits = await prisma.auditRecord.count(); const schools = await prisma.school.count();
    await expect(ops.provision(actor, key(), operationId, { name: 'Second collision', slug: `${prefix}-collision-second`, ownerEmail: `${prefix}-collision-second@example.com`, studentCodePrefix: 'S' })).rejects.toMatchObject({ code: 'P2002' });
    await expect(prisma.school.count()).resolves.toBe(schools); await expect(prisma.auditRecord.count()).resolves.toBe(audits);
  });
  it('rethrows an existing School slug unique violation without an Operation or audit', async () => {
    const actor = await operator(); const slug = `${prefix}-slug-conflict`; const first = await ops.provision(actor, key(), key(), { name: 'First slug', slug, ownerEmail: `${prefix}-slug-first@example.com`, studentCodePrefix: 'S' }); schoolIds.push((first.outcome as { schoolId: string }).schoolId); const operations = await prisma.operation.count({ where: { actorIdentityId: actor } }); const audits = await prisma.auditRecord.count();
    await expect(ops.provision(actor, key(), key(), { name: 'Second slug', slug, ownerEmail: `${prefix}-slug-second@example.com`, studentCodePrefix: 'S' })).rejects.toMatchObject({ code: 'P2002' });
    await expect(prisma.operation.count({ where: { actorIdentityId: actor } })).resolves.toBe(operations); await expect(prisma.auditRecord.count()).resolves.toBe(audits);
  });
});
