import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { createApi } from '../main.js';
import { PrismaService } from '../modules/identity/prisma.service.js';

const prisma = new PrismaService();
const schools: string[] = [];
const parentProfiles: string[] = [];
let app: Awaited<ReturnType<typeof createApi>>;
let baseUrl = '';
const uuid = () => crypto.randomUUID();

function cookie(headers: Headers, name: string) { return headers.getSetCookie().find((value) => value.startsWith(`${name}=`))?.split(';')[0]; }
async function login(email: string, audience: 'app' | 'parent' = 'app') { const start = await fetch(`${baseUrl}/api/${audience}/auth/google/start`, { redirect: 'manual' }); const url = new URL(start.headers.get('location')!); const state = url.searchParams.get('state')!; const nonce = url.searchParams.get('nonce')!; const correlation = cookie(start.headers, `${audience}_oauth_correlation`)!; const token = Buffer.from(JSON.stringify({ iss: 'https://accounts.google.com', sub: `release-${uuid()}`, email, email_verified: true, aud: url.searchParams.get('client_id')!, nonce, exp: Math.ceil(Date.now() / 1000) + 600 })).toString('base64url'); const callback = await fetch(`${baseUrl}/api/${audience}/auth/google/callback?state=${encodeURIComponent(state)}&code=${encodeURIComponent(token)}`, { redirect: 'manual', headers: { cookie: correlation } }); return { session: cookie(callback.headers, `${audience}_session`)!, csrf: cookie(callback.headers, `${audience}_csrf`)!.split('=')[1]! }; }
const headers = (session: { session: string; csrf: string }) => ({ cookie: `${session.session}; app_csrf=${session.csrf}`, origin: 'http://localhost:5173', 'x-csrf-token': session.csrf, 'idempotency-key': uuid(), 'x-operation-id': uuid(), 'content-type': 'application/json' });
async function actor(schoolId: string, email: string) { const identity = await prisma.userIdentity.findUniqueOrThrow({ where: { emailNormalized: email } }); const membership = await prisma.schoolMembership.create({ data: { schoolId, userIdentityId: identity.id } }); const fallbackIdentity = await prisma.userIdentity.create({ data: { emailNormalized: `release-fallback-${uuid()}@example.com` } }); const fallbackMembership = await prisma.schoolMembership.create({ data: { schoolId, userIdentityId: fallbackIdentity.id } }); const position = await prisma.schoolPosition.create({ data: { schoolId, code: `RELEASE_${uuid().replaceAll('-', '').slice(0, 12)}`, name: `Release ${uuid()}` } }); const fallbackPosition = await prisma.schoolPosition.create({ data: { schoolId, code: `RELEASE_FALLBACK_${uuid().replaceAll('-', '').slice(0, 12)}`, name: `Release fallback ${uuid()}` } }); await prisma.positionCapabilityGrant.createMany({ data: ['SCHOOL_CONTEXT_READ', 'ROSTER_MANAGE'].map((capability) => ({ schoolId, positionId: position.id, capability })) }); await prisma.positionCapabilityGrant.create({ data: { schoolId, positionId: fallbackPosition.id, capability: 'ROSTER_MANAGE' } }); await prisma.staffProfile.create({ data: { schoolId, fullName: 'Release actor', email, phone: '0900000000', dateOfBirth: new Date('1990-01-01T00:00:00.000Z'), gender: 'Khác', address: 'Test', primaryPositionId: position.id, schoolMembershipId: membership.id, boundAt: new Date(), boundByMembershipId: membership.id } }); await prisma.staffProfile.create({ data: { schoolId, fullName: 'Release fallback manager', email: fallbackIdentity.emailNormalized, phone: '0900000001', dateOfBirth: new Date('1990-01-01T00:00:00.000Z'), gender: 'Khác', address: 'Test', primaryPositionId: fallbackPosition.id, schoolMembershipId: fallbackMembership.id, boundAt: new Date(), boundByMembershipId: fallbackMembership.id } }); return { membership, position }; }

describe.skipIf(!process.env.TARGET_INTEGRATION_DATABASE_URL)('SchoolPosition HTTP release gate', () => {
  beforeAll(async () => { app = await createApi(); await app.listen(0, '127.0.0.1'); baseUrl = `http://127.0.0.1:${(app.getHttpServer().address() as { port: number }).port}`; });
  afterEach(async () => { const ids = schools.splice(0); const parentIds = parentProfiles.splice(0); await prisma.auditRecord.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.operation.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.parentInboxEventRead.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.notificationSourceEvent.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.leaveRequestDay.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.leaveRequest.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.attendanceRecord.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.schoolCalendarHoliday.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.$transaction(async (tx) => { await tx.$executeRaw`SELECT set_config('passionedu.allow_history_cleanup', 'on', true)`; await tx.schoolCalendarVersion.deleteMany({ where: { schoolId: { in: ids } } }); }); await prisma.studentParent.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.enrollmentClassAssignment.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.studentEnrollment.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.student.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.class.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.schoolYear.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.staffProfile.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.positionCapabilityGrant.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.schoolPosition.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.schoolMembership.deleteMany({ where: { schoolId: { in: ids } } }); await prisma.school.deleteMany({ where: { id: { in: ids } } }); await prisma.studentParent.deleteMany({ where: { parentProfileId: { in: parentIds } } }); await prisma.parentProfile.deleteMany({ where: { id: { in: parentIds } } }); });
  afterAll(async () => { await app.close(); await prisma.$disconnect(); });

  it('authorizes a Position capability, then denies the next request after it is revoked', async () => {
    const email = `release-${uuid()}@example.com`; const session = await login(email); const school = await prisma.school.create({ data: { name: 'Release', slug: `release-${uuid()}`, studentCodePrefix: 'R' } }); schools.push(school.id); const { position } = await actor(school.id, email);
    await expect(fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 200 });
    const revoke = await fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions/${position.id}/grants/ROSTER_MANAGE/revoke`, { method: 'POST', headers: headers(session), body: JSON.stringify({ reason: 'Thu hồi kiểm thử' }) });
    expect(revoke.status).toBe(201);
    await expect(fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 403 });
  });
  it('does not let a Parent session access teacher/app operations or evidence and returns a minimum leave DTO', async () => {
    const school = await prisma.school.create({ data: { name: 'Parent release', slug: `parent-release-${uuid()}`, studentCodePrefix: 'P' } }); schools.push(school.id);
    const email = `parent-release-${uuid()}@example.com`;
    const parent = await prisma.parentProfile.create({ data: { emailNormalized: email, fullName: 'Phụ huynh Release', phone: '0900000013' } }); parentProfiles.push(parent.id);
    const student = await prisma.student.create({ data: { schoolId: school.id, studentCode: `P-${uuid()}`, fullName: 'Bé Parent', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } });
    await prisma.studentParent.create({ data: { schoolId: school.id, studentId: student.id, parentProfileId: parent.id } });
    const leave = await prisma.leaveRequest.create({ data: { schoolId: school.id, studentId: student.id, parentProfileId: parent.id, status: 'PENDING', policyEffectiveFrom: new Date('2026-01-01T00:00:00.000Z'), policyDeadlineLocalTime: '08:00' } });
    const session = await login(email, 'parent');
    const parentHeaders = { cookie: session.session };
    await expect(fetch(`${baseUrl}/api/teacher/schools/${school.id}/attendance`, { method: 'POST', headers: { ...parentHeaders, 'idempotency-key': uuid(), 'x-operation-id': uuid(), 'content-type': 'application/json' }, body: JSON.stringify({ classId: uuid(), studentId: student.id, attendanceOn: '2026-02-09', state: 'PRESENT' }) })).resolves.toMatchObject({ status: 401 });
    await expect(fetch(`${baseUrl}/api/app/schools/${school.id}/leave-requests/${leave.id}/approve`, { method: 'POST', headers: { ...parentHeaders, origin: 'http://localhost:5173', 'x-csrf-token': session.csrf, 'idempotency-key': uuid(), 'x-operation-id': uuid() } })).resolves.toMatchObject({ status: 401 });
    await expect(fetch(`${baseUrl}/api/teacher/schools/${school.id}/attendance-evidence/${uuid()}`, { headers: parentHeaders })).resolves.toMatchObject({ status: 401 });
    expect(await prisma.attendanceRecord.count({ where: { schoolId: school.id } })).toBe(0);
    expect(await prisma.operation.count({ where: { schoolId: school.id } })).toBe(0);
    const response = await fetch(`${baseUrl}/api/parent/schools/${school.id}/leave-requests`, { headers: parentHeaders });
    expect(response.status).toBe(200);
    const body = await response.json() as { data: Array<Record<string, unknown>> };
    expect(body.data).toEqual([expect.objectContaining({ id: leave.id, studentId: student.id, status: 'PENDING', startsOn: null })]);
    expect(Object.keys(body.data[0]!)).toEqual(['id', 'studentId', 'status', 'startsOn', 'operatingDates', 'createdAt']);
  });
  it('validates the Parent attendance HTTP range and fails closed outside an eligible enrollment', async () => {
    const email = `parent-attendance-${uuid()}@example.com`; const school = await prisma.school.create({ data: { name: 'Parent attendance', slug: `parent-attendance-${uuid()}`, studentCodePrefix: 'PA' } }); schools.push(school.id);
    const parent = await prisma.parentProfile.create({ data: { emailNormalized: email, fullName: 'Phụ huynh Attendance', phone: '0900000020' } }); parentProfiles.push(parent.id);
    const student = await prisma.student.create({ data: { schoolId: school.id, studentCode: `PA-${uuid()}`, fullName: 'Bé Attendance', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } }); await prisma.studentParent.create({ data: { schoolId: school.id, studentId: student.id, parentProfileId: parent.id } });
    const session = await login(email, 'parent'); const identity = await prisma.userIdentity.findUniqueOrThrow({ where: { emailNormalized: email } }); const membership = await prisma.schoolMembership.create({ data: { schoolId: school.id, userIdentityId: identity.id } }); const year = await prisma.schoolYear.create({ data: { schoolId: school.id, name: 'Năm attendance', startsOn: new Date('2026-01-01'), endsOn: new Date('2027-01-01') } }); const enrollment = await prisma.studentEnrollment.create({ data: { schoolId: school.id, studentId: student.id, schoolYearId: year.id, lifecycle: 'ENROLLED', effectiveFrom: new Date('2026-02-01'), schoolYearName: year.name, schoolYearStartsOn: year.startsOn, schoolYearEndsOn: year.endsOn } }); await prisma.schoolCalendarVersion.create({ data: { schoolId: school.id, effectiveFrom: new Date('2026-01-01'), actorIdentityId: identity.id, membershipId: membership.id } });
    const validDate = '2026-02-09'; const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const part = (type: string) => parts.find((item) => item.type === type)!.value; const today = `${part('year')}-${part('month')}-${part('day')}`; const route = `${baseUrl}/api/parent/schools/${school.id}/students/${student.id}/attendance`;
    for (const query of ['', '?from=bad&to=2026-02-09', '?from=2026-02-10&to=2026-02-09', '?from=2026-02-01&to=2026-03-04']) { const response = await fetch(`${route}${query}`, { headers: { cookie: session.session } }); expect(response.status).toBe(400); expect((await response.json()).error.code).toBe('VALIDATION_ERROR'); }
    const valid = await fetch(`${route}?from=${validDate}&to=${validDate}`, { headers: { cookie: session.session } }); expect(valid.status).toBe(200); expect(valid.headers.get('cache-control')).toBe('private, no-store'); expect((await valid.json()).data[0]).toEqual({ studentId: student.id, studentDisplayName: 'Bé Attendance', date: validDate, status: 'NOT_RECORDED', updatedAt: null });
    await expect(fetch(`${route}?from=2026-01-31&to=${validDate}`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 404 }); const retained = new Date(`${today}T00:00:00.000Z`); retained.setUTCDate(retained.getUTCDate() - 1); const retainedDate = retained.toISOString().slice(0, 10); await prisma.studentEnrollment.update({ where: { id: enrollment.id }, data: { lifecycle: 'WITHDRAWN', endedOn: new Date(`${today}T00:00:00.000Z`) } }); await expect(fetch(`${route}?from=${retainedDate}&to=${retainedDate}`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 200 }); await expect(fetch(`${route}?from=${today}&to=${today}`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 404 });
  });
  it('returns only active Parent School contexts and removes a revoked School on the next request', async () => {
    const email = `parent-context-${uuid()}@example.com`;
    const first = await prisma.school.create({ data: { name: 'Parent context A', slug: `parent-context-a-${uuid()}`, studentCodePrefix: 'A' } });
    const second = await prisma.school.create({ data: { name: 'Parent context B', slug: `parent-context-b-${uuid()}`, studentCodePrefix: 'B' } });
    schools.push(first.id, second.id);
    const parent = await prisma.parentProfile.create({ data: { emailNormalized: email, fullName: 'Phụ huynh Context', phone: '0900000014' } }); parentProfiles.push(parent.id);
    const firstStudent = await prisma.student.create({ data: { schoolId: first.id, studentCode: `A-${uuid()}`, fullName: 'Bé A', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } });
    const secondStudent = await prisma.student.create({ data: { schoolId: second.id, studentCode: `B-${uuid()}`, fullName: 'Bé B', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } });
    const firstLink = await prisma.studentParent.create({ data: { schoolId: first.id, studentId: firstStudent.id, parentProfileId: parent.id } });
    await prisma.studentParent.create({ data: { schoolId: second.id, studentId: secondStudent.id, parentProfileId: parent.id } });
    const session = await login(email, 'parent');
    const before = await fetch(`${baseUrl}/api/parent/auth/session`, { headers: { cookie: session.session } });
    expect(before.status).toBe(200);
    expect((await before.json()).data.schools).toEqual([
      { schoolId: first.id, schoolName: first.name, student: { id: firstStudent.id, fullName: 'Bé A' } },
      { schoolId: second.id, schoolName: second.name, student: { id: secondStudent.id, fullName: 'Bé B' } },
    ]);
    await prisma.studentParent.update({ where: { id: firstLink.id }, data: { status: 'REVOKED', revokedAt: new Date() } });
    const after = await fetch(`${baseUrl}/api/parent/auth/session`, { headers: { cookie: session.session } });
    expect(after.status).toBe(200);
    expect((await after.json()).data.schools).toEqual([{ schoolId: second.id, schoolName: second.name, student: { id: secondStudent.id, fullName: 'Bé B' } }]);
  });
  it('omits suspended Schools and denies a final-link Parent context on the next session request', async () => {
    const email = `parent-context-final-${uuid()}@example.com`;
    const active = await prisma.school.create({ data: { name: 'Parent active', slug: `parent-active-${uuid()}`, studentCodePrefix: 'A' } });
    const suspended = await prisma.school.create({ data: { name: 'Parent suspended', slug: `parent-suspended-${uuid()}`, studentCodePrefix: 'S', status: 'SUSPENDED' } });
    schools.push(active.id, suspended.id);
    const parent = await prisma.parentProfile.create({ data: { emailNormalized: email, fullName: 'Phụ huynh Final', phone: '0900000015' } }); parentProfiles.push(parent.id);
    const activeStudent = await prisma.student.create({ data: { schoolId: active.id, studentCode: `A-${uuid()}`, fullName: 'Bé Active', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } });
    const suspendedStudent = await prisma.student.create({ data: { schoolId: suspended.id, studentCode: `S-${uuid()}`, fullName: 'Bé Suspended', dateOfBirth: new Date('2022-01-01T00:00:00.000Z') } });
    const activeLink = await prisma.studentParent.create({ data: { schoolId: active.id, studentId: activeStudent.id, parentProfileId: parent.id } });
    await prisma.studentParent.create({ data: { schoolId: suspended.id, studentId: suspendedStudent.id, parentProfileId: parent.id } });
    const session = await login(email, 'parent');
    const before = await fetch(`${baseUrl}/api/parent/auth/session`, { headers: { cookie: session.session } });
    expect((await before.json()).data.schools).toEqual([{ schoolId: active.id, schoolName: active.name, student: { id: activeStudent.id, fullName: 'Bé Active' } }]);
    await prisma.studentParent.update({ where: { id: activeLink.id }, data: { status: 'REVOKED', revokedAt: new Date() } });
    await expect(fetch(`${baseUrl}/api/parent/auth/session`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 401 });
  });
  it('lists only retained authorized inbox snapshots, keeps Parent reads independent, and protects open with CSRF', async () => {
    const emailA = `inbox-a-${uuid()}@example.com`; const emailB = `inbox-b-${uuid()}@example.com`; const school = await prisma.school.create({ data: { name: 'Inbox release', slug: `inbox-${uuid()}`, studentCodePrefix: 'I' } }); schools.push(school.id);
    const parentA = await prisma.parentProfile.create({ data: { emailNormalized: emailA, fullName: 'Phụ huynh A', phone: '0900000030' } }); const parentB = await prisma.parentProfile.create({ data: { emailNormalized: emailB, fullName: 'Phụ huynh B', phone: '0900000031' } }); parentProfiles.push(parentA.id, parentB.id);
    const student = await prisma.student.create({ data: { schoolId: school.id, studentCode: `I-${uuid()}`, fullName: 'Tên hiện tại không được lộ', dateOfBirth: new Date('2022-01-01') } }); const sibling = await prisma.student.create({ data: { schoolId: school.id, studentCode: `I-${uuid()}`, fullName: 'Sibling', dateOfBirth: new Date('2022-01-01') } });
    await prisma.studentParent.createMany({ data: [{ schoolId: school.id, studentId: student.id, parentProfileId: parentA.id }, { schoolId: school.id, studentId: student.id, parentProfileId: parentB.id }] }); const identity = await prisma.userIdentity.create({ data: { emailNormalized: `inbox-actor-${uuid()}@example.com` } }); await prisma.schoolMembership.create({ data: { schoolId: school.id, userIdentityId: identity.id } }); const year = await prisma.schoolYear.create({ data: { schoolId: school.id, name: 'Inbox 2026', startsOn: new Date('2026-01-01'), endsOn: new Date('2027-01-01') } }); await prisma.studentEnrollment.createMany({ data: [student, sibling].map((item) => ({ schoolId: school.id, studentId: item.id, schoolYearId: year.id, lifecycle: 'ENROLLED', effectiveFrom: new Date('2026-01-01'), schoolYearName: year.name, schoolYearStartsOn: year.startsOn, schoolYearEndsOn: year.endsOn })) });
    const source = await prisma.notificationSourceEvent.create({ data: { schoolId: school.id, sourceType: 'ATTENDANCE', sourceRecordId: uuid(), studentId: student.id, attendanceOn: new Date(), state: 'PRESENT', studentDisplayNameSnapshot: 'Bé An lúc điểm danh', payload: { private: true } } }); await prisma.notificationSourceEvent.create({ data: { schoolId: school.id, sourceType: 'ATTENDANCE', sourceRecordId: uuid(), studentId: sibling.id, attendanceOn: new Date(), state: 'PRESENT', studentDisplayNameSnapshot: 'Sibling', payload: {} } });
    const sessionA = await login(emailA, 'parent'); const sessionB = await login(emailB, 'parent'); const readHeaders = { cookie: sessionA.session }; const list = await fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox`, { headers: readHeaders }); expect(list.status).toBe(200); expect(list.headers.get('cache-control')).toBe('private, no-store'); const listed = await list.json() as { data: Array<Record<string, unknown>>; meta: { unreadCount: number } }; expect(listed.meta.unreadCount).toBe(1); expect(listed.data).toHaveLength(1); expect(listed.data[0]).toEqual(expect.objectContaining({ id: source.id, studentId: student.id, studentDisplayName: 'Bé An lúc điểm danh', text: 'Đã ghi nhận có mặt', unread: true })); expect(Object.keys(listed.data[0]!)).toEqual(['id', 'schoolId', 'studentId', 'studentDisplayName', 'eventType', 'text', 'date', 'time', 'unread', 'readAt']);
    const route = `${baseUrl}/api/parent/schools/${school.id}/inbox/${source.id}/open`; await expect(fetch(route, { method: 'POST', headers: { cookie: sessionA.session } })).resolves.toMatchObject({ status: 401 }); expect(await prisma.parentInboxEventRead.count()).toBe(0); const opened = await fetch(route, { method: 'POST', headers: { cookie: `${sessionA.session}; parent_csrf=${sessionA.csrf}`, origin: 'http://localhost:5174', 'x-csrf-token': sessionA.csrf } }); expect(opened.status).toBe(201); expect(await opened.json()).toEqual({ data: { studentId: student.id, date: new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()) } }); expect(await prisma.parentInboxEventRead.count({ where: { schoolId: school.id, parentProfileId: parentA.id } })).toBe(1); const other = await fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox`, { headers: { cookie: sessionB.session } }); expect((await other.json()).meta.unreadCount).toBe(1);
    const hcm = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); const retainedOn = new Date(`${hcm}T00:00:00.000Z`); retainedOn.setUTCDate(retainedOn.getUTCDate() - 29); const expiredOn = new Date(`${hcm}T00:00:00.000Z`); expiredOn.setUTCDate(expiredOn.getUTCDate() - 30); const retained = await prisma.notificationSourceEvent.create({ data: { schoolId: school.id, sourceType: 'HANDOVER', sourceRecordId: uuid(), studentId: student.id, attendanceOn: retainedOn, pickedUpAt: new Date(), studentDisplayNameSnapshot: 'Ngày 30', payload: {} } }); const expired = await prisma.notificationSourceEvent.create({ data: { schoolId: school.id, sourceType: 'HANDOVER', sourceRecordId: uuid(), studentId: student.id, attendanceOn: expiredOn, pickedUpAt: new Date(), studentDisplayNameSnapshot: 'Ngày 31', payload: {} } }); const bList = await fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox`, { headers: { cookie: sessionB.session } }); const bItems = (await bList.json()).data as Array<{ id: string }>; expect(bItems.map((item) => item.id)).toContain(retained.id); expect(bItems.map((item) => item.id)).not.toContain(expired.id); const parentHeaders = { cookie: `${sessionB.session}; parent_csrf=${sessionB.csrf}`, origin: 'http://localhost:5174', 'x-csrf-token': sessionB.csrf }; await expect(fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox/${retained.id}/open`, { method: 'POST', headers: parentHeaders })).resolves.toMatchObject({ status: 201 }); await expect(fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox/${expired.id}/open`, { method: 'POST', headers: parentHeaders })).resolves.toMatchObject({ status: 404 });
    const enrollment = await prisma.studentEnrollment.findFirstOrThrow({ where: { schoolId: school.id, studentId: student.id } }); const expiredEnrollmentOn = new Date(`${hcm}T00:00:00.000Z`); expiredEnrollmentOn.setUTCDate(expiredEnrollmentOn.getUTCDate() - 31); await prisma.studentEnrollment.update({ where: { id: enrollment.id }, data: { lifecycle: 'WITHDRAWN', endedOn: expiredEnrollmentOn } }); const operationalExpired = await prisma.notificationSourceEvent.create({ data: { schoolId: school.id, sourceType: 'HANDOVER', sourceRecordId: uuid(), studentId: student.id, attendanceOn: new Date(`${hcm}T00:00:00.000Z`), pickedUpAt: new Date(), studentDisplayNameSnapshot: 'Hết retention vận hành', payload: {} } }); const operationalList = await fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox`, { headers: { cookie: sessionB.session } }); expect(((await operationalList.json()).data as Array<{ id: string }>).map((item) => item.id)).not.toContain(operationalExpired.id); await expect(fetch(`${baseUrl}/api/parent/schools/${school.id}/inbox/${operationalExpired.id}/open`, { method: 'POST', headers: parentHeaders })).resolves.toMatchObject({ status: 404 }); await expect(fetch(`${baseUrl}/api/parent/schools/${uuid()}/inbox`, { headers: { cookie: sessionB.session } })).resolves.toMatchObject({ status: 404 });
    await prisma.studentParent.updateMany({ where: { schoolId: school.id, studentId: student.id, parentProfileId: parentA.id }, data: { status: 'REVOKED', revokedAt: new Date() } }); await expect(fetch(route, { method: 'POST', headers: { cookie: `${sessionA.session}; parent_csrf=${sessionA.csrf}`, origin: 'http://localhost:5174', 'x-csrf-token': sessionA.csrf } })).resolves.toMatchObject({ status: 404 });
  });
});
