import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { createApi } from '../main.js';
import { PrismaService } from '../modules/identity/prisma.service.js';

const prisma = new PrismaService();
const schools: string[] = [];
let app: Awaited<ReturnType<typeof createApi>>;
let baseUrl = '';
const uuid = () => crypto.randomUUID();

function cookie(headers: Headers, name: string) { return headers.getSetCookie().find((value) => value.startsWith(`${name}=`))?.split(';')[0]; }
async function login(email: string) { const start = await fetch(`${baseUrl}/api/app/auth/google/start`, { redirect: 'manual' }); const url = new URL(start.headers.get('location')!); const state = url.searchParams.get('state')!; const nonce = url.searchParams.get('nonce')!; const correlation = cookie(start.headers, 'app_oauth_correlation')!; const token = Buffer.from(JSON.stringify({ iss: 'https://accounts.google.com', sub: `release-${uuid()}`, email, email_verified: true, aud: url.searchParams.get('client_id')!, nonce, exp: Math.ceil(Date.now() / 1000) + 600 })).toString('base64url'); const callback = await fetch(`${baseUrl}/api/app/auth/google/callback?state=${encodeURIComponent(state)}&code=${encodeURIComponent(token)}`, { redirect: 'manual', headers: { cookie: correlation } }); return { session: cookie(callback.headers, 'app_session')!, csrf: cookie(callback.headers, 'app_csrf')!.split('=')[1]! }; }
const headers = (session: { session: string; csrf: string }) => ({ cookie: `${session.session}; app_csrf=${session.csrf}`, origin: 'http://localhost:5173', 'x-csrf-token': session.csrf, 'idempotency-key': uuid(), 'x-operation-id': uuid(), 'content-type': 'application/json' });
async function actor(schoolId: string, email: string) { const identity = await prisma.userIdentity.findUniqueOrThrow({ where: { emailNormalized: email } }); const membership = await prisma.schoolMembership.create({ data: { schoolId, userIdentityId: identity.id } }); const fallbackIdentity = await prisma.userIdentity.create({ data: { emailNormalized: `release-fallback-${uuid()}@example.com` } }); const fallbackMembership = await prisma.schoolMembership.create({ data: { schoolId, userIdentityId: fallbackIdentity.id } }); const position = await prisma.schoolPosition.create({ data: { schoolId, code: `RELEASE_${uuid().replaceAll('-', '').slice(0, 12)}`, name: `Release ${uuid()}` } }); const fallbackPosition = await prisma.schoolPosition.create({ data: { schoolId, code: `RELEASE_FALLBACK_${uuid().replaceAll('-', '').slice(0, 12)}`, name: `Release fallback ${uuid()}` } }); await prisma.positionCapabilityGrant.createMany({ data: ['SCHOOL_CONTEXT_READ', 'ROSTER_MANAGE'].map((capability) => ({ schoolId, positionId: position.id, capability })) }); await prisma.positionCapabilityGrant.create({ data: { schoolId, positionId: fallbackPosition.id, capability: 'ROSTER_MANAGE' } }); await prisma.staffProfile.create({ data: { schoolId, fullName: 'Release actor', email, phone: '0900000000', dateOfBirth: new Date('1990-01-01T00:00:00.000Z'), gender: 'Khác', address: 'Test', primaryPositionId: position.id, schoolMembershipId: membership.id, boundAt: new Date(), boundByMembershipId: membership.id } }); await prisma.staffProfile.create({ data: { schoolId, fullName: 'Release fallback manager', email: fallbackIdentity.emailNormalized, phone: '0900000001', dateOfBirth: new Date('1990-01-01T00:00:00.000Z'), gender: 'Khác', address: 'Test', primaryPositionId: fallbackPosition.id, schoolMembershipId: fallbackMembership.id, boundAt: new Date(), boundByMembershipId: fallbackMembership.id } }); return { membership, position }; }

describe.skipIf(!process.env.TARGET_INTEGRATION_DATABASE_URL)('SchoolPosition HTTP release gate', () => {
  beforeAll(async () => { app = await createApi(); await app.listen(0, '127.0.0.1'); baseUrl = `http://127.0.0.1:${(app.getHttpServer().address() as { port: number }).port}`; });
  afterEach(async () => { await prisma.auditRecord.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.operation.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.staffProfile.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.positionCapabilityGrant.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.schoolPosition.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.schoolMembership.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.school.deleteMany({ where: { id: { in: schools.splice(0) } } }); });
  afterAll(async () => { await app.close(); await prisma.$disconnect(); });

  it('authorizes a Position capability, then denies the next request after it is revoked', async () => {
    const email = `release-${uuid()}@example.com`; const session = await login(email); const school = await prisma.school.create({ data: { name: 'Release', slug: `release-${uuid()}`, studentCodePrefix: 'R' } }); schools.push(school.id); const { position } = await actor(school.id, email);
    await expect(fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 200 });
    const revoke = await fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions/${position.id}/grants/ROSTER_MANAGE/revoke`, { method: 'POST', headers: headers(session), body: JSON.stringify({ reason: 'Thu hồi kiểm thử' }) });
    expect(revoke.status).toBe(201);
    await expect(fetch(`${baseUrl}/api/app/schools/${school.id}/roster/positions`, { headers: { cookie: session.session } })).resolves.toMatchObject({ status: 403 });
  });
});
