import { afterAll, afterEach, describe, expect, it } from 'vitest';
import { AuthorizationService } from '../modules/authorization/authorization.service.js';
import { PrismaService } from '../modules/identity/prisma.service.js';
import { RosterService } from '../modules/roster/roster.service.js';

const prisma = new PrismaService(); const authorization = new AuthorizationService(prisma); const roster = new RosterService(prisma, authorization); const schools: string[] = [];
const uuid = () => crypto.randomUUID();
async function school() { const item = await prisma.school.create({ data: { name: 'Roster', slug: `roster-${uuid()}` } }); schools.push(item.id); return item; }
async function actor(schoolId: string, role: 'SCHOOL_ADMIN' | 'FINANCE_MANAGER' = 'SCHOOL_ADMIN') { const identity = await prisma.userIdentity.create({ data: { emailNormalized: `${uuid()}@example.com` } }); const membership = await prisma.schoolMembership.create({ data: { schoolId, userIdentityId: identity.id } }); await prisma.schoolRoleGrant.create({ data: { schoolId, membershipId: membership.id, role } }); return identity; }
afterEach(async () => { await prisma.auditRecord.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.operation.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.class.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.schoolYear.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.schoolRoleGrant.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.schoolMembership.deleteMany({ where: { schoolId: { in: schools } } }); await prisma.school.deleteMany({ where: { id: { in: schools.splice(0) } } }); }); afterAll(() => prisma.$disconnect());

describe.skipIf(!process.env.TARGET_INTEGRATION_DATABASE_URL)('roster PostgreSQL invariants', () => {
  it('enforces half-open SchoolYear intervals per School and permits an identical interval elsewhere', async () => {
    const a = await school(); const b = await school(); const user = await actor(a.id); const userB = await actor(b.id); const first = await roster.createSchoolYear(user.id, a.id, uuid(), uuid(), { name: 'A', startsOn: '2026-01-01', endsOn: '2026-06-01' }); await roster.createSchoolYear(user.id, a.id, uuid(), uuid(), { name: 'Adjacent', startsOn: '2026-06-01', endsOn: '2027-01-01' }); await roster.createSchoolYear(userB.id, b.id, uuid(), uuid(), { name: 'B', startsOn: '2026-01-01', endsOn: '2026-06-01' }); await expect(roster.createSchoolYear(user.id, a.id, uuid(), uuid(), { name: 'Overlap', startsOn: '2026-05-01', endsOn: '2026-07-01' })).rejects.toMatchObject({ status: 409 }); expect(first.status).toBe('COMPLETED');
  });
  it('validates before Operation creation, protects tenant graph, and replays an identical Class command', async () => {
    const a = await school(); const b = await school(); const admin = await actor(a.id); const other = await actor(b.id); const before = await prisma.operation.count({ where: { schoolId: a.id } }); await expect(roster.createSchoolYear(admin.id, a.id, uuid(), uuid(), { name: '', startsOn: '2026-01-01', endsOn: '2026-01-01' })).rejects.toMatchObject({ status: 400 }); await expect(prisma.operation.count({ where: { schoolId: a.id } })).resolves.toBe(before); const yearA = await roster.createSchoolYear(admin.id, a.id, uuid(), uuid(), { name: 'A', startsOn: '2026-01-01', endsOn: '2027-01-01' }); const yearB = await roster.createSchoolYear(other.id, b.id, uuid(), uuid(), { name: 'B', startsOn: '2026-01-01', endsOn: '2027-01-01' }); const key = uuid(); const created = await roster.createClass(admin.id, a.id, (yearA.outcome as any).id, key, uuid(), { name: 'Mầm' }); const replay = await roster.createClass(admin.id, a.id, (yearA.outcome as any).id, key, uuid(), { name: 'Mầm' }); expect(replay.id).toBe(created.id); await expect(roster.createClass(admin.id, a.id, (yearB.outcome as any).id, uuid(), uuid(), { name: 'Foreign' })).rejects.toMatchObject({ status: 404 }); await expect(prisma.auditRecord.count({ where: { schoolId: a.id, action: 'CLASS_CREATED' } })).resolves.toBe(1);
  });
  it('persists JSON-safe Class outcomes and replays create and rename commands', async () => {
    const current = await school(); const admin = await actor(current.id); const year = await roster.createSchoolYear(admin.id, current.id, uuid(), uuid(), { name: 'A', startsOn: '2026-01-01', endsOn: '2027-01-01' }); const createKey = uuid(); const created = await roster.createClass(admin.id, current.id, (year.outcome as any).id, createKey, uuid(), { name: 'Mầm' }); const createReplay = await roster.createClass(admin.id, current.id, (year.outcome as any).id, createKey, uuid(), { name: 'Mầm' }); const classOutcome = created.outcome as any; expect(created.status).toBe('COMPLETED'); expect(createReplay).toEqual(created); expect(classOutcome).toMatchObject({ name: 'Mầm', status: 'ACTIVE' }); expect(typeof classOutcome.createdAt).toBe('string'); expect(typeof classOutcome.updatedAt).toBe('string'); expect(() => JSON.stringify(classOutcome)).not.toThrow(); const renameKey = uuid(); const renamed = await roster.renameClass(admin.id, current.id, classOutcome.id, renameKey, uuid(), { name: 'Chồi' }); const renameReplay = await roster.renameClass(admin.id, current.id, classOutcome.id, renameKey, uuid(), { name: 'Chồi' }); expect(renamed.status).toBe('COMPLETED'); expect(renameReplay).toEqual(renamed); expect(renamed.outcome).toMatchObject({ id: classOutcome.id, name: 'Chồi' }); const operation = await prisma.operation.findUniqueOrThrow({ where: { id: renamed.id } }); expect(operation.outcome).toMatchObject({ name: 'Chồi', createdAt: expect.any(String), updatedAt: expect.any(String) });
  });
  it('denies roster reads before disclosing data to a non-admin or suspended School', async () => {
    const current = await school(); const admin = await actor(current.id); const finance = await actor(current.id, 'FINANCE_MANAGER'); await roster.createSchoolYear(admin.id, current.id, uuid(), uuid(), { name: 'A', startsOn: '2026-01-01', endsOn: '2027-01-01' }); await expect(roster.schoolYears(finance.id, current.id)).rejects.toMatchObject({ status: 403 }); await prisma.school.update({ where: { id: current.id }, data: { status: 'SUSPENDED' } }); await expect(roster.schoolYears(admin.id, current.id)).rejects.toMatchObject({ status: 404 });
  });
});
