import { BadRequestException, Body, Controller, Get, Headers, Param, Post, Query, Req, Res } from '@nestjs/common';
import { audienceConfig } from '../auth/auth.config.js';
import { AuthService } from '../auth/auth.service.js';
import { assertCookieMutation } from '../common/mutation-protection.js';
import { AttendanceService } from './attendance.service.js';

type RequestLike = { headers: Record<string, string | undefined> };
type ResponseLike = { setHeader(name: string, value: string): void; send(value: Uint8Array): void };
const cookie = (request: RequestLike, name: string) => request.headers.cookie?.split(';').map((item) => item.trim().split('=')).find(([key]) => key === name)?.[1];

@Controller('api')
export class AttendanceController {
  constructor(private readonly auth: AuthService, private readonly attendance: AttendanceService) {}
  private identity(request: RequestLike, audience: 'app' | 'teacher' | 'parent') { return this.auth.session(audience, cookie(request, audienceConfig(audience).cookieName)).userIdentityId; }
  private mutation(request: RequestLike, audience: 'app' | 'teacher' | 'parent', key?: string) { const config = audienceConfig(audience); return assertCookieMutation(request, config.origin, config.csrfCookieName, key); }
  @Post('parent/schools/:schoolId/leave-requests') async create(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.attendance.create(this.identity(request, 'parent'), schoolId, this.mutation(request, 'parent', key), operationId ?? '', body) }; }
  @Get('parent/schools/:schoolId/leave-requests') async parentList(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('studentId') studentId?: string) { return { data: await this.attendance.parentList(this.identity(request, 'parent'), schoolId, studentId), meta: {} }; }
  @Get('parent/schools/:schoolId/leave-requests/:leaveRequestId') async parentRead(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('leaveRequestId') leaveRequestId: string) { return { data: await this.attendance.parentRead(this.identity(request, 'parent'), schoolId, leaveRequestId) }; }
  @Get('parent/schools/:schoolId/operations/:operationId') async parentOperation(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('operationId') operationId: string) { return { data: await this.attendance.parentOperation(this.identity(request, 'parent'), schoolId, operationId) }; }
  @Get('teacher/schools/:schoolId/leave-requests') async teacherList(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('classId') classId?: string) { return { data: await this.attendance.teacherList(this.identity(request, 'teacher'), schoolId, classId), meta: {} }; }
  @Get('teacher/schools/:schoolId/attendance-roster') async teacherRoster(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('classId') classId: string, @Query('attendanceOn') attendanceOn: string) { return { data: await this.attendance.teacherRoster(this.identity(request, 'teacher'), schoolId, classId, attendanceOn) }; }
  @Post('teacher/schools/:schoolId/attendance') async record(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.attendance.record(this.identity(request, 'teacher'), schoolId, this.mutation(request, 'teacher', key), operationId ?? '', body) }; }
  @Post('teacher/schools/:schoolId/attendance-evidence') async uploadEvidence(@Req() request: RequestLike & { body: unknown }, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Query('classId') classId: string, @Query('attendanceOn') attendanceOn: string) { return { data: await this.attendance.uploadEvidence(this.identity(request, 'teacher'), schoolId, this.mutation(request, 'teacher', key), operationId ?? '', classId, attendanceOn, request.headers['content-type']?.split(';')[0], request.body) }; }
  @Get('teacher/schools/:schoolId/handover-roster') async handoverRoster(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('handoverOn') handoverOn: string) { return { data: await this.attendance.handoverRoster(this.identity(request, 'teacher'), schoolId, handoverOn) }; }
  @Post('teacher/schools/:schoolId/handovers') async handover(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.attendance.recordHandover(this.identity(request, 'teacher'), schoolId, this.mutation(request, 'teacher', key), operationId ?? '', body) }; }
  @Post('teacher/schools/:schoolId/handover-evidence') async uploadHandoverEvidence(@Req() request: RequestLike & { body: unknown }, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Query('handoverOn') handoverOn: string) { return { data: await this.attendance.uploadHandoverEvidence(this.identity(request, 'teacher'), schoolId, this.mutation(request, 'teacher', key), operationId ?? '', handoverOn, request.headers['content-type']?.split(';')[0], request.body) }; }
  @Get('teacher/schools/:schoolId/handover-evidence/:evidenceId') async handoverEvidence(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('evidenceId') evidenceId: string, @Res() response: ResponseLike) { const media = await this.attendance.readHandoverEvidence(this.identity(request, 'teacher'), schoolId, evidenceId, 'teacher'); response.setHeader('Content-Type', media.contentType); response.setHeader('Cache-Control', 'private, no-store'); response.setHeader('X-Content-Type-Options', 'nosniff'); response.send(media.blob); }
  @Get('teacher/schools/:schoolId/attendance-evidence/:evidenceId') async teacherEvidence(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('evidenceId') evidenceId: string, @Res() response: ResponseLike) { const media = await this.attendance.readAttendanceEvidence(this.identity(request, 'teacher'), schoolId, evidenceId); response.setHeader('Content-Type', media.contentType); response.setHeader('Cache-Control', 'private, no-store'); response.setHeader('X-Content-Type-Options', 'nosniff'); response.send(media.blob); }
  @Get('app/schools/:schoolId/handover-evidence/:evidenceId') async appHandoverEvidence(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('evidenceId') evidenceId: string, @Res() response: ResponseLike) { const media = await this.attendance.readHandoverEvidence(this.identity(request, 'app'), schoolId, evidenceId, 'app'); response.setHeader('Content-Type', media.contentType); response.setHeader('Cache-Control', 'private, no-store'); response.setHeader('X-Content-Type-Options', 'nosniff'); response.send(media.blob); }
  @Get('teacher/schools/:schoolId/operations/:operationId') async teacherOperation(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('operationId') operationId: string) { return { data: await this.attendance.teacherOperation(this.identity(request, 'teacher'), schoolId, operationId) }; }
  @Get('app/schools/:schoolId/leave-requests') async appList(@Req() request: RequestLike, @Param('schoolId') schoolId: string) { return { data: await this.attendance.appList(this.identity(request, 'app'), schoolId), meta: {} }; }
  @Get('app/schools/:schoolId/leave-operations/:operationId') async appOperation(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('operationId') operationId: string) { return { data: await this.attendance.appOperation(this.identity(request, 'app'), schoolId, operationId) }; }
  @Get('app/schools/:schoolId/leave-day-sources') async leaveDaySources(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('limit') rawLimit?: string, @Query('cursor') cursor?: string) { const limit = rawLimit === undefined ? 100 : Number(rawLimit); if (!Number.isInteger(limit) || limit < 1 || limit > 200 || (cursor !== undefined && !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(cursor))) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { ...(!Number.isInteger(limit) || limit < 1 || limit > 200 ? { limit: 'Giới hạn không hợp lệ.' } : {}), ...(cursor !== undefined && !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(cursor) ? { cursor: 'Con trỏ không hợp lệ.' } : {}) } }); const page = await this.attendance.leaveDaySources(this.identity(request, 'app'), schoolId, limit, cursor); return { data: page.data, meta: { limit, nextCursor: page.nextCursor } }; }
  @Post('app/schools/:schoolId/leave-requests/:leaveRequestId/approve') async approve(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('leaveRequestId') leaveRequestId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.attendance.decide(this.identity(request, 'app'), schoolId, leaveRequestId, 'APPROVED', this.mutation(request, 'app', key), operationId ?? '', {}) }; }
  @Post('app/schools/:schoolId/leave-requests/:leaveRequestId/reject') async reject(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('leaveRequestId') leaveRequestId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.attendance.decide(this.identity(request, 'app'), schoolId, leaveRequestId, 'REJECTED', this.mutation(request, 'app', key), operationId ?? '', body) }; }
}
