import { Dialog } from '@base-ui/react/dialog';
import { useEffect, useRef, useState } from 'react';
import { ApiError, ApiTimeoutError } from '../../app/api/client';
import { type BankAccount, type BankAccountFilters, type BankAccountStatus, useBankAccounts, useCreateBankAccount, useSetBankAccountStatus } from './api';

function filtersFromUrl(): BankAccountFilters { const params = new URLSearchParams(window.location.search); const page = Number(params.get('page')); const status = params.get('status'); return { search: params.get('search') ?? '', status: status === 'ACTIVE' || status === 'INACTIVE' ? status : '', page: Number.isInteger(page) && page > 0 ? page : 1 }; }

export function BankAccountsPage(): React.JSX.Element {
  const [filters, setFilters] = useState(filtersFromUrl); const accounts = useBankAccounts(filters); const [creating, setCreating] = useState(false); const [changing, setChanging] = useState<BankAccount | null>(null); const createTrigger = useRef<HTMLElement | null>(null); const statusTrigger = useRef<HTMLElement | null>(null);
  useEffect(() => { const syncFilters = () => setFilters(filtersFromUrl()); window.addEventListener('popstate', syncFilters); return () => window.removeEventListener('popstate', syncFilters); }, []);
  const updateFilters = (next: Partial<BankAccountFilters>) => { const value = { ...filters, ...next, page: next.search !== undefined || next.status !== undefined ? 1 : (next.page ?? filters.page) }; const params = new URLSearchParams(); if (value.search) params.set('search', value.search); if (value.status) params.set('status', value.status); if (value.page > 1) params.set('page', String(value.page)); window.history.replaceState(null, '', `${window.location.pathname}${params.size ? `?${params}` : ''}`); setFilters(value); };
  const openCreate = (event: React.MouseEvent<HTMLButtonElement>) => { createTrigger.current = event.currentTarget; setCreating(true); };
  const closeCreate = () => { setCreating(false); requestAnimationFrame(() => createTrigger.current?.focus()); };
  return <section className="page"><div className="page-heading"><div><h1>Tài khoản nhận tiền</h1><p>Quản lý tài khoản dùng để nhận chuyển khoản.</p></div><button className="primary-action" type="button" onClick={openCreate}>Thêm tài khoản</button></div>
    <div className="table-toolbar"><label>Tìm tài khoản<input value={filters.search} onChange={(event) => updateFilters({ search: event.target.value })} placeholder="Tìm ngân hàng, số tài khoản" /></label><label>Trạng thái<select value={filters.status} onChange={(event) => updateFilters({ status: event.target.value as BankAccountFilters['status'] })}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="INACTIVE">Ngừng dùng</option></select></label></div>
    {accounts.isPending ? <div className="table-card skeleton" aria-live="polite">Đang tải danh sách tài khoản...</div> : accounts.error ? <div className="table-card error-state" role="alert"><p>Không thể tải danh sách tài khoản.</p><button type="button" onClick={() => void accounts.refetch()}>Thử lại</button></div> : <>{accounts.data!.data.length === 0 ? <div className="table-card empty-state"><p>{accounts.data!.meta.total ? 'Trang này không còn tài khoản nào.' : 'Chưa có tài khoản nào phù hợp.'}</p><button className="primary-action" type="button" onClick={openCreate}>Thêm tài khoản</button></div> : <div className="table-card table-scroll"><table aria-label="Danh sách tài khoản nhận tiền"><caption className="sr-only">Danh sách tài khoản nhận tiền</caption><thead><tr><th>Ngân hàng</th><th>Số tài khoản</th><th>Chủ tài khoản</th><th>Trạng thái</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{accounts.data!.data.map((item) => <tr key={item.id}><th scope="row">{item.bankCode}</th><td>{item.accountNumber}</td><td>{item.accountHolderName}</td><td><span className={`status ${item.status === 'ACTIVE' ? 'active' : 'archived'}`}>{item.status === 'ACTIVE' ? 'Đang hoạt động' : 'Ngừng dùng'}</span></td><td className="row-actions"><button type="button" onClick={(event) => { statusTrigger.current = event.currentTarget; setChanging(item); }}>{item.status === 'ACTIVE' ? 'Ngừng dùng' : 'Kích hoạt'}</button></td></tr>)}</tbody></table></div>}{(accounts.data!.data.length > 0 || accounts.data!.meta.total > 0) && <div className="pagination"><span>Trang {accounts.data!.meta.page} / {accounts.data!.meta.pageCount}</span><button type="button" disabled={filters.page <= 1} onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button><button type="button" disabled={filters.page >= accounts.data!.meta.pageCount} onClick={() => updateFilters({ page: filters.page + 1 })}>Sau</button></div>}</>}
    {creating && <BankAccountForm onClose={closeCreate} onCreated={() => updateFilters({ page: 1 })} />}{changing && <StatusDialog item={changing} trigger={statusTrigger} onClose={() => setChanging(null)} />}</section>;
}

function BankAccountForm({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }): React.JSX.Element {
  const create = useCreateBankAccount(); const [input, setInput] = useState({ bankCode: '', accountNumber: '', accountHolderName: '' }); const [errors, setErrors] = useState<Record<string, string>>({});
  const validate = (key: keyof typeof input) => { const value = input[key].trim(); const maximum = key === 'accountHolderName' ? 150 : 50; const error = !value ? 'Trường này không được để trống.' : value.length > maximum ? `Trường này không được dài quá ${maximum} ký tự.` : ''; setInput((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: error })); return !error; };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const keys: (keyof typeof input)[] = ['bankCode', 'accountNumber', 'accountHolderName']; const valid = keys.map(validate).every(Boolean); if (!valid) return; create.mutate(input, { onSuccess: () => { onCreated(); onClose(); }, onError: (cause) => { if (cause instanceof ApiError && cause.fieldErrors) { const next: Record<string, string> = {}; const unmatched = cause.fieldErrors.filter((error) => { const key = keys.find((field) => error.includes(field)); if (key) next[key] = error; return !key; }); setErrors(unmatched.length ? { ...next, form: cause.message } : next); return; } setErrors({ form: cause instanceof ApiTimeoutError ? cause.message : cause instanceof ApiError ? cause.message : 'Không thể lưu tài khoản.' }); } }); };
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !create.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>Thêm tài khoản nhận tiền</Dialog.Title><form noValidate onSubmit={submit}>{(['bankCode', 'accountNumber', 'accountHolderName'] as const).map((key) => { const label = key === 'bankCode' ? 'Mã ngân hàng VietQR' : key === 'accountNumber' ? 'Số tài khoản' : 'Tên chủ tài khoản'; const id = `bank-account-${key}-error`; return <div key={key}><label>{label}<input value={input[key]} maxLength={key === 'accountHolderName' ? 150 : 50} disabled={create.isPending} autoFocus={key === 'bankCode'} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key] ? id : undefined} onChange={(event) => setInput((current) => ({ ...current, [key]: event.target.value }))} onBlur={() => validate(key)} /></label>{errors[key] && <p id={id} role="alert">{errors[key]}</p>}</div>; })}{errors.form && <p role="alert">{errors.form}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={create.isPending}>Hủy</button>} /><button className="primary-action" type="submit" disabled={create.isPending}>{create.isPending ? 'Đang lưu...' : 'Lưu tài khoản'}</button></div></form></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}

function StatusDialog({ item, trigger, onClose }: { item: BankAccount; trigger: React.RefObject<HTMLElement | null>; onClose: () => void }): React.JSX.Element {
  const change = useSetBankAccountStatus(); const [error, setError] = useState(''); const next: BankAccountStatus = item.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE';
  useEffect(() => () => trigger.current?.focus(), [trigger]);
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !change.isPending) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>{next === 'INACTIVE' ? `Ngừng dùng ${item.accountNumber}?` : `Kích hoạt ${item.accountNumber}?`}</Dialog.Title><p>{next === 'INACTIVE' ? 'Tài khoản này sẽ không thể được chọn cho hóa đơn nháp mới.' : 'Tài khoản này sẽ có thể được chọn cho hóa đơn nháp mới.'}</p>{error && <p role="alert">{error}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={change.isPending}>Hủy</button>} /><button className={next === 'INACTIVE' ? 'danger-action' : 'primary-action'} type="button" disabled={change.isPending} onClick={() => change.mutate({ id: item.id, status: next }, { onSuccess: onClose, onError: (cause) => setError(cause instanceof ApiError ? cause.message : 'Không thể cập nhật tài khoản.') })}>{change.isPending ? 'Đang cập nhật...' : next === 'INACTIVE' ? 'Xác nhận ngừng dùng' : 'Xác nhận kích hoạt'}</button></div></Dialog.Popup></Dialog.Portal></Dialog.Root>;
}
