import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ApiError, getJson, requestJson } from '../../app/api/client';

export type InvoiceStatus = 'DRAFT' | 'PENDING' | 'COMPLETED';
export interface Invoice { id: string; billingMonth: string; student: { name: string; nickname: string | null }; schoolClass: { id: string; name: string }; status: InvoiceStatus; total: number; createdAt: string; updatedAt: string; }
export interface InvoiceDetail extends Invoice { items: { id: string; description: string; feeGroup: string | null; amount: number; position: number }[]; payment: { method: 'CASH' | 'TRANSFER' | null; bankAccount: { id?: string; bankCode: string; accountNumber: string; accountHolderName: string } | null }; qr: { transferContent: string; url: string } | null; createdBy: { id: string; displayName: string }; completedBy: { id: string; displayName: string } | null; completedAt: string | null; }
export interface UpdateInvoiceInput { items: { description: string; feeGroup?: string; amount: number }[]; paymentMethod: 'CASH' | 'TRANSFER'; bankAccountId?: string; }
export interface InvoiceList { data: Invoice[]; meta: { page: number; pageSize: number; total: number; pageCount: number }; }
export interface InvoiceFilters { billingMonth: string; search: string; status: '' | InvoiceStatus; classId: string; page: number; }
export interface BatchInput { billingMonth: string; allActiveClasses: boolean; classIds?: string[]; }
export interface BatchResult { operationId: string; createdCount: number; skipped: BatchSkips; }
export interface BatchPreview { eligibleCount: number; skipped: BatchSkips; }
export interface BatchSkips { inactiveStudent: number; missingClass: number; archivedClass: number; existingInvoice: number; }
export interface PendingBatchOperation { operationId: string; state: 'PENDING'; }

function invalid(): never { throw new ApiError(502, 'INVALID_RESPONSE', 'Phản hồi API không hợp lệ.'); }
const billingMonthPattern = /^(?!0000)\d{4}-(0[1-9]|1[0-2])$/;
export function parseInvoice(value: unknown): Invoice {
  if (!value || typeof value !== 'object') return invalid();
  const item = value as Record<string, unknown>; const student = item.student as Record<string, unknown>; const schoolClass = item.schoolClass as Record<string, unknown>;
  if (typeof item.id !== 'string' || typeof item.billingMonth !== 'string' || !billingMonthPattern.test(item.billingMonth) || !student || typeof student.name !== 'string' || (student.nickname !== null && typeof student.nickname !== 'string') || !schoolClass || typeof schoolClass.id !== 'string' || typeof schoolClass.name !== 'string' || !['DRAFT', 'PENDING', 'COMPLETED'].includes(item.status as string) || !Number.isSafeInteger(item.total) || typeof item.createdAt !== 'string' || Number.isNaN(Date.parse(item.createdAt)) || typeof item.updatedAt !== 'string' || Number.isNaN(Date.parse(item.updatedAt))) return invalid();
  return { id: item.id, billingMonth: item.billingMonth as string, student: { name: student.name, nickname: student.nickname as string | null }, schoolClass: { id: schoolClass.id, name: schoolClass.name }, status: item.status as InvoiceStatus, total: item.total as number, createdAt: item.createdAt, updatedAt: item.updatedAt };
}
function parseList(value: unknown): InvoiceList {
  if (!value || typeof value !== 'object') return invalid();
  const response = value as { data?: unknown; meta?: unknown }; const meta = response.meta as Record<string, unknown>;
  if (!Array.isArray(response.data) || !meta || !['page', 'pageSize', 'total', 'pageCount'].every((key) => Number.isSafeInteger(meta[key])) || (meta.page as number) < 1 || (meta.pageSize as number) < 1 || (meta.total as number) < 0 || (meta.pageCount as number) !== Math.max(1, Math.ceil((meta.total as number) / (meta.pageSize as number)))) return invalid();
  return { data: response.data.map(parseInvoice), meta: meta as InvoiceList['meta'] };
}
export function parseInvoiceDetail(value: unknown): InvoiceDetail {
  if (!value || typeof value !== 'object' || !('data' in value)) return invalid();
  const data = value.data as Record<string, unknown>; const base = parseInvoice(data); const payment = data.payment as Record<string, unknown>; const qr = data.qr as Record<string, unknown> | null; const createdBy = data.createdBy as Record<string, unknown>; const completedBy = data.completedBy as Record<string, unknown> | null;
  if (!Array.isArray(data.items) || !payment || !createdBy || typeof createdBy.id !== 'string' || typeof createdBy.displayName !== 'string' || ![null, 'CASH', 'TRANSFER'].includes(payment.method as null | string) || (payment.bankAccount !== null && typeof payment.bankAccount !== 'object')) return invalid();
  const bankAccount = payment.bankAccount as Record<string, unknown> | null;
  if (bankAccount && (!['bankCode', 'accountNumber', 'accountHolderName'].every((key) => typeof bankAccount[key] === 'string') || (bankAccount.id !== undefined && typeof bankAccount.id !== 'string'))) return invalid();
  if ((payment.method === 'TRANSFER') !== Boolean(bankAccount) || (payment.method === 'CASH' && bankAccount)) return invalid();
  if ((base.status === 'PENDING' || base.status === 'COMPLETED') && payment.method === null) return invalid();
  if (!Object.hasOwn(data, 'completedBy') || !Object.hasOwn(data, 'completedAt') || (base.status === 'COMPLETED' && (!completedBy || typeof completedBy.id !== 'string' || typeof completedBy.displayName !== 'string' || typeof data.completedAt !== 'string' || Number.isNaN(Date.parse(data.completedAt)))) || (base.status !== 'COMPLETED' && (completedBy !== null || data.completedAt !== null))) return invalid();
  if ((base.status === 'DRAFT' && qr !== null) || (qr !== null && (!qr || typeof qr.transferContent !== 'string' || typeof qr.url !== 'string' || payment.method !== 'TRANSFER')) || ((base.status === 'PENDING' || base.status === 'COMPLETED') && payment.method === 'TRANSFER' && qr === null)) return invalid();
  const items = data.items.map((value, position) => { const item = value as Record<string, unknown>; if (!item || typeof item.id !== 'string' || typeof item.description !== 'string' || (item.feeGroup !== null && typeof item.feeGroup !== 'string') || !Number.isSafeInteger(item.amount) || item.position !== position) return invalid(); return { id: item.id, description: item.description, feeGroup: item.feeGroup as string | null, amount: item.amount as number, position }; });
  return { ...base, items, payment: { method: payment.method as InvoiceDetail['payment']['method'], bankAccount: bankAccount as InvoiceDetail['payment']['bankAccount'] }, qr: qr as InvoiceDetail['qr'], createdBy: { id: createdBy.id, displayName: createdBy.displayName }, completedBy: completedBy as InvoiceDetail['completedBy'], completedAt: data.completedAt as string | null };
}
function parseSkips(value: unknown): BatchSkips { if (!value || typeof value !== 'object') return invalid(); const skips = value as Record<string, unknown>; if (!['inactiveStudent', 'missingClass', 'archivedClass', 'existingInvoice'].every((key) => Number.isSafeInteger(skips[key]) && (skips[key] as number) >= 0)) return invalid(); return { inactiveStudent: skips.inactiveStudent as number, missingClass: skips.missingClass as number, archivedClass: skips.archivedClass as number, existingInvoice: skips.existingInvoice as number }; }
function parsePreview(value: unknown): BatchPreview { if (!value || typeof value !== 'object' || !('data' in value)) return invalid(); const data = value.data as Record<string, unknown>; if (!Number.isSafeInteger(data.eligibleCount) || (data.eligibleCount as number) < 0) return invalid(); return { eligibleCount: data.eligibleCount as number, skipped: parseSkips(data.skipped) }; }
export function parseBatchResult(value: unknown): BatchResult { if (!value || typeof value !== 'object' || !('data' in value)) return invalid(); const data = value.data as Record<string, unknown>; if (typeof data.operationId !== 'string' || !Number.isSafeInteger(data.createdCount) || (data.createdCount as number) < 0) return invalid(); return { operationId: data.operationId, createdCount: data.createdCount as number, skipped: parseSkips(data.skipped) }; }
function queryString(filters: InvoiceFilters): string { const params = new URLSearchParams({ billingMonth: filters.billingMonth, page: String(filters.page) }); if (filters.search) params.set('search', filters.search); if (filters.status) params.set('status', filters.status); if (filters.classId) params.set('classId', filters.classId); return params.toString(); }

export function useInvoices(filters: InvoiceFilters, enabled = true) { return useQuery({ queryKey: ['invoices', filters], enabled, queryFn: () => getJson<unknown>(`/invoices?${queryString(filters)}`).then(parseList) }); }
export function useInvoice(id: string) { return useQuery({ queryKey: ['invoices', id], enabled: Boolean(id), queryFn: () => getJson<unknown>(`/invoices/${id}`).then(parseInvoiceDetail) }); }
export function useUpdateInvoice() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: UpdateInvoiceInput }) => requestJson<unknown>(`/invoices/${id}`, { method: 'PATCH', body: JSON.stringify(input) }).then(parseInvoiceDetail), onSuccess: (invoice) => { client.setQueryData(['invoices', invoice.id], invoice); client.invalidateQueries({ queryKey: ['invoices'] }); } }); }
export function useInvoiceLifecycle() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, target }: { id: string; target: 'pending' | 'draft' }) => requestJson<unknown>(`/invoices/${id}/${target}`, { method: 'POST' }).then(parseInvoiceDetail), onSuccess: (invoice) => { client.setQueryData(['invoices', invoice.id], invoice); client.invalidateQueries({ queryKey: ['invoices'] }); } }); }
export function useBatchPreview() { return useMutation({ mutationFn: (input: BatchInput) => requestJson<unknown>('/invoices/batch-preview', { method: 'POST', body: JSON.stringify(input) }).then(parsePreview) }); }
export function createInvoiceBatch(input: BatchInput, operationId: string) { return requestJson<unknown>('/invoices/batch', { method: 'POST', headers: { 'Idempotency-Key': operationId }, body: JSON.stringify(input) }).then((value) => { const result = parseBatchResult(value); return result.operationId === operationId ? result : invalid(); }); }
function parseBatchOperation(value: unknown): BatchResult | PendingBatchOperation { if (!value || typeof value !== 'object' || !('data' in value)) return invalid(); const data = value.data as Record<string, unknown>; if (data.state === 'PENDING' && typeof data.operationId === 'string') return { operationId: data.operationId, state: 'PENDING' }; return parseBatchResult(value); }
export function getInvoiceBatchOperation(operationId: string) { return getJson<unknown>(`/operations/${operationId}`).then((value) => { const result = parseBatchOperation(value); return result.operationId === operationId ? result : invalid(); }); }
function parseCompletionOperation(value: unknown): InvoiceDetail | PendingBatchOperation { if (!value || typeof value !== 'object' || !('data' in value)) return invalid(); const data = value.data as Record<string, unknown>; if (data.state === 'PENDING' && typeof data.operationId === 'string') return { operationId: data.operationId, state: 'PENDING' }; return parseInvoiceDetail(value); }
export function completeInvoice(id: string, operationId: string) { return requestJson<unknown>(`/invoices/${id}/complete`, { method: 'POST', headers: { 'Idempotency-Key': operationId } }).then((value) => { const result = parseInvoiceDetail(value); return result.id === id ? result : invalid(); }); }
export function getInvoiceCompletionOperation(operationId: string, invoiceId: string) { return getJson<unknown>(`/operations/${operationId}`).then((value) => { const result = parseCompletionOperation(value); return 'state' in result ? (result.operationId === operationId ? result : invalid()) : (result.id === invoiceId ? result : invalid()); }); }
