import { useEffect } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useClassesForInvoicePicker } from '../classes/api';
import { type InvoiceFilters, type InvoiceStatus, useInvoices } from './api';

function currentMonth(): string { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; }
function formatMonth(month: string): string { const [year, value] = month.split('-'); return `${value}/${year}`; }
function formatVnd(amount: number): string { return `${new Intl.NumberFormat('vi-VN').format(amount)} đ`; }
function statusLabel(status: InvoiceStatus): string { return status === 'DRAFT' ? 'Nháp' : status === 'PENDING' ? 'Chờ xác nhận' : 'Đã hoàn tất'; }
const monthPattern = /^(?!0000)\d{4}-(0[1-9]|1[0-2])$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function filtersFromUrl(params: URLSearchParams): InvoiceFilters { const page = Number(params.get('page')); const status = params.get('status'); const month = params.get('month'); const classId = params.get('classId'); return { billingMonth: month && monthPattern.test(month) ? month : currentMonth(), search: params.get('search') ?? '', status: status === 'DRAFT' || status === 'PENDING' || status === 'COMPLETED' ? status : '', classId: classId && uuidPattern.test(classId) ? classId : '', page: Number.isInteger(page) && page > 0 ? page : 1 }; }

export function InvoicesPage(): React.JSX.Element {
  const [params, setParams] = useSearchParams(); const filters = filtersFromUrl(params); const hasValidMonth = monthPattern.test(params.get('month') ?? ''); const invoices = useInvoices(filters, hasValidMonth); const classes = useClassesForInvoicePicker();
  useEffect(() => { if (!hasValidMonth) { const normalized = new URLSearchParams(params); normalized.set('month', filters.billingMonth); normalized.delete('page'); setParams(normalized, { replace: true }); } }, [filters.billingMonth, hasValidMonth, params, setParams]);
  const updateFilters = (next: Partial<InvoiceFilters>) => { const value = { ...filters, ...next, page: next.search !== undefined || next.status !== undefined || next.classId !== undefined || next.billingMonth !== undefined ? 1 : (next.page ?? filters.page) }; const result = new URLSearchParams({ month: value.billingMonth }); if (value.search) result.set('search', value.search); if (value.status) result.set('status', value.status); if (value.classId) result.set('classId', value.classId); if (value.page > 1) result.set('page', String(value.page)); setParams(result); };
  return <section className="page invoices-page"><div className="page-heading"><div><h1>Hóa đơn</h1><p>Tra cứu hóa đơn theo tháng, học sinh và trạng thái.</p></div></div>
    <div className="table-toolbar"><label>Tháng<input aria-label="Tháng hóa đơn" type="month" value={filters.billingMonth} onChange={(event) => updateFilters({ billingMonth: event.target.value })} /></label><label>Tìm học sinh<input value={filters.search} onChange={(event) => updateFilters({ search: event.target.value })} placeholder="Tìm theo tên học sinh" /></label><label>Trạng thái<select value={filters.status} onChange={(event) => updateFilters({ status: event.target.value as InvoiceFilters['status'] })}><option value="">Tất cả</option><option value="DRAFT">Nháp</option><option value="PENDING">Chờ xác nhận</option><option value="COMPLETED">Đã hoàn tất</option></select></label><label>Lớp snapshot<select aria-label="Lớp snapshot" value={filters.classId} onChange={(event) => updateFilters({ classId: event.target.value })} disabled={classes.isPending || Boolean(classes.error)}><option value="">Tất cả lớp</option>{classes.data?.data.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name}{schoolClass.status === 'ARCHIVED' ? ' (Đã lưu trữ)' : ''}</option>)}</select></label></div>
    {!hasValidMonth || invoices.isPending ? <div className="table-card skeleton" aria-live="polite">Đang tải hóa đơn...</div> : invoices.error ? <div className="table-card error-state" role="alert"><p>Không thể tải danh sách hóa đơn.</p><button type="button" onClick={() => void invoices.refetch()}>Thử lại</button></div> : invoices.data!.data.length === 0 && invoices.data!.meta.total > 0 ? <div className="table-card empty-state"><p>Trang này không còn hóa đơn.</p><div className="pagination"><span>Trang {invoices.data!.meta.page} / {invoices.data!.meta.pageCount}</span><button type="button" onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button></div></div> : invoices.data!.data.length === 0 ? <div className="table-card empty-state"><p>Chưa có hóa đơn trong {formatMonth(filters.billingMonth)}.</p><p id="invoice-creation-unavailable" role="status">Chức năng tạo hóa đơn tháng sẽ có ở bước tiếp theo.</p><button className="primary-action" type="button" disabled aria-describedby="invoice-creation-unavailable">Tạo hóa đơn tháng</button></div> : <><div className="table-card table-scroll"><table aria-label={`Danh sách hóa đơn tháng ${formatMonth(filters.billingMonth)}`}><caption>Hóa đơn tháng {formatMonth(filters.billingMonth)}{filters.search ? `, tìm ${filters.search}` : ''}</caption><thead><tr><th className="invoice-identity">Học sinh</th><th>Lớp snapshot</th><th>Trạng thái</th><th className="money">Tổng cộng</th></tr></thead><tbody>{invoices.data!.data.map((item) => <tr key={item.id}><th className="invoice-identity" scope="row"><Link to={`/hoa-don/${item.id}`}>{item.student.name}</Link>{item.student.nickname && <span className="student-names">{item.student.nickname}</span>}</th><td>{item.schoolClass.name}</td><td><span className={`status invoice-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span></td><td className="money">{formatVnd(item.total)}</td></tr>)}</tbody></table></div><div className="pagination"><span>Trang {invoices.data!.meta.page} / {invoices.data!.meta.pageCount}</span><button type="button" disabled={filters.page <= 1} onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button><button type="button" disabled={filters.page >= invoices.data!.meta.pageCount} onClick={() => updateFilters({ page: filters.page + 1 })}>Sau</button></div></>}</section>;
}
