import { Dialog } from '@base-ui/react/dialog';
import { useEffect, useRef, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { ApiError, ApiTimeoutError, createOperationId } from '../../app/api/client';
import { useActiveClassesForPicker, useClassesForInvoicePicker } from '../classes/api';
import { createInvoiceBatch, getInvoiceBatchOperation, type BatchInput, type BatchPreview, type BatchResult, type InvoiceFilters, type InvoiceStatus, useBatchPreview, useInvoices } from './api';

function currentMonth(): string { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; }
function formatMonth(month: string): string { const [year, value] = month.split('-'); return `${value}/${year}`; }
function formatVnd(amount: number): string { return `${new Intl.NumberFormat('vi-VN').format(amount)} đ`; }
function statusLabel(status: InvoiceStatus): string { return status === 'DRAFT' ? 'Nháp' : status === 'PENDING' ? 'Chờ xác nhận' : 'Đã hoàn tất'; }
const monthPattern = /^(?!0000)\d{4}-(0[1-9]|1[0-2])$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function filtersFromUrl(params: URLSearchParams): InvoiceFilters { const page = Number(params.get('page')); const status = params.get('status'); const month = params.get('month'); const classId = params.get('classId'); return { billingMonth: month && monthPattern.test(month) ? month : currentMonth(), search: params.get('search') ?? '', status: status === 'DRAFT' || status === 'PENDING' || status === 'COMPLETED' ? status : '', classId: classId && uuidPattern.test(classId) ? classId : '', page: Number.isInteger(page) && page > 0 ? page : 1 }; }

export function InvoicesPage(): React.JSX.Element {
  const [params, setParams] = useSearchParams(); const filters = filtersFromUrl(params); const hasValidMonth = monthPattern.test(params.get('month') ?? ''); const invoices = useInvoices(filters, hasValidMonth); const classes = useClassesForInvoicePicker(); const [creating, setCreating] = useState(false); const trigger = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!hasValidMonth) { const normalized = new URLSearchParams(params); normalized.set('month', filters.billingMonth); normalized.delete('page'); setParams(normalized, { replace: true }); } }, [filters.billingMonth, hasValidMonth, params, setParams]);
  const updateFilters = (next: Partial<InvoiceFilters>) => { const value = { ...filters, ...next, page: next.search !== undefined || next.status !== undefined || next.classId !== undefined || next.billingMonth !== undefined ? 1 : (next.page ?? filters.page) }; const result = new URLSearchParams({ month: value.billingMonth }); if (value.search) result.set('search', value.search); if (value.status) result.set('status', value.status); if (value.classId) result.set('classId', value.classId); if (value.page > 1) result.set('page', String(value.page)); setParams(result); };
  const close = () => { setCreating(false); requestAnimationFrame(() => trigger.current?.focus()); };
  const open = (event: React.MouseEvent<HTMLButtonElement>) => { trigger.current = event.currentTarget; setCreating(true); };
  return <section className="page invoices-page"><div className="page-heading"><div><h1>Hóa đơn</h1><p>Tra cứu hóa đơn theo tháng, học sinh và trạng thái.</p></div>{invoices.data?.data.length ? <button className="primary-action" type="button" onClick={open}>Tạo hóa đơn tháng</button> : null}</div>
    <div className="table-toolbar"><label>Tháng<input aria-label="Tháng hóa đơn" type="month" value={filters.billingMonth} onChange={(event) => updateFilters({ billingMonth: event.target.value })} /></label><label>Tìm học sinh<input value={filters.search} onChange={(event) => updateFilters({ search: event.target.value })} placeholder="Tìm theo tên học sinh" /></label><label>Trạng thái<select value={filters.status} onChange={(event) => updateFilters({ status: event.target.value as InvoiceFilters['status'] })}><option value="">Tất cả</option><option value="DRAFT">Nháp</option><option value="PENDING">Chờ xác nhận</option><option value="COMPLETED">Đã hoàn tất</option></select></label><label>Lớp snapshot<select aria-label="Lớp snapshot" value={filters.classId} onChange={(event) => updateFilters({ classId: event.target.value })} disabled={classes.isPending || Boolean(classes.error)}><option value="">Tất cả lớp</option>{classes.data?.data.map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name}{schoolClass.status === 'ARCHIVED' ? ' (Đã lưu trữ)' : ''}</option>)}</select></label></div>
    {!hasValidMonth || invoices.isPending ? <div className="table-card skeleton" aria-live="polite">Đang tải hóa đơn...</div> : invoices.error ? <div className="table-card error-state" role="alert"><p>Không thể tải danh sách hóa đơn.</p><button type="button" onClick={() => void invoices.refetch()}>Thử lại</button></div> : invoices.data!.data.length === 0 && invoices.data!.meta.total > 0 ? <div className="table-card empty-state"><p>Trang này không còn hóa đơn.</p><div className="pagination"><span>Trang {invoices.data!.meta.page} / {invoices.data!.meta.pageCount}</span><button type="button" onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button></div></div> : invoices.data!.data.length === 0 ? <div className="table-card empty-state"><p>Chưa có hóa đơn trong {formatMonth(filters.billingMonth)}.</p><button className="primary-action" type="button" onClick={open}>Tạo hóa đơn tháng</button></div> : <><div className="table-card table-scroll"><table aria-label={`Danh sách hóa đơn tháng ${formatMonth(filters.billingMonth)}`}><caption>Hóa đơn tháng {formatMonth(filters.billingMonth)}{filters.search ? `, tìm ${filters.search}` : ''}</caption><thead><tr><th className="invoice-identity">Học sinh</th><th>Lớp snapshot</th><th>Trạng thái</th><th className="money">Tổng cộng</th></tr></thead><tbody>{invoices.data!.data.map((item) => <tr key={item.id}><th className="invoice-identity" scope="row"><Link to={`/hoa-don/${item.id}`}>{item.student.name}</Link>{item.student.nickname && <span className="student-names">{item.student.nickname}</span>}</th><td>{item.schoolClass.name}</td><td><span className={`status invoice-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span></td><td className="money">{formatVnd(item.total)}</td></tr>)}</tbody></table></div><div className="pagination"><span>Trang {invoices.data!.meta.page} / {invoices.data!.meta.pageCount}</span><button type="button" disabled={filters.page <= 1} onClick={() => updateFilters({ page: filters.page - 1 })}>Trước</button><button type="button" disabled={filters.page >= invoices.data!.meta.pageCount} onClick={() => updateFilters({ page: filters.page + 1 })}>Sau</button></div></>}
    {creating && <BatchDialog month={filters.billingMonth} onClose={close} onComplete={() => { close(); updateFilters({ billingMonth: filters.billingMonth, status: 'DRAFT' }); }} />}</section>;
}

function BatchDialog({ month, onClose, onComplete }: { month: string; onClose: () => void; onComplete: () => void }): React.JSX.Element {
  const classes = useActiveClassesForPicker(); const preview = useBatchPreview(); const queryClient = useQueryClient(); const [billingMonth, setBillingMonth] = useState(month); const [allActiveClasses, setAllActiveClasses] = useState(true); const [classIds, setClassIds] = useState<string[]>([]); const [result, setResult] = useState<BatchResult>(); const [error, setError] = useState(''); const [checking, setChecking] = useState(false); const [submitting, setSubmitting] = useState(false); const operationId = useRef<string | undefined>(undefined);
  const input = (): BatchInput => ({ billingMonth, allActiveClasses, ...(!allActiveClasses ? { classIds } : {}) }); const resetPreview = () => { preview.reset(); setError(''); }; const locked = preview.isPending || checking || submitting;
  const check = () => { setError(''); setResult(undefined); preview.mutate(input(), { onError: (cause) => setError(cause instanceof ApiError ? cause.message : 'Không thể xem trước hóa đơn.') }); };
  const applyResult = (created: BatchResult) => { setResult(created); void queryClient.invalidateQueries({ queryKey: ['invoices'] }); };
  const create = async () => { if (!preview.data?.eligibleCount || submitting) return; setError(''); setSubmitting(true); operationId.current ??= createOperationId(); try { applyResult(await createInvoiceBatch(input(), operationId.current)); } catch (cause) { if (!(cause instanceof ApiTimeoutError)) { setError(cause instanceof ApiError ? cause.message : 'Không thể tạo hóa đơn.'); return; } setChecking(true); for (;;) { try { const reconciled = await getInvoiceBatchOperation(operationId.current); if ('state' in reconciled) { await new Promise((resolve) => setTimeout(resolve, 500)); continue; } applyResult(reconciled); break; } catch (lookupError) { if (lookupError instanceof ApiError && lookupError.status === 404) { setError('Máy chủ xác nhận chưa áp dụng thao tác. Bạn có thể thử lại.'); operationId.current = undefined; } else setError('Không thể đối soát kết quả tạo hóa đơn.'); break; } } setChecking(false); } finally { setSubmitting(false); } };
  return <Dialog.Root open onOpenChange={(open) => { if (!open && !locked) onClose(); }}><Dialog.Portal><Dialog.Backdrop className="dialog-backdrop" /><Dialog.Popup className="dialog"><Dialog.Title>Tạo hóa đơn tháng</Dialog.Title>{result ? <><p>Đã tạo {result.createdCount} hóa đơn nháp.</p><SkipSummary skipped={result.skipped} /><div className="dialog-actions"><Link className="primary-action" to={`/hoa-don?month=${billingMonth}&status=DRAFT`} onClick={onComplete}>Xem hóa đơn nháp</Link></div></> : <><label>Tháng<input aria-label="Tháng tạo hóa đơn" type="month" value={billingMonth} disabled={locked} onChange={(event) => { resetPreview(); setBillingMonth(event.target.value); }} /></label><fieldset disabled={locked || classes.isPending}><legend>Phạm vi</legend><label><input type="radio" checked={allActiveClasses} onChange={() => { resetPreview(); setAllActiveClasses(true); }} /> Tất cả lớp đang hoạt động</label><label><input type="radio" checked={!allActiveClasses} onChange={() => { resetPreview(); setAllActiveClasses(false); }} /> Chọn lớp</label>{!allActiveClasses && classes.data?.data.map((item) => <label key={item.id}><input type="checkbox" checked={classIds.includes(item.id)} onChange={(event) => { resetPreview(); setClassIds((ids) => event.target.checked ? [...ids, item.id] : ids.filter((id) => id !== item.id)); }} /> {item.name}</label>)}</fieldset><button type="button" onClick={check} disabled={locked || !monthPattern.test(billingMonth) || (!allActiveClasses && !classIds.length)}>Xem trước</button>{preview.data && <div aria-live="polite"><p>Có {preview.data.eligibleCount} học sinh đủ điều kiện.</p><SkipSummary skipped={preview.data.skipped} /></div>}{error && <p role="alert">{error}</p>}<div className="dialog-actions"><Dialog.Close render={<button type="button" disabled={locked}>Hủy</button>} /><button className="primary-action" type="button" disabled={locked || !preview.data?.eligibleCount} onClick={() => void create()}>{checking ? 'Đang kiểm tra...' : submitting ? 'Đang tạo...' : 'Tạo hóa đơn nháp'}</button></div></>}</Dialog.Popup></Dialog.Portal></Dialog.Root>;
}
function SkipSummary({ skipped }: { skipped: BatchPreview['skipped'] }): React.JSX.Element { return <p>Bỏ qua: học sinh không hoạt động {skipped.inactiveStudent}, thiếu lớp {skipped.missingClass}, lớp lưu trữ {skipped.archivedClass}, đã có hóa đơn {skipped.existingInvoice}.</p>; }
