import { Body, Controller, Get, Headers, Param, Post, Query, Req } from '@nestjs/common';
import { audienceConfig } from '../auth/auth.config.js';
import { AuthService } from '../auth/auth.service.js';
import { assertCookieMutation } from '../common/mutation-protection.js';
import { SettingsService } from './settings.service.js';

type RequestLike = { headers: Record<string, string | undefined> };
const cookie = (request: RequestLike, name: string) => request.headers.cookie?.split(';').map((item) => item.trim().split('=')).find(([key]) => key === name)?.[1];

@Controller('api/app/schools/:schoolId/settings')
export class SettingsController {
  constructor(private readonly auth: AuthService, private readonly settings: SettingsService) {}
  private identity(request: RequestLike) { return this.auth.session('app', cookie(request, audienceConfig('app').cookieName)).userIdentityId; }
  private mutation(request: RequestLike, key?: string) { const config = audienceConfig('app'); return assertCookieMutation(request, config.origin, config.csrfCookieName, key); }
  @Get() async read(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Query('asOf') asOf?: string) { return { data: await this.settings.read(this.identity(request), schoolId, asOf) }; }
  @Post('profile-versions') async profile(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createProfile(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('calendar-versions') async calendar(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createCalendar(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('finance-policy-versions') async financePolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createFinancePolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('attendance-policy-versions') async attendancePolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createAttendancePolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('handover-policy-versions') async handoverPolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createHandoverPolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('daily-journal-policy-versions') async dailyJournalPolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createDailyJournalPolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('leave-policy-versions') async leavePolicy(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createLeavePolicy(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('bank-accounts') async bankAccount(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createBankAccount(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('holidays') async createHoliday(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.createHoliday(this.identity(request), schoolId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('holidays/:holidayId') async updateHoliday(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('holidayId') holidayId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.updateHoliday(this.identity(request), schoolId, holidayId, this.mutation(request, key), operationId ?? '', body) }; }
  @Post('holidays/:holidayId/delete') async deleteHoliday(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('holidayId') holidayId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.settings.deleteHoliday(this.identity(request), schoolId, holidayId, this.mutation(request, key), operationId ?? '') }; }
  @Post(':kind/:versionId/delete') async deleteVersion(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('kind') kind: string, @Param('versionId') versionId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string) { return { data: await this.settings.deleteVersion(this.identity(request), schoolId, kind, versionId, this.mutation(request, key), operationId ?? '') }; }
  @Post('bank-accounts/:bankAccountId/lifecycle') async bankAccountLifecycle(@Req() request: RequestLike, @Param('schoolId') schoolId: string, @Param('bankAccountId') bankAccountId: string, @Headers('idempotency-key') key: string, @Headers('x-operation-id') operationId: string, @Body() body: unknown) { return { data: await this.settings.transitionBankAccount(this.identity(request), schoolId, bankAccountId, this.mutation(request, key), operationId ?? '', body) }; }
}
