import { BadRequestException, ConflictException, ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { AuthorizationService } from '../authorization/authorization.service.js';
import { auditData } from '../common/audit.js';
import { requestFingerprint } from '../common/mutation-protection.js';
import { isOperationIdempotencyCollision } from '../common/operation-idempotency.js';
import { PrismaService } from '../identity/prisma.service.js';

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const routes = { profile: 'POST /api/app/schools/:schoolId/settings/profile-versions', calendar: 'POST /api/app/schools/:schoolId/settings/calendar-versions' };

@Injectable()
export class SettingsService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService) {}
  private async actor(identityId: string, schoolId: string) { return this.authorization.resolve(identityId, schoolId, 'app', 'SETTINGS_MANAGE'); }
  private date(value: unknown, field: string) { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value) || new Date(`${value}T00:00:00.000Z`).toISOString().slice(0, 10) !== value) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { [field]: 'Ngày không hợp lệ.' } }); return value; }
  private text(value: unknown, field: string, required = true, limit = 200) { const text = typeof value === 'string' ? value.trim() : ''; if ((required && !text) || text.length > limit) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { [field]: required ? `Cần từ 1 đến ${limit} ký tự.` : `Không quá ${limit} ký tự.` } }); return text || null; }
  private today() { const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); return `${parts.find((part) => part.type === 'year')!.value}-${parts.find((part) => part.type === 'month')!.value}-${parts.find((part) => part.type === 'day')!.value}`; }
  private profileDto(value: any) { return value && { id: value.id, effectiveFrom: value.effectiveFrom.toISOString().slice(0, 10), schoolName: value.schoolName, address: value.address, phone: value.phone, createdAt: value.createdAt.toISOString() }; }
  private calendarDto(value: any) { return value && { id: value.id, effectiveFrom: value.effectiveFrom.toISOString().slice(0, 10), workweek: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'], nonOperatingWeekdays: ['SUNDAY'], createdAt: value.createdAt.toISOString(), holidays: value.holidays.map((holiday: any) => ({ id: holiday.id, name: holiday.name, startsOn: holiday.startsOn.toISOString().slice(0, 10), endsOn: holiday.endsOn.toISOString().slice(0, 10) })) }; }
  async read(identityId: string, schoolId: string, asOf?: string) {
    await this.actor(identityId, schoolId); const day = asOf ? this.date(asOf, 'asOf') : this.today(); const where = { schoolId, effectiveFrom: { lte: new Date(`${day}T00:00:00.000Z`) } };
    const [profile, calendar] = await Promise.all([this.prisma.schoolProfileVersion.findFirst({ where, orderBy: { effectiveFrom: 'desc' } }), this.prisma.schoolCalendarVersion.findFirst({ where, include: { holidays: { orderBy: { startsOn: 'asc' } } }, orderBy: { effectiveFrom: 'desc' } })]);
    return { asOf: day, timezone: 'Asia/Ho_Chi_Minh', profile: this.profileDto(profile), calendar: this.calendarDto(calendar) };
  }
  async createProfile(identityId: string, schoolId: string, key: string, operationId: string, body: any) {
    const actor = await this.actor(identityId, schoolId); const input = { effectiveFrom: this.date(body?.effectiveFrom, 'effectiveFrom'), schoolName: this.text(body?.schoolName, 'schoolName')!, address: this.text(body?.address, 'address', false, 500), phone: this.text(body?.phone, 'phone', false, 30) };
    return this.mutate(actor, identityId, schoolId, routes.profile, key, operationId, input, async (tx, operation) => { const prior = await tx.schoolProfileVersion.findFirst({ where: { schoolId, effectiveFrom: { lt: new Date(`${input.effectiveFrom}T00:00:00.000Z`) } }, orderBy: { effectiveFrom: 'desc' } }); try { const profile = await tx.schoolProfileVersion.create({ data: { schoolId, ...input, effectiveFrom: new Date(`${input.effectiveFrom}T00:00:00.000Z`), actorIdentityId: identityId, membershipId: actor.membershipId } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'SCHOOL_PROFILE_VERSION_CREATED', operation, { oldValue: this.profileDto(prior), newValue: this.profileDto(profile) }); return this.profileDto(profile); } catch (error) { if (this.unique(error)) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { effectiveFrom: 'Đã có phiên bản tại ngày hiệu lực này.' } }); throw error; } });
  }
  async createCalendar(identityId: string, schoolId: string, key: string, operationId: string, body: any) {
    const actor = await this.actor(identityId, schoolId); const effectiveFrom = this.date(body?.effectiveFrom, 'effectiveFrom'); const holidays = Array.isArray(body?.holidays) ? body.holidays.map((item: any) => ({ name: this.text(item?.name, 'holidayName')!, startsOn: this.date(item?.startsOn, 'startsOn'), endsOn: this.date(item?.endsOn, 'endsOn') })) : [];
    for (const holiday of holidays) if (holiday.endsOn < holiday.startsOn) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { endsOn: 'Ngày kết thúc không được trước ngày bắt đầu.' } });
    for (const [index, holiday] of holidays.entries()) for (const other of holidays.slice(index + 1)) if (holiday.startsOn <= other.endsOn && other.startsOn <= holiday.endsOn) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { startsOn: 'Các khoảng nghỉ không được chồng lấn.' } });
    return this.mutate(actor, identityId, schoolId, routes.calendar, key, operationId, { effectiveFrom, holidays }, async (tx, operation) => { const prior = await tx.schoolCalendarVersion.findFirst({ where: { schoolId, effectiveFrom: { lt: new Date(`${effectiveFrom}T00:00:00.000Z`) } }, include: { holidays: true }, orderBy: { effectiveFrom: 'desc' } }); try { const calendar = await tx.schoolCalendarVersion.create({ data: { schoolId, effectiveFrom: new Date(`${effectiveFrom}T00:00:00.000Z`), actorIdentityId: identityId, membershipId: actor.membershipId, holidays: { create: holidays.map((holiday: { name: string; startsOn: string; endsOn: string }) => ({ ...holiday, startsOn: new Date(`${holiday.startsOn}T00:00:00.000Z`), endsOn: new Date(`${holiday.endsOn}T00:00:00.000Z`) })) } }, include: { holidays: { orderBy: { startsOn: 'asc' } } } }); await this.audit(tx, schoolId, identityId, actor.membershipId, 'SCHOOL_CALENDAR_VERSION_CREATED', operation, { oldValue: this.calendarDto(prior), newValue: this.calendarDto(calendar) }); return this.calendarDto(calendar); } catch (error) { if (this.unique(error)) throw new BadRequestException({ code: 'VALIDATION_ERROR', message: 'Dữ liệu không hợp lệ.', fieldErrors: { effectiveFrom: 'Đã có phiên bản tại ngày hiệu lực này.' } }); throw error; } });
  }
  private unique(error: unknown) { return Boolean(error && typeof error === 'object' && (error as { code?: string }).code === 'P2002'); }
  private async audit(tx: any, schoolId: string, identityId: string, membershipId: string, action: string, operationId: string, provenance: object) { await tx.auditRecord.create({ data: auditData(schoolId, { identityId, type: 'SCHOOL_MEMBERSHIP', reference: membershipId, membershipId }, action, { operationId, ...provenance }) }); }
  private async mutate(actor: { membershipId: string }, identityId: string, schoolId: string, route: string, key: string, operationId: string, body: unknown, work: (tx: any, operationId: string) => Promise<unknown>) {
    if (!uuid.test(key) || !uuid.test(operationId)) throw new UnauthorizedException({ code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Cần Idempotency-Key và X-Operation-Id UUID.' }); const fingerprint = requestFingerprint(body); const existing = await this.prisma.operation.findFirst({ where: { schoolId, actorReference: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP', route, idempotencyKey: key } }); if (existing) { if (existing.fingerprint !== fingerprint) throw new ConflictException({ code: 'IDEMPOTENCY_CONFLICT', message: 'Idempotency-Key đã dùng cho yêu cầu khác.' }); return { id: existing.id, status: existing.status, outcome: existing.outcome }; }
    try { return await this.prisma.$transaction(async (tx) => { await tx.$queryRaw`SELECT 1 FROM "School" WHERE "id" = ${schoolId}::uuid FOR UPDATE`; const membership = await tx.schoolMembership.findFirst({ where: { id: actor.membershipId, schoolId, userIdentityId: identityId, status: 'ACTIVE', school: { status: 'ACTIVE' }, roleGrants: { some: { role: 'SCHOOL_ADMIN' } } } }); if (!membership) throw new ForbiddenException({ code: 'CAPABILITY_DENIED', message: 'Bạn không có quyền thực hiện thao tác này.' }); const operation = await tx.operation.create({ data: { id: operationId, schoolId, membershipId: actor.membershipId, actorIdentityId: identityId, actorType: 'SCHOOL_MEMBERSHIP', actorReference: actor.membershipId, route, idempotencyKey: key, fingerprint } }); const outcome = await work(tx, operation.id); const completed = await tx.operation.update({ where: { id: operation.id }, data: { status: 'COMPLETED', outcome: outcome as any } }); return { id: completed.id, status: completed.status, outcome: completed.outcome }; }); } catch (error) { if (isOperationIdempotencyCollision(error)) { const replay = await this.prisma.operation.findFirst({ where: { schoolId, actorReference: actor.membershipId, actorType: 'SCHOOL_MEMBERSHIP', route, idempotencyKey: key } }); if (replay && replay.fingerprint === fingerprint) return { id: replay.id, status: replay.status, outcome: replay.outcome }; } throw error; }
  }
}
