import { useLayoutEffect, useRef, useState } from 'react';

type Student = { studentId: string; fullName: string; state: 'PRESENT' | 'ABSENT' | 'ON_LEAVE' | 'NOT_RECORDED'; evidenceId: string | null; updatedAt: string | null };
type Roster = { classId: string; attendanceOn: string; photoEvidenceMode: 'REQUIRED' | 'OPTIONAL'; students: Student[] };
const apiUrl = typeof __API_URL__ === 'undefined' ? '' : __API_URL__;
const cookie = (name: string) => document.cookie.split('; ').find((entry) => entry.startsWith(`${name}=`))?.slice(name.length + 1) ?? '';
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date());

export function AttendanceWorkspace({ schoolId, onDirty }: { schoolId: string; onDirty: (dirty: boolean) => void }) {
  const [classId, setClassId] = useState(''); const [attendanceOn, setAttendanceOn] = useState(today()); const [roster, setRoster] = useState<Roster>(); const [evidence, setEvidence] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [fieldError, setFieldError] = useState(''); const [pending, setPending] = useState<string>(); const operation = useRef<{ id: string; key: string } | undefined>(undefined);
  useLayoutEffect(() => { setClassId(''); setEvidence({}); setRoster(undefined); setError(''); setFieldError(''); setPending(undefined); operation.current = undefined; onDirty(false); }, [schoolId, onDirty]);
  const load = async () => { setError(''); setFieldError(''); const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/attendance-roster?classId=${encodeURIComponent(classId)}&attendanceOn=${attendanceOn}`, { credentials: 'include' }); const payload = await response.json().catch(() => ({})); if (!response.ok) return setError(payload.message ?? 'Không thể tải danh sách điểm danh.'); setRoster(payload.data); };
  const reconcile = async () => { if (!operation.current) return; const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/operations/${operation.current.id}`, { credentials: 'include' }); const payload = await response.json().catch(() => ({})); if (response.ok && payload.data?.status === 'COMPLETED') { operation.current = undefined; setPending(undefined); onDirty(false); await load(); } else if (response.ok) setError('Đang kiểm tra kết quả với hệ thống'); else { setPending(undefined); setError('Không thể xác nhận kết quả. Hãy kiểm tra lại trước khi gửi lại.'); } };
  const record = async (student: Student, state: 'PRESENT' | 'ABSENT') => { const evidenceId = state === 'PRESENT' ? evidence[student.studentId] || student.evidenceId : null; const current = operation.current ?? { id: crypto.randomUUID(), key: crypto.randomUUID() }; operation.current = current; setPending(student.studentId); setError(''); setFieldError(''); onDirty(true); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 15000); try { const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/attendance`, { method: 'POST', credentials: 'include', signal: controller.signal, headers: { 'content-type': 'application/json', 'x-csrf-token': cookie('teacher_csrf'), 'idempotency-key': current.key, 'x-operation-id': current.id }, body: JSON.stringify({ classId, studentId: student.studentId, attendanceOn, state, evidenceId }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setPending(undefined); operation.current = undefined; setFieldError(payload.fieldErrors?.evidenceId ?? ''); await load(); return setError(payload.message ?? 'Không thể ghi điểm danh.'); } operation.current = undefined; setPending(undefined); onDirty(false); await load(); } catch { setError('Đang kiểm tra kết quả với hệ thống'); await reconcile(); } finally { window.clearTimeout(timeout); } };
  return <section aria-labelledby="attendance-title"><h2 id="attendance-title">Điểm danh lớp</h2><p>Trạng thái chỉ được xác nhận sau phản hồi từ hệ thống.</p><div><label>Mã lớp <input aria-label="Mã lớp" value={classId} onChange={(event) => setClassId(event.target.value)} /></label><label>Ngày <input aria-label="Ngày điểm danh" type="date" value={attendanceOn} onChange={(event) => setAttendanceOn(event.target.value)} /></label><button disabled={!classId} onClick={() => void load()}>Tải danh sách</button></div>{error && <div role="alert" tabIndex={-1}>{error}</div>}{fieldError && <p role="alert">Bằng chứng: {fieldError}</p>}{roster && <table><caption>Danh sách lớp ngày {attendanceOn}</caption><thead><tr><th>Học sinh</th><th>Trạng thái xác nhận</th><th>Thao tác</th></tr></thead><tbody>{roster.students.map((student) => <tr key={student.studentId}><td>{student.fullName}</td><td>{student.state}{student.state === 'ON_LEAVE' ? ' · Có nghỉ đã duyệt' : ''}{student.updatedAt ? ` · ${new Date(student.updatedAt).toLocaleTimeString('vi-VN')}` : ''}</td><td><label>Bằng chứng {roster.photoEvidenceMode === 'REQUIRED' ? '(bắt buộc khi ghi có mặt)' : '(tùy chọn)'}<input aria-label={`Bằng chứng ${student.fullName}`} value={evidence[student.studentId] ?? student.evidenceId ?? ''} onChange={(event) => { setEvidence({ ...evidence, [student.studentId]: event.target.value }); onDirty(true); }} /></label><button disabled={Boolean(pending)} onClick={() => void record(student, 'PRESENT')}>Có mặt</button><button disabled={Boolean(pending)} onClick={() => void record(student, 'ABSENT')}>Vắng mặt</button></td></tr>)}</tbody></table>}{pending && <p aria-live="polite">Đang kiểm tra kết quả với hệ thống</p>}</section>;
}
