import { useLayoutEffect, useRef, useState } from 'react';

type Student = { studentId: string; fullName: string; pickedUpAt: string | null; evidenceId: string | null; evidenceAvailability?: 'AVAILABLE' | 'EXPIRED' | null; evidenceMessage?: string | null };
type Roster = { handoverOn: string; photoEvidenceMode: 'REQUIRED' | 'OPTIONAL'; students: Student[] };
const apiUrl = typeof __API_URL__ === 'undefined' ? '' : __API_URL__;
const cookie = (name: string) => document.cookie.split('; ').find((entry) => entry.startsWith(`${name}=`))?.slice(name.length + 1) ?? '';
const hcmParts = (value = new Date()) => { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(value); const get = (type: string) => parts.find((part) => part.type === type)!.value; return { day: `${get('year')}-${get('month')}-${get('day')}`, time: `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}` }; };
const hcmTime = (instant: string) => hcmParts(new Date(instant)).time;

export function HandoverWorkspace({ schoolId, onDirty }: { schoolId: string; onDirty: (dirty: boolean) => void }) {
  const initial = hcmParts();
  const [handoverOn, setHandoverOn] = useState(initial.day); const [roster, setRoster] = useState<Roster>(); const [evidence, setEvidence] = useState<Record<string, string>>({}); const [pickedUpAt, setPickedUpAt] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [fieldError, setFieldError] = useState(''); const [pending, setPending] = useState<string>(); const operation = useRef<{ id: string; key: string } | undefined>(undefined); const errorRef = useRef<HTMLDivElement>(null);
  const reset = () => { setRoster(undefined); setEvidence({}); setPickedUpAt({}); setError(''); setFieldError(''); setPending(undefined); operation.current = undefined; onDirty(false); };
  useLayoutEffect(() => { reset(); }, [schoolId]);
  useLayoutEffect(() => { if (error) errorRef.current?.focus(); }, [error]);
  const load = async () => { setError(''); setFieldError(''); const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/handover-roster?handoverOn=${handoverOn}`, { credentials: 'include' }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setRoster(undefined); return setError(payload.message ?? 'Không thể tải danh sách bàn giao.'); } setRoster(payload.data); };
  const reconcile = async (success?: (outcome: any) => Promise<void> | void) => { if (!operation.current) return; const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/operations/${operation.current.id}`, { credentials: 'include' }); const payload = await response.json().catch(() => ({})); if (response.ok && payload.data?.status === 'COMPLETED') { operation.current = undefined; setPending(undefined); onDirty(false); await success?.(payload.data.outcome); await load(); } else if (response.ok) setError('Đang kiểm tra kết quả với hệ thống'); else { setPending(undefined); setError('Không thể xác nhận kết quả. Hãy kiểm tra lại trước khi gửi lại.'); } };
  const upload = async (student: Student, file: File) => { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) return setFieldError('Chỉ nhận ảnh JPEG, PNG hoặc WebP.'); const current = { id: crypto.randomUUID(), key: crypto.randomUUID() }; operation.current = current; setPending(student.studentId); setError(''); setFieldError(''); onDirty(true); const send = async () => { const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/handover-evidence?handoverOn=${handoverOn}`, { method: 'POST', credentials: 'include', headers: { 'content-type': file.type, 'x-csrf-token': cookie('teacher_csrf'), 'idempotency-key': current.key, 'x-operation-id': current.id }, body: file }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(payload.message), { payload }); return payload.data; }; try { const outcome = await send(); operation.current = undefined; setPending(undefined); setEvidence((currentEvidence) => ({ ...currentEvidence, [student.studentId]: outcome.id })); onDirty(true); } catch (cause) { const failure = cause as { payload?: any }; if (failure.payload) { operation.current = undefined; setPending(undefined); setFieldError(failure.payload.message ?? 'Không thể tải bằng chứng.'); } else await reconcile((outcome) => setEvidence((currentEvidence) => ({ ...currentEvidence, [student.studentId]: outcome.id }))); } };
  const record = async (student: Student) => { const current = { id: crypto.randomUUID(), key: crypto.randomUUID() }; operation.current = current; setPending(student.studentId); setError(''); setFieldError(''); onDirty(true); const localTime = pickedUpAt[student.studentId] ?? hcmParts().time; const instant = new Date(`${localTime}:00+07:00`).toISOString(); const body = { studentId: student.studentId, handoverOn, pickedUpAt: instant, evidenceId: evidence[student.studentId] || null }; const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 15000); try { const response = await fetch(`${apiUrl}/api/teacher/schools/${schoolId}/handovers`, { method: 'POST', credentials: 'include', signal: controller.signal, headers: { 'content-type': 'application/json', 'x-csrf-token': cookie('teacher_csrf'), 'idempotency-key': current.key, 'x-operation-id': current.id }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { operation.current = undefined; setPending(undefined); setFieldError(payload.fieldErrors?.evidenceId ?? payload.fieldErrors?.pickedUpAt ?? ''); await load(); return setError(payload.message ?? 'Không thể ghi nhận trả trẻ.'); } operation.current = undefined; setPending(undefined); onDirty(false); await load(); } catch { setError('Đang kiểm tra kết quả với hệ thống'); await reconcile(); } finally { window.clearTimeout(timeout); } };
  const changeDate = (value: string) => { setHandoverOn(value); reset(); };
  return <section aria-labelledby="handover-title"><h2 id="handover-title">Bàn giao - tham chiếu vận hành</h2><p>Ghi nhận giờ trả trẻ, không phải ủy quyền đón trẻ và không áp dụng phí.</p><label>Ngày <input aria-label="Ngày bàn giao" type="date" value={handoverOn} onChange={(event) => changeDate(event.target.value)} /></label><button onClick={() => void load()}>Tải danh sách</button>{error && <div ref={errorRef} role="alert" tabIndex={-1}>{error}</div>}{fieldError && <p role="alert">Bằng chứng hoặc giờ trả trẻ: {fieldError}</p>}{roster && <table><caption>Danh sách bàn giao ngày {handoverOn}</caption><thead><tr><th>Học sinh</th><th>Trạng thái xác nhận</th><th>Thao tác</th></tr></thead><tbody>{roster.students.map((student) => <tr key={student.studentId}><td>{student.fullName}</td><td>{student.pickedUpAt ? `Đã trả trẻ lúc ${new Date(student.pickedUpAt).toLocaleTimeString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}` : 'Chưa ghi nhận'}{student.evidenceAvailability === 'EXPIRED' ? ` · ${student.evidenceMessage}` : ''}</td><td>{!student.pickedUpAt && <><label>Giờ trả trẻ <input aria-label={`Giờ trả trẻ ${student.fullName}`} type="datetime-local" value={pickedUpAt[student.studentId] ?? hcmParts().time} onChange={(event) => { setPickedUpAt({ ...pickedUpAt, [student.studentId]: event.target.value }); onDirty(true); }} /></label><label>Bằng chứng {roster.photoEvidenceMode === 'REQUIRED' ? '(bắt buộc)' : '(tùy chọn)'}<input aria-label={`Bằng chứng bàn giao ${student.fullName}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={Boolean(pending)} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(student, file); }} />{evidence[student.studentId] && <span> Đã tải bằng chứng</span>}</label><button disabled={Boolean(pending) || (roster.photoEvidenceMode === 'REQUIRED' && !evidence[student.studentId])} onClick={() => void record(student)}>Xác nhận trả trẻ</button></>}</td></tr>)}</tbody></table>}{pending && <p aria-live="polite">Đang kiểm tra kết quả với hệ thống</p>}</section>;
}
